---
# file: roles/k8s_worker/defaults/main.yaml

k8s_defaults:

  cni_provider: flannel

  # NOTE: The pod subnet MUST be 10.244.0.0/16 since this is hardcoded in the default flannel yaml configuration
  pod_subnet: 10.244.0.0/16
  service_subnet: 10.245.0.0/16

k8s_config: "{{ k8s_defaults | combine(k8s | default({}), recursive=True) }}"
