---
# file: roles/kafka_mirrormaker/defaults/main.yaml

kafka_defaults:
  kafka_mirrormaker:
    etc_directory: /etc/kafka
    log_directory: /var/log/kafka

    user: kafka
    user_id: 330

    group: kafka
    group_id: 330

    kafka_broker:
      secure_broker_port: 9093
      username: mirrormaker

    prometheus_jmx_exporter:
      enabled: true
      port: 9130

kafka_config: "{{ kafka_defaults | combine(kafka | default({})) }}"
