---
# file: roles/gitea/tasks/redhat.yaml

- ansible.builtin.debug:
    msg: Applying the RedHat-specific Gitea configuration

- name: Install the Git packages
  ansible.builtin.yum:
    name:
    - git-core
    state: present

- name: Allow all hosts access to tcp port {{ gitea_config.port }}
  ansible.posix.firewalld:
    port: '{{ gitea_config.port }}/tcp'
    permanent: yes
    state: enabled
    immediate: yes
