---
# file: roles/gitea/tasks/ubuntu.yaml

- debug:
    msg: Applying the Ubuntu-specific Gitea configuration

- name: Install the Git packages
  apt:
    state: present
    name:
     - git

- name: Allow all hosts access to tcp port 80
  ufw:
    rule: allow
    port: '80'
    proto: tcp
