---
# file: roles/confluent_zookeeper/tasks/centos.yaml

- debug:
    msg: Applying the CentOS-specific ZooKeeper configuration

- name: Allow the other ZooKeeper hosts access to tcp port 2888 (Cluster1)
  firewalld:
    rich_rule: 'rule family=ipv4 source address={{ hostvars[item].ansible_default_ipv4.address }} port port=2888 protocol=tcp accept'
    state: enabled
    permanent: yes
    immediate: yes
  loop: "{{ confluent_zookeeper_cluster1_actual_hosts }}"
  when: ((inventory_hostname in confluent_zookeeper_cluster1_actual_hosts) and (item != inventory_hostname))

- name: Allow the other ZooKeeper hosts access to tcp port 2888 (Cluster2)
  firewalld:
    rich_rule: 'rule family=ipv4 source address={{ hostvars[item].ansible_default_ipv4.address }} port port=2888 protocol=tcp accept'
    state: enabled
    permanent: yes
    immediate: yes
  loop: "{{ confluent_zookeeper_cluster2_actual_hosts }}"
  when: ((inventory_hostname in confluent_zookeeper_cluster2_actual_hosts) and (item != inventory_hostname))

- name: Allow the other ZooKeeper hosts access to tcp port 3888 (Cluster1)
  firewalld:
    rich_rule: 'rule family=ipv4 source address={{ hostvars[item].ansible_default_ipv4.address }} port port=3888 protocol=tcp accept'
    state: enabled
    permanent: yes
    immediate: yes
  loop: "{{ confluent_zookeeper_cluster1_actual_hosts }}"
  when: ((inventory_hostname in confluent_zookeeper_cluster1_actual_hosts) and (item != inventory_hostname))

- name: Allow the other ZooKeeper hosts access to tcp port 3888 (Cluster2)
  firewalld:
    rich_rule: 'rule family=ipv4 source address={{ hostvars[item].ansible_default_ipv4.address }} port port=3888 protocol=tcp accept'
    state: enabled
    permanent: yes
    immediate: yes
  loop: "{{ confluent_zookeeper_cluster2_actual_hosts }}"
  when: ((inventory_hostname in confluent_zookeeper_cluster2_actual_hosts) and (item != inventory_hostname))

- name: Allow all the Kafka Server hosts access to tcp port {{ zookeeper_secure_client_port }} (Cluster1)
  firewalld:
    rich_rule: 'rule family=ipv4 source address={{ hostvars[item].ansible_default_ipv4.address }} port port={{ zookeeper_secure_client_port }} protocol=tcp accept'
    state: enabled
    permanent: yes
    immediate: yes
  loop: "{{ kafka_server_cluster1_actual_hosts | default([]) }}"
  when: (inventory_hostname in confluent_zookeeper_cluster1_actual_hosts)

- name: Allow all the Kafka Server hosts access to tcp port {{ zookeeper_secure_client_port }} (Cluster2)
  firewalld:
    rich_rule: 'rule family=ipv4 source address={{ hostvars[item].ansible_default_ipv4.address }} port port={{ zookeeper_secure_client_port }} protocol=tcp accept'
    state: enabled
    permanent: yes
    immediate: yes
  loop: "{{ kafka_server_cluster2_actual_hosts | default([]) }}"
  when: (inventory_hostname in confluent_zookeeper_cluster2_actual_hosts)

- name: Allow all access to tcp port {{ prometheus_zookeeper_jmx_exporter_port }} (Prometheus JMX Exporter Port)
  firewalld:
    port: '{{ prometheus_zookeeper_jmx_exporter_port }}/tcp'
    permanent: yes
    state: enabled
    immediate: yes
  when: ((prometheus_jmx_exporter_enabled is defined) and (prometheus_jmx_exporter_enabled != None) and (prometheus_jmx_exporter_enabled == true))

- name: Allow all access to tcp port {{ prometheus_zookeeper_exporter_port }} (Prometheus ZooKeeper Exporter Port)
  firewalld:
    port: '{{ prometheus_zookeeper_exporter_port }}/tcp'
    permanent: yes
    state: enabled
    immediate: yes
  when: ((prometheus_exporter_enabled is defined) and (prometheus_exporter_enabled != None) and (prometheus_exporter_enabled == true))

- name: Allow access to the remote JMX tcp ports
  block:
  - firewalld:
      port: '9998/tcp'
      permanent: yes
      state: enabled
      immediate: yes

  - firewalld:
      port: '9999/tcp'
      permanent: yes
      state: enabled
      immediate: yes

  when: ((zookeeper_enable_remote_jmx is defined) and (zookeeper_enable_remote_jmx != None) and (zookeeper_enable_remote_jmx == true))

