---
# file: roles/confluent_zookeeper/tasks/centos.yaml

- debug:
    msg: Applying the CentOS-specific ZooKeeper configuration

- name: Allow the other ZooKeeper hosts access to tcp port 2888
  firewalld:
    rich_rule: 'rule family=ipv4 source address={{ hostvars[item].ansible_default_ipv4.address }} port port=2888 protocol=tcp accept'
    state: enabled
    permanent: yes
    immediate: yes
  loop: "{{ zookeeper_hosts }}"

- name: Allow the other ZooKeeper hosts access to tcp port 3888
  firewalld:
    rich_rule: 'rule family=ipv4 source address={{ hostvars[item].ansible_default_ipv4.address }} port port=3888 protocol=tcp accept'
    state: enabled
    permanent: yes
    immediate: yes
  loop: "{{ zookeeper_hosts }}"

- name: Allow all the Kafka Server hosts access to tcp port {{ zookeeper_secure_client_port }}
  firewalld:
    rich_rule: 'rule family=ipv4 source address={{ hostvars[item].ansible_default_ipv4.address }} port port={{ zookeeper_secure_client_port }} protocol=tcp accept'
    state: enabled
    permanent: yes
    immediate: yes
  loop: "{{ kafka_server_hosts }}"

- name: Allow all access to tcp port {{ prometheus_zookeeper_jmx_exporter_port }} (Prometheus JMX Exporter Port)
  firewalld:
    port: '{{ prometheus_zookeeper_jmx_exporter_port }}/tcp'
    permanent: yes
    state: enabled
    immediate: yes
  when: ((prometheus_jmx_exporter_enabled is defined) and (prometheus_jmx_exporter_enabled != None) and (prometheus_jmx_exporter_enabled == true))

- name: Allow all access to tcp port {{ prometheus_zookeeper_exporter_port }} (Prometheus ZooKeeper Exporter Port)
  firewalld:
    port: '{{ prometheus_zookeeper_exporter_port }}/tcp'
    permanent: yes
    state: enabled
    immediate: yes
  when: ((prometheus_exporter_enabled is defined) and (prometheus_exporter_enabled != None) and (prometheus_exporter_enabled == true))

- name: Allow access to the remote JMX tcp ports
  block:
  - firewalld:
      port: '9998/tcp'
      permanent: yes
      state: enabled
      immediate: yes

  - firewalld:
      port: '9999/tcp'
      permanent: yes
      state: enabled
      immediate: yes

  when: ((zookeeper_enable_remote_jmx is defined) and (zookeeper_enable_remote_jmx != None) and (zookeeper_enable_remote_jmx == true))

