---
# file: roles/confluent_zookeeper/tasks/ubuntu.yaml

- debug:
    msg: Applying the Ubuntu-specific ZooKeeper configuration

- name: Enable the firewall
  ufw:
    state: enabled
    policy: deny

- name: Allow all access to tcp port 2888 to other ZooKeeper hosts (DC1)
  ufw:
    rule: allow
    source: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
    port: '2888'
    proto: tcp
  loop: "{{ confluent_zookeeper_dc1_actual_hosts }}"
  when: ((inventory_hostname in confluent_zookeeper_dc1_actual_hosts) and (item != inventory_hostname))

- name: Allow all access to tcp port 2888 to other ZooKeeper hosts (DC2)
  ufw:
    rule: allow
    source: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
    port: '2888'
    proto: tcp
  loop: "{{ confluent_zookeeper_dc2_actual_hosts }}"
  when: ((inventory_hostname in confluent_zookeeper_dc2_actual_hosts) and (item != inventory_hostname))

- name: Allow all access to tcp port 3888 to other ZooKeeper hosts (DC1)
  ufw:
    rule: allow
    source: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
    port: '3888'
    proto: tcp
  loop: "{{ confluent_zookeeper_dc1_actual_hosts }}"
  when: ((inventory_hostname in confluent_zookeeper_dc1_actual_hosts) and (item != inventory_hostname))

- name: Allow all access to tcp port 3888 to other ZooKeeper hosts (DC2)
  ufw:
    rule: allow
    source: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
    port: '3888'
    proto: tcp
  loop: "{{ confluent_zookeeper_dc2_actual_hosts }}"
  when: ((inventory_hostname in confluent_zookeeper_dc2_actual_hosts) and (item != inventory_hostname))

- name: Allow all access to tcp port {{ zookeeper_secure_client_port}} (Secure ZooKeeper Client Port) for Confluent Server hosts (DC1)
  ufw:
    rule: allow
    source: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
    port: '{{ zookeeper_secure_client_port }}'
    proto: tcp
  loop: "{{ confluent_kafka_server_dc1_actual_hosts | default([]) }}"
  when: (inventory_hostname in confluent_zookeeper_dc1_actual_hosts)

- name: Allow all access to tcp port {{ zookeeper_secure_client_port}} (Secure ZooKeeper Client Port) for Confluent Server hosts (DC2)
  ufw:
    rule: allow
    source: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
    port: '{{ zookeeper_secure_client_port }}'
    proto: tcp
  loop: "{{ confluent_kafka_server_dc2_actual_hosts | default([]) }}"
  when: (inventory_hostname in confluent_zookeeper_dc2_actual_hosts)

