---
# file: roles/k8s_common/meta/main.yaml

galaxy_info:
  author: Marcus Portmann
  description: Ansible Kubernetes Common Role
  company: http://mmp.guru
  license: Apache 2
  min_ansible_version: 2.9
  platforms:
  - name: EL
    versions:
     - 7
  - name: Ubuntu
    versions:
      - breezy
      - focal
  categories:
  - platform

# NOTE: The docker dependency overrides the default values for variables for the role to ensure a compatible version of Docker is installed
dependencies:
  - { role: docker, docker: { centos: { containerd: { package: containerd.io-1.2.13-3.1.el7.x86_64.rpm, package_version: 1.2.13 }, docker_ce: { package: docker-ce-19.03.8-3.el7.x86_64.rpm, package_version: 19.03.8 }, docker_ce_cli: { package: docker-ce-cli-19.03.8-3.el7.x86_64.rpm, package_version: 19.03.8 } }, ubuntu: { docker_ce: { package_version: 5:19.03.6~3-0~ubuntu-bionic } } } }
