---
# file: roles/k8s_istio/defaults/main.yaml

k8s_defaults:
  istio:
    enabled: false
    package_checksum: sha256:027ca706cadd96b3013b31bae1365ef94ed41feef0018e871f64a8c4e6275402
    package_version: 1.7.3

    istioctl_package_checksum: sha256:a66c45da3f390c881f87d97daa5be32c52d5bc8b87b0bc3680aa3148e0ebbf0b

    grafana:
      enabled: false
    kiali:
      enabled: true
    prometheus:
      enabled: false
    tracing:
      enabled: false

    demo_configuration_enabled: false

k8s_config: "{{ k8s_defaults | combine(k8s | default({}), recursive=True) }}"
