---
# file: roles/k8s_istio/defaults/main.yaml

k8s_defaults:
  istio:
    enabled: false
    package_checksum: sha256:1d00a2ea0cb7608ce2266fc65572ac9316978b01c0c2c8dd8c65efcb63f5fe97
    package_version: '1.10.0'

    istioctl_package_checksum: sha256:e1b89b5066afb87e98acc366d983b264c018a54d79221acc670de6a063de494b


    kiali:
      enabled: false
      helm_chart_version: '1.30.0'
      auth:
        strategy: 'anonymous'

k8s_config: "{{ k8s_defaults | combine(k8s | default({}), recursive=True) }}"
