---
# file: roles/k8s_istio/defaults/main.yaml

k8s_defaults:
  istio:
    enabled: false
    package_checksum: sha256:23eaa80a0c3edc8271fe82443b33958437c6c5a62f28bc1b7d04a71e416010a4
    package_version: '1.10.2'

    istioctl_package_checksum: sha256:916447886375d97fb8f3a769645bfcf883f4e725ce628a15c289e36e4c5ce061

    # For latest version of Helm chart see: https://github.com/kiali/helm-charts/releases
    kiali:
      enabled: false
      helm_chart_version: '1.36.0'
      auth:
        strategy: 'anonymous'

k8s_config: "{{ k8s_defaults | combine(k8s | default({}), recursive=True) }}"
