---
# file: roles/k8s_istio/defaults/main.yaml

k8s_defaults:
  istio:
    enabled: false
    package_checksum: sha256:f5fe82687f3777d6e5c9e4cda0d99bd03ff7aefaa9f10b0e608e0990a6ab000a
    package_version: '1.15.3'

    istioctl_package_checksum: sha256:de4dba51603b84b965d72e89c0491beca63421f3ae4d7324eda50ba3ea7d8b26

    # For latest version of Helm chart see: https://github.com/kiali/helm-charts/releases
    kiali:
      enabled: false
      helm_chart_version: '1.54.0'
      auth:
        strategy: 'anonymous'

k8s_config: "{{ k8s_defaults | combine(k8s | default({}), recursive=True) }}"
