---
# file: roles/k8s_istio/defaults/main.yaml

pki_root: ../../../pki

k8s_defaults:
  istio:
    enabled: false
    package_checksum: sha256:9e6c7f5cc52663a4177d6f275c500b4de5c59f075384c7084e3a7412921c310d
    package_version: 1.7.3

    istioctl_package_checksum: sha256:027ca706cadd96b3013b31bae1365ef94ed41feef0018e871f64a8c4e6275402

    grafana:
      enabled: false
    kiali:
      enabled: true
    prometheus:
      enabled: false
    tracing:
      enabled: false

    demo_configuration_enabled: false

k8s_config: "{{ k8s_defaults | combine(k8s | default({}), recursive=True) }}"
