---
# file: roles/kafka_zookeeper/tasks/centos.yaml

- debug:
    msg: Applying the CentOS-specific ZooKeeper configuration

- name: Allow the other ZooKeeper hosts access to tcp port 2888 (DC1)
  firewalld:
    rich_rule: 'rule family=ipv4 source address={{ hostvars[item].ansible_default_ipv4.address }} port port=2888 protocol=tcp accept'
    state: enabled
    permanent: yes
    immediate: yes
  loop: "{{ kafka_zookeeper_dc1_actual_hosts }}"
  when: ((inventory_hostname in kafka_zookeeper_dc1_actual_hosts) and (item != inventory_hostname))

- name: Allow the other ZooKeeper hosts access to tcp port 2888 (DC2)
  firewalld:
    rich_rule: 'rule family=ipv4 source address={{ hostvars[item].ansible_default_ipv4.address }} port port=2888 protocol=tcp accept'
    state: enabled
    permanent: yes
    immediate: yes
  loop: "{{ kafka_zookeeper_dc2_actual_hosts }}"
  when: ((inventory_hostname in kafka_zookeeper_dc2_actual_hosts) and (item != inventory_hostname))

- name: Allow the other ZooKeeper hosts access to tcp port 3888 (DC1)
  firewalld:
    rich_rule: 'rule family=ipv4 source address={{ hostvars[item].ansible_default_ipv4.address }} port port=3888 protocol=tcp accept'
    state: enabled
    permanent: yes
    immediate: yes
  loop: "{{ kafka_zookeeper_dc1_actual_hosts }}"
  when: ((inventory_hostname in kafka_zookeeper_dc1_actual_hosts) and (item != inventory_hostname))

- name: Allow the other ZooKeeper hosts access to tcp port 3888 (DC2)
  firewalld:
    rich_rule: 'rule family=ipv4 source address={{ hostvars[item].ansible_default_ipv4.address }} port port=3888 protocol=tcp accept'
    state: enabled
    permanent: yes
    immediate: yes
  loop: "{{ kafka_zookeeper_dc2_actual_hosts }}"
  when: ((inventory_hostname in kafka_zookeeper_dc2_actual_hosts) and (item != inventory_hostname))

- name: Allow all the Kafka Server hosts access to tcp port {{ zookeeper_secure_client_port }} (DC1)
  firewalld:
    rich_rule: 'rule family=ipv4 source address={{ hostvars[item].ansible_default_ipv4.address }} port port={{ zookeeper_secure_client_port }} protocol=tcp accept'
    state: enabled
    permanent: yes
    immediate: yes
  loop: "{{ kafka_server_dc1_actual_hosts | default([]) }}"
  when: (inventory_hostname in kafka_zookeeper_dc1_actual_hosts)

- name: Allow all the Kafka Server hosts access to tcp port {{ zookeeper_secure_client_port }} (DC2)
  firewalld:
    rich_rule: 'rule family=ipv4 source address={{ hostvars[item].ansible_default_ipv4.address }} port port={{ zookeeper_secure_client_port }} protocol=tcp accept'
    state: enabled
    permanent: yes
    immediate: yes
  loop: "{{ kafka_server_dc2_actual_hosts | default([]) }}"
  when: (inventory_hostname in kafka_zookeeper_dc2_actual_hosts)
