---
# file: roles/kafka_zookeeper/tasks/centos.yaml

- debug:
    msg: Applying the CentOS-specific Kafka ZooKeeper configuration

- name: Allow all access to tcp port 2182 (Secure ZooKeeper Client Port)
  firewalld:
    port: 2182/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: Add the zookeeper_clients firewalld zone
  firewalld:
    zone: zookeeper_clients
    state: present
    permanent: true

- name: Add the zookeeper_peers firewalld zone
  firewalld:
    zone: zookeeper_peers
    state: present
    permanent: true

- name: Reload service firewalld
  systemd:
    name: firewalld
    state: reloaded

- name: Allow access to tcp port 2182 for the zookeeper_clients firewalld zone
  firewalld:
    zone: zookeeper_clients
    port: 2182/tcp
    state: enabled
    permanent: true
    immediate: yes

- name: Allow access to tcp port 2888 for the zookeeper_peers firewalld zone
  firewalld:
    zone: zookeeper_peers
    port: 2888/tcp
    state: enabled
    permanent: true
    immediate: yes

- name: Allow access to tcp port 3888 for the zookeeper_peers firewalld zone
  firewalld:
    zone: zookeeper_peers
    port: 3888/tcp
    state: enabled
    permanent: true
    immediate: yes

- name: Allow the other Kafka ZooKeeper hosts access to the zookeeper_peers firewalld zone
  firewalld:
    zone: zookeeper_peers
    source: "{{ hostvars[item].ansible_default_ipv4.address }}"
    state: enabled
    permanent: yes
    immediate: yes
  loop: "{{ groups['kafka_zookeeper'] }}"
  when: (item != inventory_hostname)


- name: Allow all the Kafka Server hosts access to the zookeeper_clients firewalld zone
  firewalld:
    zone: zookeeper_clients
    source: "{{ hostvars[item].ansible_default_ipv4.address }}"
    state: enabled
    permanent: yes
    immediate: yes
  loop: "{{ groups['kafka_server'] | default([]) }}"

