---
# file: roles/kafka_zookeeper/tasks/ubuntu.yaml

- ansible.builtin.debug:
    msg: Applying the Ubuntu-specific ZooKeeper configuration

- name: Allow ZooKeeper hosts access to tcp port 2888
  community.general.ufw:
    rule: allow
    from_ip: "{{ (hostvars[item].ansible_default_ipv4.address|default(hostvars[item].ansible_all_ipv4_addresses[0])) }}"
    port: '2888'
    proto: tcp
  loop: "{{ zookeeper_hosts }}"

- name: Allow ZooKeeper hosts access to tcp port 3888
  community.general.ufw:
    rule: allow
    from_ip: "{{ (hostvars[item].ansible_default_ipv4.address|default(hostvars[item].ansible_all_ipv4_addresses[0])) }}"
    port: '3888'
    proto: tcp
  loop: "{{ zookeeper_hosts }}"

- name: Allow Kafka Server hosts access to tcp port {{ kafka_config.zookeeper.secure_client_port}}
  community.general.ufw:
    rule: allow
    from_ip: "{{ (hostvars[item].ansible_default_ipv4.address|default(hostvars[item].ansible_all_ipv4_addresses[0])) }}"
    port: '{{ kafka_config.zookeeper.secure_client_port }}'
    proto: tcp
  loop: "{{ kafka_server_hosts }}"

- name: Allow Prometheus Server hosts access to tcp port {{ kafka_config.zookeeper.prometheus_jmx_exporter.port }} (Prometheus JMX Exporter Port)
  community.general.ufw:
    rule: allow
    port: '{{ kafka_config.zookeeper.prometheus_jmx_exporter.port }}'
    proto: tcp
  loop: "{{ (groups['prometheus_server'] | default([])) }}"
  when: ((kafka_config.zookeeper.prometheus_jmx_exporter.enabled is defined) and (kafka_config.zookeeper.prometheus_jmx_exporter.enabled != None) and (kafka_config.zookeeper.prometheus_jmx_exporter.enabled == true))

- name: Allow Prometheus Server hosts access to tcp port {{ kafka_config.zookeeper.prometheus_exporter.port }} (ZooKeeper Prometheus Exporter Port)
  community.general.ufw:
    rule: allow
    port: '{{ kafka_config.zookeeper.prometheus_exporter.port }}'
    proto: tcp
  loop: "{{ (groups['prometheus_server'] | default([])) }}"
  when: ((kafka_config.zookeeper.prometheus_exporter.enabled is defined) and (kafka_config.zookeeper.prometheus_exporter.enabled != None) and (kafka_config.zookeeper.prometheus_exporter.enabled == true))

- name: Allow access to the remote JMX tcp ports
  block:
  - community.general.ufw:
      rule: allow
      port: '9998'
      proto: tcp
  - community.general.ufw:
      rule: allow
      port: '9999'
      proto: tcp
  when: ((kafka_config.zookeeper.enable_remote_jmx is defined) and (kafka_config.zookeeper.enable_remote_jmx != None) and (kafka_config.zookeeper.enable_remote_jmx == true))

- name: Allow Burrow hosts access to tcp port {{ kafka_config.zookeeper.secure_client_port}}
  community.general.ufw:
    rule: allow
    from_ip: "{{ (hostvars[item].ansible_default_ipv4.address|default(hostvars[item].ansible_all_ipv4_addresses[0])) }}"
    port: '{{ kafka_config.zookeeper.secure_client_port }}'
    proto: tcp
  loop: "{{ (groups['burrow'] | default([])) }}"

