---
# file: roles/kafka_zookeeper/tasks/ubuntu.yaml

- debug:
    msg: Applying the Ubuntu-specific Kafka ZooKeeper configuration

- name: Enable the firewall
  ufw:
    state: enabled
    policy: deny

- name: Allow all access to tcp port 2182 (Secure ZooKeeper Client Port)
  ufw:
    rule: allow
    port: '2182'
    proto: tcp

- name: Allow all access to tcp port 2888 to other Kafka ZooKeeper hosts
  ufw:
    source: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
    rule: allow
    port: '2888'
    proto: tcp
  loop: "{{ groups['kafka_zookeeper'] }}"
  when: (item != inventory_hostname)

- name: Allow all access to tcp port 3888 to other Kafka ZooKeeper hosts
  ufw:
    source: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
    rule: allow
    port: '3888'
    proto: tcp
  loop: "{{ groups['kafka_zookeeper'] }}"
  when: (item != inventory_hostname)

