---
# file: roles/kafka_zookeeper/tasks/ubuntu.yaml

- debug:
    msg: Applying the Ubuntu-specific ZooKeeper configuration

- name: Enable the firewall
  ufw:
    state: enabled
    policy: deny

- name: Allow all access to tcp port 2888 to other ZooKeeper hosts
  ufw:
    rule: allow
    source: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
    port: '2888'
    proto: tcp
  loop: "{{ zookeeper_hosts }}"

- name: Allow all access to tcp port 3888 to other ZooKeeper hosts
  ufw:
    rule: allow
    source: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
    port: '3888'
    proto: tcp
  loop: "{{ zookeeper_hosts }}"

- name: Allow all access to tcp port {{ zookeeper_secure_client_port}} (Secure ZooKeeper Client Port) for Kafka Server hosts
  ufw:
    rule: allow
    source: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
    port: '{{ zookeeper_secure_client_port }}'
    proto: tcp
  loop: "{{ kafka_server_hosts }}"

- name: Allow all access to tcp port {{ prometheus_zookeeper_jmx_exporter_port }} (Prometheus JMX Exporter Port)
  ufw:
    rule: allow
    port: '{{ prometheus_zookeeper_jmx_exporter_port }}'
    proto: tcp
  when: ((prometheus_jmx_exporter_enabled is defined) and (prometheus_jmx_exporter_enabled != None) and (prometheus_jmx_exporter_enabled == true))

- name: Allow all access to tcp port {{ prometheus_zookeeper_exporter_port }} (Prometheus ZooKeeper Exporter Port)
  ufw:
    rule: allow
    port: '{{ prometheus_zookeeper_exporter_port }}'
    proto: tcp
  when: ((prometheus_exporter_enabled is defined) and (prometheus_exporter_enabled != None) and (prometheus_exporter_enabled == true))

- name: Allow access to the remote JMX tcp ports
  block:
  - ufw:
      rule: allow
      port: '9998'
      proto: tcp

  - ufw:
      rule: allow
      port: '9999'
      proto: tcp

  when: ((prometheus_jmx_exporter_enabled is defined) and (prometheus_jmx_exporter_enabled != None) and (prometheus_jmx_exporter_enabled == true))


