---
# file: roles/kafka_zookeeper/tasks/ubuntu.yaml

- debug:
    msg: Applying the Ubuntu-specific ZooKeeper configuration

- name: Enable the firewall
  ufw:
    state: enabled
    policy: deny

- name: Allow all access to tcp port 2888 to other ZooKeeper hosts (Cluster1)
  ufw:
    rule: allow
    source: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
    port: '2888'
    proto: tcp
  loop: "{{ kafka_zookeeper_cluster1_actual_hosts }}"
  when: ((inventory_hostname in kafka_zookeeper_cluster1_actual_hosts) and (item != inventory_hostname))

- name: Allow all access to tcp port 2888 to other ZooKeeper hosts (Cluster2)
  ufw:
    rule: allow
    source: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
    port: '2888'
    proto: tcp
  loop: "{{ kafka_zookeeper_cluster2_actual_hosts }}"
  when: ((inventory_hostname in kafka_zookeeper_cluster2_actual_hosts) and (item != inventory_hostname))

- name: Allow all access to tcp port 3888 to other ZooKeeper hosts (Cluster1)
  ufw:
    rule: allow
    source: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
    port: '3888'
    proto: tcp
  loop: "{{ kafka_zookeeper_cluster1_actual_hosts }}"
  when: ((inventory_hostname in kafka_zookeeper_cluster1_actual_hosts) and (item != inventory_hostname))

- name: Allow all access to tcp port 3888 to other ZooKeeper hosts (Cluster2)
  ufw:
    rule: allow
    source: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
    port: '3888'
    proto: tcp
  loop: "{{ kafka_zookeeper_cluster2_actual_hosts }}"
  when: ((inventory_hostname in kafka_zookeeper_cluster2_actual_hosts) and (item != inventory_hostname))

- name: Allow all access to tcp port {{ zookeeper_secure_client_port}} (Secure ZooKeeper Client Port) for Kafka Server hosts (Cluster1)
  ufw:
    rule: allow
    source: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
    port: '{{ zookeeper_secure_client_port }}'
    proto: tcp
  loop: "{{ kafka_server_cluster1_actual_hosts | default([]) }}"
  when: (inventory_hostname in kafka_zookeeper_cluster1_actual_hosts)

- name: Allow all access to tcp port {{ zookeeper_secure_client_port}} (Secure ZooKeeper Client Port) for Kafka Server hosts (Cluster2)
  ufw:
    rule: allow
    source: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
    port: '{{ zookeeper_secure_client_port }}'
    proto: tcp
  loop: "{{ kafka_server_cluster2_actual_hosts | default([]) }}"
  when: (inventory_hostname in kafka_zookeeper_cluster2_actual_hosts)

