---
#file: roles/confluent_zookeeper/vars/main.yaml

zookeeper_etc_directory: /etc/zookeeper
zookeeper_log_directory: /var/log/zookeeper
zookeeper_data_directory: /data/zookeeper/data
zookeeper_data_log_directory: /data/zookeeper/data-log

zookeeper_user: cp-zookeeper
zookeeper_user_id: 316
zookeeper_group: cp-zookeeper
zookeeper_group_id: 316

zookeeper_client_port: 2181
zookeeper_secure_client_port: 2182
zookeeper_cluster_ports: "2888:3888"

zookeeper_enable_admin_server: 'false'
zookeeper_admin_server_port: 8080

zookeeper_max_client_connections: 60

## Rolling file appender setttings
zookeeper_rolling_log_file_max_size: 10MB
zookeeper_max_rolling_log_file_count: 10

zookeeper_tick_time: 2000

zookeeper_init_limit: 5

zookeeper_sync_limit: 2

zookeeper_autopurge_purge_interval: 1
zookeeper_autopurge_snap_retain_count: 10


zookeeper_kafka_user_username: kafka

zookeeper_admin_user_username: admin

zookeeper_enable_remote_jmx: false

# JMX EXPORTER REQUIRED FOR ZOOKEEPER <3.6
prometheus_jmx_exporter_enabled: true
prometheus_jmx_exporter_version: 0.13.0
prometheus_zookeeper_jmx_exporter_port: 9150

# REQUIRES ZOOKEEPER >=3.6 (https://zookeeper.apache.org/doc/current/zookeeperMonitor.html)
prometheus_exporter_enabled: false
prometheus_zookeeper_exporter_port: 9151



