---
# file: roles/awx/tasks/redhat.yaml

- debug:
    msg: Applying the RedHat-specific common configuration

- name: Allow access to tcp port 53 and udp port 53 (DNS)
  block:
  - firewalld:
      port: '53/tcp'
      permanent: yes
      state: enabled
      immediate: yes
  - firewalld:
      port: '53/udp'
      permanent: yes
      state: enabled
      immediate: yes

- name: Install the python3 package
  yum:
    name: python3
    state: present
  when: ansible_distribution_major_version == '7'

- pip:
    name: selinux
    executable: pip-3

- pip:
    name: docker
    executable: pip-3

- pip:
    name: docker-compose
    executable: pip-3

- name: Install the dnsmasq package
  yum:
    name: dnsmasq
    state: present

- systemd:
    name: dnsmasq
    state: started
    enabled: yes

- name: Install the jq package
  yum:
    name: jq
    state: present

- name: Check if docker has been configured to use dnsmasq for DNS
  shell:
    cmd: jq -r '.dns[0]' /etc/docker/daemon.json
  register: docker_using_dnsmasq_check_result

- name: Update docker to use dnsmasq for DNS
  block:
  - shell:
      cmd: echo "$( jq '.dns = ["{{ (ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]))) }}"]' /etc/docker/daemon.json )" > /etc/docker/daemon.json

  - systemd:
      name: docker
      state: restarted
      enabled: yes
      daemon_reload: yes

  - systemd:
      name: docker
      state: started
      enabled: yes
  when: docker_using_dnsmasq_check_result.stdout != ((ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]))))

- name: Install the git package
  yum:
    name: git
    state: present

- name: Install the ansible package
  yum:
    name: ansible
    state: present

- name: Clone the AWX git repo
  git:
    repo: https://github.com/ansible/awx.git
    dest: /var/tmp/ansible/awx
    update: no


