---
# file: roles/burrow/tasks/assert.yaml

- name: Check the burrow variable is defined correctly
  assert:
    that:
    - burrow is defined
    quiet: yes

- name: Check the burrow.clusters variable is defined correctly
  assert:
    that:
    - burrow.clusters is defined
    - (burrow.clusters | length) >  0
    quiet: yes

