---
# file: roles/burrow/tasks/centos.yaml

- debug:
    msg: Applying the CentOS-specific Burrow configuration

- name: Allow all hosts access to tcp port {{ burrow_config.http_port }}
  firewalld:
    port: '{{ burrow_config.http_port }}/tcp'
    permanent: yes
    state: enabled
    immediate: yes
