---
# file: roles/burrow/tasks/ubuntu.yaml

- ansible.builtin.debug:
    msg: Applying the Ubuntu-specific Burrow configuration

- name: Allow all hosts access to tcp port {{ burrow_config.http_port }}
  community.general.ufw:
    rule: allow
    port: '{{ burrow_config.http_port }}'
    proto: tcp
