---
#file: roles/confluent_kafka_mirrormaker/tasks/main.yaml

- set_fact:
    confluent_kafka_mirrormaker_dc1_actual_hosts: "{{ confluent_kafka_mirrormaker_dc1_possible_hosts | intersect(groups['confluent_kafka_mirrormaker']) }}"
- set_fact:
    confluent_kafka_mirrormaker_dc2_actual_hosts: "{{ confluent_kafka_mirrormaker_dc2_possible_hosts | intersect(groups['confluent_kafka_mirrormaker']) }}"

- set_fact:
    confluent_kafka_server_dc1_actual_hosts: "{{ confluent_kafka_server_dc1_possible_hosts | intersect(groups['confluent_kafka_server']) }}"
- set_fact:
    confluent_kafka_server_dc2_actual_hosts: "{{ confluent_kafka_server_dc2_possible_hosts | intersect(groups['confluent_kafka_server']) }}"

- debug:
    msg: 'Confluent Kafka MirrorMaker DC1 hosts: {{ confluent_kafka_mirrormaker_dc1_actual_hosts  }}'
- debug:
    msg: 'Confluent Kafka MirrorMaker DC2 hosts: {{ confluent_kafka_mirrormaker_dc2_actual_hosts  }}'
- debug:
    msg: 'Confluent Kafka Server DC1 hosts: {{ confluent_kafka_server_dc1_actual_hosts  }}'
- debug:
    msg: 'Confluent Kafka Server DC2 hosts: {{ confluent_kafka_server_dc2_actual_hosts  }}'

- debug:
    msg: "Confluent Kafka MirrorMaker host {{ inventory_hostname }} is in DC1"
  when: (inventory_hostname in confluent_kafka_mirrormaker_dc1_actual_hosts)
- debug:
    msg: "Confluent Kafka MirrorMaker host {{ inventory_hostname }} is in DC2"
  when: (inventory_hostname in confluent_kafka_mirrormaker_dc2_actual_hosts)


#   ____ ___  _   _ _____ _    _   _ _____ _   _ _____   _  __    _    _____ _  __    _      __  __ ___ ____  ____   ___  ____    __  __    _    _  _______ ____
#  / ___/ _ \| \ | |  ___| |  | | | | ____| \ | |_   _| | |/ /   / \  |  ___| |/ /   / \    |  \/  |_ _|  _ \|  _ \ / _ \|  _ \  |  \/  |  / \  | |/ / ____|  _ \
# | |  | | | |  \| | |_  | |  | | | |  _| |  \| | | |   | ' /   / _ \ | |_  | ' /   / _ \   | |\/| || || |_) | |_) | | | | |_) | | |\/| | / _ \ | ' /|  _| | |_) |
# | |__| |_| | |\  |  _| | |__| |_| | |___| |\  | | |   | . \  / ___ \|  _| | . \  / ___ \  | |  | || ||  _ <|  _ <| |_| |  _ <  | |  | |/ ___ \| . \| |___|  _ <
#  \____\___/|_| \_|_|   |_____\___/|_____|_| \_| |_|   |_|\_\/_/   \_\_|   |_|\_\/_/   \_\ |_|  |_|___|_| \_\_| \_\\___/|_| \_\ |_|  |_/_/   \_\_|\_\_____|_| \_\
#
- name: Add the kafka group
  group:
    name: kafka
    gid: '{{ kafka_group_id }}'
    state: present

- name: Add the kafka user
  user:
    name: kafka
    uid: '{{ kafka_user_id }}'
    group: kafka
    create_home: yes
    state: present

- name: Create the /var/tmp/ansible/kafka directory
  file:
    path: /var/tmp/ansible/kafka
    owner: root
    group: root
    mode: '0700'
    state: directory

- name: Create the {{ kafka_etc_directory }} directory
  file:
    path: '{{ kafka_etc_directory }}'
    owner: kafka
    group: kafka
    mode: '0550'
    state: directory

- name: Create the {{ kafka_etc_directory }}/conf directory
  file:
    path: '{{ kafka_etc_directory }}/conf'
    owner: kafka
    group: kafka
    mode: '0550'
    state: directory

- name: Setup the Kafka MirrorMaker keystore and Kafka CA truststore
  block:
  - name: Create the {{ kafka_etc_directory }}/pki directory
    file:
      path: '{{ kafka_etc_directory }}/pki'
      owner: kafka
      group: kafka
      mode: '0550'
      state: directory

  - name: Copy the Kafka CA certificate to the /var/tmp/ansible/kafka directory
    copy:
      src: pki/{{ confluent_cluster_name }}/ca.crt
      dest: /var/tmp/ansible/kafka/ca.crt
    register: kafka_ca_copy_result

  - name: Copy the Kafka MirrorMaker private key (confluent-{{ confluent_cluster_name }}-kafka-mirrormaker.key) to the /var/tmp/ansible/kafka directory
    copy:
      src: pki/{{ confluent_cluster_name }}/confluent-{{ confluent_cluster_name }}-kafka-mirrormaker.key
      dest: /var/tmp/ansible/kafka/confluent-{{ confluent_cluster_name }}-kafka-mirrormaker.key
    register: kafka_mirrormaker_private_key_copy_result

  - name: Copy the Kafka MirrorMaker certificate (confluent-{{ confluent_cluster_name }}-kafka-mirrormaker.crt) to the /var/tmp/ansible/kafka directory
    copy:
      src: pki/{{ confluent_cluster_name }}/confluent-{{ confluent_cluster_name }}-kafka-mirrormaker.crt
      dest: /var/tmp/ansible/kafka/confluent-{{ confluent_cluster_name }}-kafka-mirrormaker.crt
    register: kafka_mirrormaker_certificate_copy_result

  - name: Generate or retrieve the password for the Kafka MirrorMaker keystore
    set_fact:
      kafka_mirrormaker_keystore_password: "{{ lookup('password', 'credentials/confluent/{{ confluent_cluster_name }}/kafka-mirrormaker-keystore-password chars=ascii_letters,digits length=16') }}"

  - name: Generate or retrieve the password for the Kafka truststore
    set_fact:
      kafka_ca_truststore_password: "{{ lookup('password', 'credentials/confluent/{{ confluent_cluster_name }}/kafka-ca-truststore-password chars=ascii_letters,digits length=16') }}"

  - name: Generate the Kafka MirrorMaker keystore and Kafka CA truststore
    block:
    - name: Generate the Kafka MirrorMaker PKCS12 keystore
      openssl_pkcs12:
        action: export
        path: '{{ kafka_etc_directory }}/pki/mirrormaker.p12'
        friendly_name: 'confluent-{{ confluent_cluster_name }}-kafka-mirrormaker'
        privatekey_path: /var/tmp/ansible/kafka/confluent-{{ confluent_cluster_name }}-kafka-mirrormaker.key
        certificate_path: /var/tmp/ansible/kafka/confluent-{{ confluent_cluster_name }}-kafka-mirrormaker.crt
        passphrase: '{{ kafka_mirrormaker_keystore_password }}'
        owner: kafka
        group: kafka
        mode: '0440'
        state: present

    - name: Remove the Kafka CA PKCS12 truststore if it already exists
      file:
        path: '{{ kafka_etc_directory }}/pki/ca.p12'
        state: absent

    - name: Generate the Kafka CA PKCS12 truststore
      shell:
        cmd: keytool -importcert -noprompt -trustcacerts -alias "ca" -file /var/tmp/ansible/kafka/ca.crt -keystore '{{ kafka_etc_directory }}/pki/ca.p12' -storetype PKCS12 -storepass '{{ kafka_ca_truststore_password }}'

    - name: Set the permissions for the Kafka CA PKCS12 truststore
      file:
        path: '{{ kafka_etc_directory }}/pki/ca.p12'
        owner: kafka
        group: kafka
        mode: '0440'

    when: ((kafka_ca_copy_result.changed == True) or (kafka_mirrormaker_private_key_copy_result.changed == True) or (kafka_mirrormaker_certificate_copy_result.changed == True))

- name: Create the {{ kafka_log_directory }} directory
  file:
    path: '{{ kafka_log_directory }}'
    owner: kafka
    group: kafka
    mode: '0750'
    state: directory

# NOTE: This is the password Kafka MirrorMaker uses to connect to the Kafka cluster
- name: Generate or retrieve the password for the Kafka MirrorMaker user
  set_fact:
    kafka_mirrormaker_user_password: "{{ lookup('password', 'credentials/confluent/{{ confluent_cluster_name }}/kafka-mirrormaker-user-password chars=ascii_letters,digits length=16') }}"

- name: Create the Kafka MirrorMaker configuration file
  template:
    src: mirrormaker.properties.j2
    dest: '{{ kafka_etc_directory }}/conf/mirrormaker.properties'
    owner: kafka
    group: kafka
    mode: '0440'
  register: kafka_mirrormaker_configuration_template_result

#- name: Create the Kafka MirrorMaker JAAS configuration file
#  template:
#    src: mirrormaker-jaas.conf.j2
#    dest: '{{ kafka_etc_directory }}/conf/mirrormaker-jaas.conf'
#    owner: kafka
#    group: kafka
#    mode: '0440'
#  register: kafka_mirrormaker_jaas_configuration_template_result

- name: Configure the Kafka MirrorMaker service
  template:
    src: mirrormaker.service.j2
    dest: /lib/systemd/system/mirrormaker.service
  register: kafka_mirrormaker_service_file_template_result

- name: Restart the Kafka MirrorMaker service if required
  systemd:
    name: mirrormaker.service
    state: restarted
    enabled: yes
    daemon_reload: yes
  when: ((kafka_ca_copy_result.changed == True) or (kafka_mirrormaker_private_key_copy_result.changed == True) or (kafka_mirrormaker_certificate_copy_result.changed == True) or (kafka_mirrormaker_configuration_template_result.changed == True) or (kafka_server_service_file_template_result.changed == True))
