---
# file: roles/confluent_kafka_mirrormaker/tasks/ubuntu.yaml

- debug:
    msg: Applying the Ubuntu-specific Confluent Kafka MirrorMaker configuration

- name: Enable the firewall
  ufw:
    state: enabled
    policy: deny

- name: Allow all hosts access to tcp port {{ confluent_config.kafka_mirrormaker.prometheus_jmx_exporter.port }} (Prometheus JMX Exporter Port)
  ufw:
    rule: allow
    port: '{{ confluent_config.kafka_mirrormaker.prometheus_jmx_exporter.port }}'
    proto: tcp
  when: ((confluent_config.kafka_mirrormaker.prometheus_jmx_exporter.enabled is defined) and (confluent_config.kafka_mirrormaker.prometheus_jmx_exporter.enabled != None) and (confluent_config.kafka_mirrormaker.prometheus_jmx_exporter.enabled == true))
