---
# file: roles/postgresql/defaults/main.yaml

postgresql_defaults:

  version: '13'

  redhat_package_version: '13.3'

  ubuntu_package_version: '13.3-1.pgdg20.04+1'

  # Specifying a data_directory_root value will result in the default database being
  # initialized at this location (RedHat) or moved to this location (Ubuntu)
  #data_directory_root: /data

  user: postgres
  group: postgres

  # Ubuntu only. Used to generate the locales used by PostgreSQL databases.
  locales:
  - 'en_US.UTF-8'

  # Global configuration options that will be set in postgresql.conf.
  global_config_options:
  - option: unix_socket_directories
    value: '/var/run/postgresql'

  # NOTE: This list needs to match the unix_socket_directories global configuration option
  unix_socket_directories:
  - /var/run/postgresql

  # Host based authentication (hba) entries to be added to the pg_hba.conf. This
  # variable's defaults reflect the defaults that come with a fresh installation.
  default_hba_entries:
  - {type: local, database: all, user: postgres, auth_method: peer}
  - {type: local, database: all, user: all, auth_method: peer}
  - {type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: 'scram-sha-256'}
  - {type: host, database: all, user: all, address: '::1/128', auth_method: 'scram-sha-256'}

#  clusters:
#  - name: example
#    servers:
#    - hostname: example.hostname
#      config_options:
#        listen_addresses: 'localhost'
#      hba_entries:
#      - {type: local, database: all, user: postgres, auth_method: peer}
#      - {type: local, database: all, user: all, auth_method: peer}
#      - {type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: 'scram-sha-256'}
#      - {type: host, database: all, user: all, address: '::1/128', auth_method: 'scram-sha-256'}
#    ## Databases that should exist
#    databases: []
#    - name: exampledb # required; the rest are optional
#      lc_collate: # defaults to 'en_US.UTF-8'
#      lc_ctype: # defaults to 'en_US.UTF-8'
#      encoding: # defaults to 'UTF-8'
#      template: # defaults to 'template0'
#      owner: # defaults to postgresql_user
#      state: # defaults to 'present'
#    # Users that should exist
#    # See: https://docs.ansible.com/ansible/latest/collections/community/postgresql/postgresql_user_module.html#ansible-collections-community-postgresql-postgresql-user-module
#    users: []
#    - name: jdoe #required; the rest are optional
#      password: # defaults to not set
#      priv: # defaults to not set
#      role_attr_flags: # defaults to not set
#      db: # defaults to not set

  # Whether to output user data when managing users.
  users_no_log: true

postgresql_config: "{{ postgresql_defaults | combine(postgresql | default({}), recursive=True) }}"



