---
# file: roles/prometheus_alert_manager/tasks/ubuntu.yaml

- ansible.builtin.debug:
    msg: Applying the Ubuntu-specific Prometheus Alert Manager configuration

- name: Allow all hosts access to tcp port 9093
  community.general.ufw:
    rule: allow
    port: '9093'
    proto: tcp

- name: Allow Prometheus Alert Manager hosts access to tcp port 9094
  community.general.ufw:
    rule: allow
    from_ip: "{{ (hostvars[item].ansible_default_ipv4.address|default(hostvars[item].ansible_all_ipv4_addresses[0])) }}"
    port: '9094'
    proto: tcp
  loop: "{{ groups['prometheus_alert_manager'] }}"

- name: Allow Prometheus Alert Manager hosts access to udp port 9094
  community.general.ufw:
    rule: allow
    from_ip: "{{ (hostvars[item].ansible_default_ipv4.address|default(hostvars[item].ansible_all_ipv4_addresses[0])) }}"
    port: '9094'
    proto: udp
  loop: "{{ groups['prometheus_alert_manager'] }}"
