#
# VARIABLES
#
# The following variables influence the deployment and configuration of etcd:
#   etcd_cluster_name - The name of the etcd cluster, which influences the location and
#                       names of the private keys and certificates for the cluster.
#
# The following variables influence the deployment and configuration of Kubernetes:
#   k8s_cluster_name  - The name of the etcd cluster, which influences the location and
#                       names of the private keys and certificates for the cluster.
#   k8s_etcd_topology - The etcd topology for the Kubernetes cluster, which can be stacked
#                       or external, for an external etcd cluster.
#
#
# PROFILES
#
# Profiles are used to group a related set of hosts that need to be provisioned together,
# e.g., the hosts that form part of an etcd cluster, the hosts that form part of a
# Kubernetes cluster, the hosts that suport a set of integrated development tools, etc.
#

variables:
# ----------------------------------------------------------------------------------------
# Etcd Configuration
# ----------------------------------------------------------------------------------------
- name: etcd_cluster_name
  values:
  - local

# ----------------------------------------------------------------------------------------
# Kubernetes Configuration
# ----------------------------------------------------------------------------------------
- name: k8s_etcd_topology
  values:
  - stacked
- name: k8s_cluster_name
  values:
  - local
- name: k8s_cluster_domain
  values:
  - local.internal
- name: k8s_control_plane_endpoint
  values:
  - k8s-local-api.local
#  - name: k8s_kube_state_metrics_endpoint
#    values:
#      - k8s-local-metrics.local
- name: k8s_api_server_cert_sans
  values:
  - localhost
  - 127.0.0.1
  - k8s-local-api.local
- name: k8s_service_subnet
  values:
  - 10.254.0.0/16
- name: k8s_pod_subnet
  values:
  - 10.255.0.0/16
- name: k8s_cni_provider
  values:
  - weave
- name: longhorn_enabled
  values:
  - true
- name: topolvm_enabled
  values:
  - true
- name: topolvm_volume_group
  values:
  - system

# ----------------------------------------------------------------------------------------
# Kubernetes Extensions Configuration
# ----------------------------------------------------------------------------------------
- name: bitnami_labs_sealed_secrets_enabled
  values:
  - true

# ----------------------------------------------------------------------------------------
# Kubernetes Operator Configuration
# ----------------------------------------------------------------------------------------
- name: operator_lifecycle_manager_enabled
  values:
  - false
- name: jaeger_operator_enabled
  values:
  - false
- name: postgres_operator_enabled
  values:
  - false

# ----------------------------------------------------------------------------------------
# Istio Configuration
# ----------------------------------------------------------------------------------------
- name: istio_enabled
  values:
  - true
- name: istio_grafana_enabled
  values:
  - false
- name: istio_kiali_enabled
  values:
  - true
- name: istio_prometheus_enabled
  values:
  - false
- name: istio_tracing_enabled
  values:
  - false

# ----------------------------------------------------------------------------------------
# External Monitoring Configuration
# ----------------------------------------------------------------------------------------
- name: prometheus_data_directory
  values:
  - /var/lib/prometheus

# ----------------------------------------------------------------------------------------
# Monitoring Configuration
#
# Where elasticsearch_cluster_type is one of single, minimal or full.
#
# ----------------------------------------------------------------------------------------
- name: monitoring_enabled
  values:
  - true
- name: monitoring_security_enabled
  values:
  - true
- name: monitoring_elasticsearch_cluster_type
  values:
  - standalone
- name: monitoring_elasticsearch_enabled
  values:
  - true
- name: monitoring_elasticsearch_helm_chart_version
  values:
  - 7.6.1
- name: monitoring_elasticsearch_storage_class_name
  values:
  - default-local-storage
- name: monitoring_grafana_enabled
  values:
  - true
- name: monitoring_grafana_helm_chart_version
  values:
  - 5.0.7
- name: monitoring_jaeger_enabled
  values:
  - false
- name: monitoring_kibana_enabled
  values:
  - true
- name: monitoring_kibana_helm_chart_version
  values:
  - 7.6.1
- name: monitoring_prometheus_enabled
  values:
  - true
- name: monitoring_prometheus_helm_chart_version
  values:
  - 11.0.2
- name: monitoring_prometheus_storage_class_name
  values:
  - default-local-storage


profiles:
- name: devops
  hosts:
  - devops.local

- name: etcd_cluster
  hosts:
  - etcd-local-01.local
  - etcd-local-02.local
  - etcd-local-03.local

- name: k8s_minimal
  hosts:
  - k8s-local-m-01.local
  - k8s-local-w-01.local

- name: k8s_only_masters
  hosts:
  - k8s-local-api.local
  - k8s-local-m-01.local
  - k8s-local-m-02.local
  - k8s-local-m-03.local

- name: k8s_full
  hosts:
  - k8s-local-api.local
  - k8s-local-m-01.local
  - k8s-local-m-02.local
  - k8s-local-m-03.local
  - k8s-local-w-01.local
  - k8s-local-w-02.local
  - k8s-local-w-03.local

- name: test-ubuntu1804
  hosts:
  - test-ubuntu1804.local

- name: test-centos77
  hosts:
  - test-centos77.local

- name: test-centos77
  hosts:
  - test-centos77.local

- name: test-centos80
  hosts:
  - test-centos80.local

hosts:
- name:                     etcd-local-01.local
  type:                     ubuntu1804
  ansible_playbook:         ansible/devops.yaml
  ansible_groups:           monitored,etcd
  cpus:                     1
  memory:                   512
  hostname:                 etcd-local-01
  fqdn:                     etcd-local-01.local
  ip:                       192.168.184.41/24
  network:                  192.168.184.0/24
  gateway:                  192.168.184.2
  dns_server:               192.168.184.2
  dns_search:               local

- name:                     etcd-local-02.local
  type:                     ubuntu1804
  ansible_playbook:         ansible/devops.yaml
  ansible_groups:           monitored,etcd
  cpus:                     1
  memory:                   512
  hostname:                 etcd-local-02
  fqdn:                     etcd-local-02.local
  ip:                       192.168.184.42/24
  network:                  192.168.184.0/24
  gateway:                  192.168.184.2
  dns_server:               192.168.184.2
  dns_search:               local

- name:                     etcd-local-03.local
  type:                     ubuntu1804
  ansible_playbook:         ansible/devops.yaml
  ansible_groups:           monitored,etcd
  cpus:                     1
  memory:                   512
  hostname:                 etcd-local-03
  fqdn:                     etcd-local-03.local
  ip:                       192.168.184.43/24
  network:                  192.168.184.0/24
  gateway:                  192.168.184.2
  dns_server:               192.168.184.2
  dns_search:               local

- name:                     devops.local
  type:                     ubuntu1804
  ansible_playbook:         ansible/devops.yaml
  ansible_groups:           k8s_master,k8s_components
  cpus:                     3
  memory:                   6144
  hostname:                 devops
  fqdn:                     devops.local
  ip:                       192.168.184.60/24
  network:                  192.168.184.0/24
  gateway:                  192.168.184.2
  dns_server:               192.168.184.2
  dns_search:               local

- name:                     k8s-local-api.local
  type:                     ubuntu1804
  ansible_playbook:         ansible/devops.yaml
  ansible_groups:           k8s_load_balancer
  cpus:                     1
  memory:                   512
  hostname:                 k8s-local-api
  fqdn:                     k8s-local-api.local
  ip:                       192.168.184.50/24
  network:                  192.168.184.0/24
  gateway:                  192.168.184.2
  dns_server:               192.168.184.2
  dns_search:               local

- name:                     k8s-local-m-01.local
  type:                     ubuntu1804
  ansible_playbook:         ansible/devops.yaml
  ansible_groups:           k8s_master,k8s_components
  cpus:                     2
  memory:                   1536
  hostname:                 k8s-local-m-01
  fqdn:                     k8s-local-m-01.local
  ip:                       192.168.184.51/24
  network:                  192.168.184.0/24
  gateway:                  192.168.184.2
  dns_server:               192.168.184.2
  dns_search:               local

- name:                     k8s-local-m-02.local
  type:                     ubuntu1804
  ansible_playbook:         ansible/devops.yaml
  ansible_groups:           k8s_master,k8s_components
  cpus:                     2
  memory:                   1536
  hostname:                 k8s-local-m-02
  fqdn:                     k8s-local-m-02.local
  ip:                       192.168.184.52/24
  network:                  192.168.184.0/24
  gateway:                  192.168.184.2
  dns_server:               192.168.184.2
  dns_search:               local

- name:                     k8s-local-m-03.local
  type:                     ubuntu1804
  ansible_playbook:         ansible/devops.yaml
  ansible_groups:           k8s_master,k8s_components
  cpus:                     2
  memory:                   1536
  hostname:                 k8s-local-m-03
  fqdn:                     k8s-local-m-03.local
  ip:                       192.168.184.53/24
  network:                  192.168.184.0/24
  gateway:                  192.168.184.2
  dns_server:               192.168.184.2
  dns_search:               local

- name:                     k8s-local-w-01.local
  type:                     ubuntu1804
  ansible_playbook:         ansible/devops.yaml
  ansible_groups:           k8s_worker,k8s_components
  cpus:                     2
  memory:                   3072
  hostname:                 k8s-local-w-01
  fqdn:                     k8s-local-w-01.local
  ip:                       192.168.184.54/24
  network:                  192.168.184.0/24
  gateway:                  192.168.184.2
  dns_server:               192.168.184.2
  dns_search:               local

- name:                     k8s-local-w-02.local
  type:                     ubuntu1804
  ansible_playbook:         ansible/devops.yaml
  ansible_groups:           k8s_worker,k8s_components
  cpus:                     2
  memory:                   3072
  hostname:                 k8s-local-w-02
  fqdn:                     k8s-local-w-02.local
  ip:                       192.168.184.55/24
  network:                  192.168.184.0/24
  gateway:                  192.168.184.2
  dns_server:               192.168.184.2
  dns_search:               local

- name:                     k8s-local-w-03.local
  type:                     ubuntu1804
  ansible_playbook:         ansible/devops.yaml
  ansible_groups:           k8s_worker,k8s_components
  cpus:                     2
  memory:                   3072
  hostname:                 k8s-local-w-03
  fqdn:                     k8s-local-w-03.local
  ip:                       192.168.184.56/24
  network:                  192.168.184.0/24
  gateway:                  192.168.184.2
  dns_server:               192.168.184.2
  dns_search:               local

- name:                     monitor.local
  type:                     ubuntu1804
  ansible_playbook:         ansible/devops.yaml
  ansible_groups:           monitored,prometheus,grafana
  cpus:                     2
  memory:                   1024
  hostname:                 monitor
  fqdn:                     monitor.local
  ip:                       192.168.184.30/24
  network:                  192.168.184.0/24
  gateway:                  192.168.184.2
  dns_server:               192.168.184.2
  dns_search:               local

- name:                     test-ubuntu1804.local
  type:                     ubuntu1804
  ansible_playbook:         ansible/devops.yaml
  ansible_groups:           monitored
  cpus:                     2
  memory:                   1024
  hostname:                 test-ubuntu1804
  fqdn:                     test-ubuntu1804.local
  ip:                       192.168.184.49/24
  network:                  192.168.184.0/24
  gateway:                  192.168.184.2
  dns_server:               192.168.184.2
  dns_search:               local
  data_disk:                16107

- name:                     test-centos77.local
  type:                     centos77
  ansible_playbook:         ansible/devops.yaml
  ansible_groups:           monitored
  cpus:                     2
  memory:                   1024
  hostname:                 test-centos77
  fqdn:                     test-centos77.local
  ip:                       192.168.184.49/24
  network:                  192.168.184.0/24
  gateway:                  192.168.184.2
  dns_server:               192.168.184.2
  dns_search:               local
  data_disk:                16107

- name:                     test-centos80.local
  type:                     centos80
  ansible_playbook:         ansible/devops.yaml
  ansible_groups:           monitored
  cpus:                     2
  memory:                   1024
  hostname:                 test-centos80
  fqdn:                     test-centos80.local
  ip:                       192.168.184.49/24
  network:                  192.168.184.0/24
  gateway:                  192.168.184.2
  dns_server:               192.168.184.2
  dns_search:               local
  data_disk:                16107



