---
# file: roles/confluent_common/tasks/assert.yaml

#- name: Check the ansible_hostname variable is defined and matches the inventory_hostname_short variable
#  assert:
#    that:
#    - ansible_hostname is defined
#    - ansible_hostname is string
#    - ansible_hostname != ''
#    - ansible_hostname == inventory_hostname_short
#    quiet: yes
#
#- name: Check the ansible_fqdn variable is defined and matches the inventory_hostname variable
#- name: Check the etcd variable is defined correctly
#  assert:
#    that:
#    - ansible_fqdn is defined
#    - ansible_fqdn is string
#    - ansible_fqdn != ''
#    - ansible_fqdn == inventory_hostname
#    - etcd is defined
#    quiet: yes

- name: Check the confluent variable is defined correctly
  assert:
    that:
    - confluent is defined
    quiet: yes

- name: Check the confluent.clusters variable is defined correctly
  assert:
    that:
    - confluent.clusters is defined
    - (confluent.clusters | length) >  0
    quiet: yes

