---
# file: roles/confluent_common/tasks/centos.yaml

- debug:
    msg: Applying the CentOS-specific Kafka common configuration

- name: Install the java-11-openjdk package
  yum:
    name: java-11-openjdk
    state: latest