---
# file: roles/confluent_common/tasks/main.yaml

- ansible.builtin.import_tasks: assert.yaml
  run_once: yes
  delegate_to: localhost

- name: Create the /var/tmp/ansible/confluent directory
  ansible.builtin.file:
    path: /var/tmp/ansible/confluent
    owner: 'root'
    group: 'root'
    mode: '0700'
    state: directory


#   ___  ____       ____  ____  _____ ____ ___ _____ ___ ____
#  / _ \/ ___|     / ___||  _ \| ____/ ___|_ _|  ___|_ _/ ___|
# | | | \___ \ ____\___ \| |_) |  _|| |    | || |_   | | |
# | |_| |___) |_____|__) |  __/| |__| |___ | ||  _|  | | |___
#  \___/|____/     |____/|_|   |_____\____|___|_|   |___\____|
#
- include_tasks: ubuntu.yaml
  when: ansible_distribution == 'Ubuntu'
  tags:
  - unbound

- include_tasks: redhat.yaml
  when: ansible_os_family == 'RedHat'
  tags:
  - unbound


#   ____ ___  _   _ _____ _    _   _ _____ _   _ _____    ____ ___  __  __ __  __  ___  _   _
#  / ___/ _ \| \ | |  ___| |  | | | | ____| \ | |_   _|  / ___/ _ \|  \/  |  \/  |/ _ \| \ | |
# | |  | | | |  \| | |_  | |  | | | |  _| |  \| | | |   | |  | | | | |\/| | |\/| | | | |  \| |
# | |__| |_| | |\  |  _| | |__| |_| | |___| |\  | | |   | |__| |_| | |  | | |  | | |_| | |\  |
#  \____\___/|_| \_|_|   |_____\___/|_____|_| \_| |_|    \____\___/|_|  |_|_|  |_|\___/|_| \_|
#
- name: Install Confluent
  block:
  - ansible.builtin.debug:
      msg: Check whether the Confluent {{ confluent_config.package_version }} package has been installed

  - ansible.builtin.stat:
      path: /opt/confluent
    register: confluent_installed_stat_result

  - block:
    - ansible.builtin.debug:
        msg: Install the Confluent {{ confluent_config.package_version }} package

    - name: Check whether the Confluent {{ confluent_config.package_version }} package has been downloaded
      become: no
      local_action: ansible.builtin.stat path='{{ packages_root }}/{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}/confluent-community-{{ confluent_config.package_version }}.tar.gz'
      register: confluent_package_stat_result

    - name: Download the Confluent {{ confluent_config.package_version }} package
      become: no
      local_action: ansible.builtin.get_url url='https://packages.confluent.io/archive/{{ confluent_config.major_version }}/confluent-community-{{ confluent_config.package_version }}.tar.gz' dest='{{ packages_root }}/{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}/confluent-community-{{ confluent_config.package_version }}.tar.gz'
      when: (confluent_package_stat_result.stat.exists == False)

    - name: Extract the Confluent {{ confluent_config.package_version }} package
      ansible.builtin.unarchive:
        src: '{{ packages_root }}/{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}/confluent-community-{{ confluent_config.package_version }}.tar.gz'
        dest: /opt
        owner: 'root'
        group: 'root'

    - name: Create the symbolic link to the Confluent {{ confluent_config.package_version }} package
      ansible.builtin.file:
        src: /opt/confluent-{{ confluent_config.package_version }}
        dest: /opt/confluent
        owner: 'root'
        group: 'root'
        mode: '0755'
        state: link

    when: ((confluent_installed_stat_result.stat.exists == False) or (confluent_installed_stat_result.stat.lnk_target != ('/opt/confluent-' + confluent_config.package_version)))

- name: Create the {{ confluent_config.data_directory }} directory
  ansible.builtin.file:
    path: '{{ confluent_config.data_directory }}'
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: directory
  when: ((confluent_config.data_directory is defined) and (confluent_config.data_directory != None))

#  ____  ____   ___  __  __ _____ _____ _   _ _____ _   _ ____        _ __  ____  __  _______  ______   ___  ____ _____ _____ ____
# |  _ \|  _ \ / _ \|  \/  | ____|_   _| | | | ____| | | / ___|      | |  \/  \ \/ / | ____\ \/ /  _ \ / _ \|  _ \_   _| ____|  _ \
# | |_) | |_) | | | | |\/| |  _|   | | | |_| |  _| | | | \___ \   _  | | |\/| |\  /  |  _|  \  /| |_) | | | | |_) || | |  _| | |_) |
# |  __/|  _ <| |_| | |  | | |___  | | |  _  | |___| |_| |___) | | |_| | |  | |/  \  | |___ /  \|  __/| |_| |  _ < | | | |___|  _ <
# |_|   |_| \_\\___/|_|  |_|_____| |_| |_| |_|_____|\___/|____/   \___/|_|  |_/_/\_\ |_____/_/\_\_|    \___/|_| \_\|_| |_____|_| \_\
#
- name: Install the Prometheus JMX Exporter library
  block:
  - name: Create the /opt/prometheus/lib directory
    ansible.builtin.file:
      path: /opt/prometheus/lib
      owner: 'root'
      group: 'root'
      mode: '0755'
      state: directory

  - ansible.builtin.debug:
      msg: Check whether the Prometheus JMX Exporter {{ prometheus_jmx_exporter.package_version }} library has been installed

  - ansible.builtin.stat:
      path: /opt/prometheus/lib/jmx_prometheus_javaagent-{{ prometheus_jmx_exporter.package_version }}.jar
    register: prometheus_jmx_exporter_installed_stat_result

  - block:
    - ansible.builtin.debug:
        msg: Install the Prometheus JMX Exporter {{ prometheus_jmx_exporter.package_version }} library

    - name: Check whether the Prometheus JMX Exporter {{ prometheus_jmx_exporter.package_version }} has been downloaded
      become: no
      local_action: ansible.builtin.stat path='{{ packages_root }}/{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}/jmx_prometheus_javaagent-{{ prometheus_jmx_exporter.package_version }}.jar'
      register: prometheus_jmx_exporter_package_stat_result

    - name: Download the Prometheus JMX Exporter {{ prometheus_jmx_exporter.package_version }} library
      become: no
      local_action: ansible.builtin.get_url url='https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/{{ prometheus_jmx_exporter.package_version }}/jmx_prometheus_javaagent-{{ prometheus_jmx_exporter.package_version }}.jar' dest='{{ packages_root }}/{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}/jmx_prometheus_javaagent-{{ prometheus_jmx_exporter.package_version }}.jar' checksum={{ prometheus_jmx_exporter.package_checksum }}
      when: (prometheus_jmx_exporter_package_stat_result.stat.exists == False)

    - name: Copy the Prometheus JMX Exporter {{ prometheus_jmx_exporter.package_version }} library
      ansible.builtin.copy:
        src: '{{ packages_root }}/{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}/jmx_prometheus_javaagent-{{ prometheus_jmx_exporter.package_version }}.jar'
        dest: /opt/prometheus/lib/jmx_prometheus_javaagent-{{ prometheus_jmx_exporter.package_version }}.jar
        owner: 'root'
        group: 'root'
        mode: '0644'

    when: (prometheus_jmx_exporter_installed_stat_result.stat.exists == False)

  - ansible.builtin.stat:
      path: /opt/prometheus/lib/jmx_prometheus_javaagent.jar
    register: prometheus_jmx_exporter_link_stat_result

  - name: Create the symbolic link to the Prometheus JMX Exporter {{ prometheus_jmx_exporter.package_version }} library
    ansible.builtin.file:
      src: /opt/prometheus/lib/jmx_prometheus_javaagent-{{ prometheus_jmx_exporter.package_version }}.jar
      dest: /opt/prometheus/lib/jmx_prometheus_javaagent.jar
      owner: 'root'
      group: 'root'
      mode: '0644'
      state: link

  when: ((prometheus_jmx_exporter.enabled is defined) and (prometheus_jmx_exporter.enabled != None) and (prometheus_jmx_exporter.enabled == true))
