---
# file: roles/docker/defaults/main.yaml

docker_defaults:
  centos7:
    containerd:
      package: containerd.io-1.3.7-3.1.el7.x86_64.rpm
      package_version: 1.3.7
    docker_ce:
      package: docker-ce-19.03.9-3.el7.x86_64.rpm
      package_version: 19.03.9
    docker_ce_cli:
      package: docker-ce-cli-19.03.9-3.el7.x86_64.rpm
      package_version: 19.03.9

  centos8:
    containerd:
      package: containerd.io-1.3.7-3.1.el8.x86_64.rpm
      package_version: 1.3.7
    docker_ce:
      package: docker-ce-19.03.13-3.el8.x86_64.rpm
      package_version: 19.03.13
    docker_ce_cli:
      package: docker-ce-cli-19.03.13-3.el8.x86_64.rpm
      package_version: 19.03.13

  ubuntu:
    docker_ce:
      package_version: 5:19.03.6~3-0~ubuntu-bionic

docker_config: "{{ docker_defaults | combine(docker | default({}), recursive=True) }}"


