---
# file: roles/docker/defaults/main.yaml

docker_defaults:
  redhat7:
    containerd:
      package: containerd.io-1.4.4-3.1.el7.x86_64.rpm
      package_version: '1.4.4'
    docker_ce:
      package: docker-ce-20.10.6-3.el7.x86_64.rpm
      package_version: '20.10.6'
    docker_ce_cli:
      package: docker-ce-cli-20.10.6-3.el7.x86_64.rpm
      package_version: '20.10.6'
    docker_ce_rootless_extras:
      package: docker-ce-rootless-extras-20.10.6-3.el7.x86_64.rpm
      package_version: '20.10.6'
    docker_scan_plugin:
      package: docker-scan-plugin-0.7.0-3.el7.x86_64.rpm
      package_version: '0.7.0'

  redhat8:
    containerd:
      package: containerd.io-1.4.4-3.1.el8.x86_64.rpm
      package_version: '1.4.4'
    docker_ce:
      package: docker-ce-20.10.6-3.el8.x86_64.rpm
      package_version: '20.10.6'
    docker_ce_cli:
      package: docker-ce-cli-20.10.6-3.el8.x86_64.rpm
      package_version: '20.10.6'
    docker_ce_rootless_extras:
      package: docker-ce-rootless-extras-20.10.6-3.el8.x86_64.rpm
      package_version: '20.10.6'
    docker_scan_plugin:
      package: docker-scan-plugin-0.7.0-3.el8.x86_64.rpm
      package_version: '0.7.0'

  ubuntu:
    docker_ce:
      package_version: 5:23.0.1-1~ubuntu.20.04~focal

docker_config: "{{ docker_defaults | combine(docker | default({}), recursive=True) }}"


