---
# file: roles/prometheus_server/vars/main.yaml

prometheus_data_directory: /var/lib/prometheus
prometheus_version: 2.19.1
prometheus_package_checksum: sha256:c341566bcf1d645b0561e1296bf18b694a283dd83a304f14a288aa284fc2019a

prometheus_user_id: 455
prometheus_group_id: 455

prometheus_node_exporter_port: 9100

prometheus_confluent_schema_registry_jmx_exporter_port: 9110
prometheus_kafka_mirrormaker_jmx_exporter_port: 9130
prometheus_kafka_server_jmx_exporter_port: 9131
prometheus_zookeeper_jmx_exporter_port: 9150
prometheus_zookeeper_exporter_port: 9151
