---
# file: roles/grafana/defaults/main.yaml

grafana_defaults:
  redhat_package: grafana-8.4.1-1.x86_64.rpm
  redhat_package_checksum: sha256:38f712589559ef261ab6809c00ff0061f5bad0809c27ccfb2bbb64dfc765a2d4
  redhat_package_version: '8.4.1'

  ubuntu_package: grafana_8.4.1_amd64.deb
  ubuntu_package_checksum: sha256:3bf07955dd56ffe2badba01ddbc3df5b42ba9be6ad14da38d0fee25c1db29f0b
  ubuntu_package_version: '8.4.1'

  data_directory: /var/lib/grafana
  log_directory: /var/log/grafana

  user: grafana
  user_id: 425
  group: grafana
  group_id: 425

  pie_chart_panel_plugin_version: '1.5.0'

  dashboards:
    kafka_producers_and_consumers:
      enabled: false

grafana_config: "{{ grafana_defaults | combine(grafana | default({}), recursive=True) }}"
