---
# file: roles/grafana/defaults/main.yaml

grafana_defaults:
  redhat_package: grafana-8.0.6-1.x86_64.rpm
  redhat_package_checksum: sha256:081a5d6673cb71ea477e66903fcc7e3bdc2c61712a8fc0de4085f64052c818ef
  redhat_package_version: '8.0.6'

  ubuntu_package: grafana_8.0.6_amd64.deb
  ubuntu_package_checksum: sha256:7aa819d28f15c7c602258990ed0be68e9fcf4217ced60be2052c8b37746826b7
  ubuntu_package_version: '8.0.6'

  data_directory: /var/lib/grafana
  log_directory: /var/log/grafana

  user: grafana
  user_id: 425
  group: grafana
  group_id: 425

  pie_chart_panel_plugin_version: '1.5.0'

  dashboards:
    kafka_producers_and_consumers:
      enabled: false

grafana_config: "{{ grafana_defaults | combine(grafana | default({}), recursive=True) }}"
