---
# file: roles/grafana/defaults/main.yaml

grafana_defaults:
  redhat_package: grafana-7.5.8-1.x86_64.rpm
  redhat_package_checksum: sha256:2ff2d723d8db63962f29eb714ececc78ff187664382d43fff945c333e978affa
  redhat_package_version: '7.5.8'

  ubuntu_package: grafana_7.5.8_amd64.deb
  ubuntu_package_checksum: sha256:e79ba651a71f36df2b82b908e6e3ce43ca428a943a52ed13889855ec752d4028
  ubuntu_package_version: '7.5.8'

  data_directory: /var/lib/grafana
  log_directory: /var/log/grafana

  user: grafana
  user_id: 425
  group: grafana
  group_id: 425

  pie_chart_panel_plugin_version: '1.5.0'

  dashboards:
    kafka_producers_and_consumers:
      enabled: false

grafana_config: "{{ grafana_defaults | combine(grafana | default({}), recursive=True) }}"
