---
# file: roles/grafana/defaults/main.yaml

grafana_defaults:
  redhat_package: grafana-8.0.4-1.x86_64.rpm
  redhat_package_checksum: sha256:4f6c7546f9ea020f552945c1eeeccab16b18dd03d9bfcc3d61d3b9a339cf4740
  redhat_package_version: '8.0.4'

  ubuntu_package: grafana_8.0.4_amd64.deb
  ubuntu_package_checksum: sha256:22a0ae2ab041eab22eac56aed2b96d975c7749847def30494af8dcbfb33c9b4c
  ubuntu_package_version: '8.0.4'

  data_directory: /var/lib/grafana
  log_directory: /var/log/grafana

  user: grafana
  user_id: 425
  group: grafana
  group_id: 425

  pie_chart_panel_plugin_version: '1.5.0'

  dashboards:
    kafka_producers_and_consumers:
      enabled: false

grafana_config: "{{ grafana_defaults | combine(grafana | default({}), recursive=True) }}"
