---
# file: roles/grafana/defaults/main.yaml

grafana_defaults:
  redhat_package: grafana-7.3.7-1.x86_64.rpm
  redhat_package_checksum: sha256:d988a57b03906f6795d862c507978faf01c059ed134a48be84387bb4cd7c012b
  redhat_package_version: 7.3.7

  ubuntu_package: grafana_7.3.7_amd64.deb
  ubuntu_package_checksum: sha256:32ab6b832c3d85b215b535f290b297ec6d1095708775b1f686c5a5cd32fc9257
  ubuntu_package_version: 7.3.7
  
  data_directory: /var/lib/grafana
  log_directory: /var/log/grafana
  
  user: grafana
  user_id: 425
  group: grafana
  group_id: 425

  pie_chart_panel_plugin_version: 1.5.0

  dashboards:
    kafka_producers_and_consumers:
      enabled: false

grafana_config: "{{ grafana_defaults | combine(grafana | default({}), recursive=True) }}"
