---
# file: roles/grafana/defaults/main.yaml

grafana_defaults:
  redhat_package: grafana-9.2.4-1.x86_64.rpm
  redhat_package_checksum: sha256:f88c6f737a87357d4df38143f607bf51dd016ad8719568f695db500c94c6e2a2
  redhat_package_version: '9.2.4'

  ubuntu_package: grafana_9.2.4_amd64.deb
  ubuntu_package_checksum: sha256:0c829f8dacd875167b5e1b22e1cdcccdf31cc87946bb5c72407efc9718d8c004
  ubuntu_package_version: '9.2.4'

  data_directory: /var/lib/grafana
  log_directory: /var/log/grafana

  user: grafana
  user_id: 425
  group: grafana
  group_id: 425

  pie_chart_panel_plugin_version: '1.5.0'

  dashboards:
    kafka_producers_and_consumers:
      enabled: false

grafana_config: "{{ grafana_defaults | combine(grafana | default({}), recursive=True) }}"
