---
# file: roles/k8s_operators/tasks/k8s.yaml

- name: Install the Kubernetes operator components by executing the required tasks on the first master
  block:

  #   ___  ____  _____ ____      _  _____ ___  ____  ____    _   _    _    __  __ _____ ____  ____   _    ____ _____
  #  / _ \|  _ \| ____|  _ \    / \|_   _/ _ \|  _ \/ ___|  | \ | |  / \  |  \/  | ____/ ___||  _ \ / \  / ___| ____|
  # | | | | |_) |  _| | |_) |  / _ \ | || | | | |_) \___ \  |  \| | / _ \ | |\/| |  _| \___ \| |_) / _ \| |   |  _|
  # | |_| |  __/| |___|  _ <  / ___ \| || |_| |  _ < ___) | | |\  |/ ___ \| |  | | |___ ___) |  __/ ___ \ |___| |___
  #  \___/|_|   |_____|_| \_\/_/   \_\_| \___/|_| \_\____/  |_| \_/_/   \_\_|  |_|_____|____/|_| /_/   \_\____|_____|
  #
  - name: Check if the operators namespace exists
    shell:
      cmd: /usr/bin/kubectl get ns | awk  {'print $1'} | grep operators | wc -l
    register: operators_namespace_exists_output

  - name: Create the operators namespace if required
    command:
      cmd: /usr/bin/kubectl create ns operators
    when: operators_namespace_exists_output.stdout == '0'


  #  ____   ___  ____ _____ ____ ____  _____ ____     ___  ____  _____ ____      _  _____ ___  ____
  # |  _ \ / _ \/ ___|_   _/ ___|  _ \| ____/ ___|   / _ \|  _ \| ____|  _ \    / \|_   _/ _ \|  _ \
  # | |_) | | | \___ \ | || |  _| |_) |  _| \___ \  | | | | |_) |  _| | |_) |  / _ \ | || | | | |_) |
  # |  __/| |_| |___) || || |_| |  _ <| |___ ___) | | |_| |  __/| |___|  _ <  / ___ \| || |_| |  _ <
  # |_|    \___/|____/ |_| \____|_| \_\_____|____/   \___/|_|   |_____|_| \_\/_/   \_\_| \___/|_| \_\
  #
  - name: Install the Postgres Operator if it is enabled
    block:
    - name: Check if the Postgres Operator is installed
      shell:
        cmd: /usr/bin/helm -n operators list --filter 'postgres-operator' --output json | jq -r '.[0].chart' | cut -s -f3- -d-
      register: postgres_operator_installed_helm_chart_version_output

    - name: Install the Postgres Operator
      block:
      - name: Copy the Postgres Operator v{{ k8s_postgres_operator_helm_chart_version }} Helm chart
        copy:
          src: postgres-operator-{{ k8s_postgres_operator_helm_chart_version }}.tgz
          dest: /var/tmp/ansible/postgres-operator-{{ k8s_postgres_operator_helm_chart_version }}.tgz

      - name: Generate the Postgres Operator Helm values
        template:
          src: postgres-operator-values.yaml.j2
          dest: /var/tmp/ansible/postgres-operator-values.yaml

      - name: Install the Postgres Operator using Helm
        command:
          cmd: /usr/bin/helm -n operators upgrade --install postgres-operator /var/tmp/ansible/postgres-operator-{{ k8s_postgres_operator_helm_chart_version }}.tgz --values=/var/tmp/ansible/postgres-operator-values.yaml

      - name: Wait for the Postgres Operator initialization to complete
        command:
          cmd: /usr/bin/kubectl wait --namespace=operators --for=condition=Ready pods --all --timeout=1200s

      when: postgres_operator_installed_helm_chart_version_output.stdout != k8s_postgres_operator_helm_chart_version

    when: ((k8s_postgres_operator_enabled is defined) and (k8s_postgres_operator_enabled != None) and (k8s_postgres_operator_enabled == true))


  #  ____   ___  ____ _____ ____ ____  _____ ____     ___  ____  _____ ____      _  _____ ___  ____    _   _ ___
  # |  _ \ / _ \/ ___|_   _/ ___|  _ \| ____/ ___|   / _ \|  _ \| ____|  _ \    / \|_   _/ _ \|  _ \  | | | |_ _|
  # | |_) | | | \___ \ | || |  _| |_) |  _| \___ \  | | | | |_) |  _| | |_) |  / _ \ | || | | | |_) | | | | || |
  # |  __/| |_| |___) || || |_| |  _ <| |___ ___) | | |_| |  __/| |___|  _ <  / ___ \| || |_| |  _ <  | |_| || |
  # |_|    \___/|____/ |_| \____|_| \_\_____|____/   \___/|_|   |_____|_| \_\/_/   \_\_| \___/|_| \_\  \___/|___|
  #
  - name: Install the Postgres Operator UI if it is enabled
    block:
    - name: Check if the Postgres Operator UI is installed
      shell:
        cmd: /usr/bin/helm -n operators list --filter 'postgres-operator-ui' --output json | jq -r '.[0].chart' | cut -s -f4- -d-
      register: postgres_operator_ui_installed_helm_chart_version_output

    - name: Install the Postgres Operator UI
      block:
      - name: Copy the Postgres Operator UI v{{ k8s_postgres_operator_ui_helm_chart_version }} Helm chart
        copy:
          src: postgres-operator-ui-{{ k8s_postgres_operator_ui_helm_chart_version }}.tgz
          dest: /var/tmp/ansible/postgres-operator-ui-{{ k8s_postgres_operator_ui_helm_chart_version }}.tgz

      - name: Generate the Postgres Operator UI Helm values
        template:
          src: postgres-operator-ui-values.yaml.j2
          dest: /var/tmp/ansible/postgres-operator-ui-values.yaml

      - name: Install the Postgres Operator UI using Helm
        command:
          cmd: /usr/bin/helm -n operators upgrade --install postgres-operator-ui /var/tmp/ansible/postgres-operator-ui-{{ k8s_postgres_operator_ui_helm_chart_version }}.tgz --values=/var/tmp/ansible/postgres-operator-ui-values.yaml

      - name: Wait for the Postgres Operator UI initialization to complete
        command:
          cmd: /usr/bin/kubectl wait --namespace=operators --for=condition=Ready pods --all --timeout=1200s

      when: postgres_operator_ui_installed_helm_chart_version_output.stdout != k8s_postgres_operator_ui_helm_chart_version

    when: ((k8s_postgres_operator_enabled is defined) and (k8s_postgres_operator_enabled != None) and (k8s_postgres_operator_enabled == true) and (k8s_postgres_operator_ui_enabled is defined) and (k8s_postgres_operator_ui_enabled != None) and (k8s_postgres_operator_ui_enabled == true))

  delegate_to: "{{ groups['k8s_master'][0] }}"
