---
# file: roles/k8s_operators/tasks/main.yaml

#  _  _____ ____
# | |/ ( _ ) ___|
# | ' // _ \___ \
# | . \ (_) |__) |
# |_|\_\___/____/
#
# Apply the configuration for the Kubernetes operator components to the Kubernetes cluster only to the last master node if there are no workers or the last worker node
- include_tasks: k8s.yaml
  when: (('k8s_worker' not in groups.keys()) and (groups['k8s_master'][((groups['k8s_master']|length) - 1)] == inventory_hostname)) or (('k8s_worker' in groups.keys()) and (groups['k8s_worker'][((groups['k8s_worker']|length) - 1)] == inventory_hostname))

