---
# file: roles/burrow/defaults/main.yaml

burrow_defaults:
  package_version: '1.3.6'
  package_checksum: sha256:2d0f07b65a3840e4c18be7615a5ad32f89cc55c312d3c8d450bb56db3b9e7f68

  etc_directory: /etc/burrow
  log_directory: /var/log/burrow
  run_directory: /var/run/burrow

  user: burrow
  user_id: 318

  group: burrow
  group_id: 318

  http_port: 9105

  kafka_server:
    username: burrow
    secure_broker_port: 9093

  zookeeper:
    secure_client_port: 2182
    username: burrow

burrow_config: "{{ burrow_defaults | combine(burrow | default({}), recursive=True) }}"



