---
# file: roles/burrow/defaults/main.yaml

burrow_defaults:
  package_version: '1.5.0'
  package_checksum: sha256:7ea58c64deb0c4681863c29cc3ee36c8556a82c58ec726152bcc7fc23a357921

  etc_directory: /etc/burrow
  log_directory: /var/log/burrow
  run_directory: /var/run/burrow

  user: burrow
  user_id: 318

  group: burrow
  group_id: 318

  http_port: 9105

  kafka_server:
    username: burrow
    secure_broker_port: 9093

  zookeeper:
    secure_client_port: 2182
    username: burrow

burrow_config: "{{ burrow_defaults | combine(burrow | default({}), recursive=True) }}"



