---
# file: roles/monitored/tasks/centos.yaml

- debug:
    msg: Applying the CentOS-specific monitored configuration

- name: Allow all hosts access to tcp port {{ prometheus_node_exporter_port }}
  firewalld:
    port: '{{ prometheus_node_exporter_port }}/tcp'
    permanent: yes
    state: enabled
    immediate: yes


