---
# file: roles/monitored/tasks/main.yaml

- set_fact:
    prometheus_data_directory: "{{ prometheus_data_directory if ((prometheus_data_directory is defined) and (prometheus_data_directory != None)) else '/var/lib/prometheus' }}"

- include_tasks: ubuntu.yaml
  when: ansible_distribution == "Ubuntu"
  tags:
  - unbound

- include_tasks: redhat.yaml
  when: ansible_distribution == "CentOS"
  tags:
  - unbound

- name: Install the Prometheus Node Exporter
  block:
  - debug:
      msg: Check whether the Prometheus Node Exporter {{ prometheus_node_exporter_version }} package has been installed

  - stat:
      path: /usr/bin/prometheus-node-exporter
    register: prometheus_node_exporter_installed_stat_result

  - shell:
      cmd: /usr/bin/prometheus-node-exporter --version 2>&1 | head -1 | awk {'print $3'}
    register: prometheus_node_exporter_installed_version_output
    when: (prometheus_node_exporter_installed_stat_result.stat.exists == True)

  - set_fact:
      prometheus_node_exporter_installed_version: '{{ prometheus_node_exporter_installed_version_output.stdout }}'
    when: (prometheus_node_exporter_installed_stat_result.stat.exists == True)

  - set_fact:
      prometheus_node_exporter_installed_version: ''
    when: (prometheus_node_exporter_installed_stat_result.stat.exists == False)

  - block:
    - debug:
        msg: Install the Prometheus Node Exporter {{ prometheus_node_exporter_version }} package

    - name: Add the prometheus group
      group:
        name: prometheus
        gid: '{{ prometheus_group_id }}'
        state: present

    - name: Add the prometheus user
      user:
        name: prometheus
        uid: '{{ prometheus_user_id }}'
        group: prometheus
        create_home: no
        shell: /usr/sbin/nologin
        state: present

    - name: Check whether the Prometheus Node Exporter service exists
      stat:
        path: /lib/systemd/system/prometheus-node-exporter.service
      register: prometheus_node_exporter_service_stat_result

    - name: Stop the Prometheus Node Exporter service
      service:
        name: prometheus-node-exporter.service
        state: stopped
      when: prometheus_node_exporter_service_stat_result.stat.exists == True
      register: prometheus_node_exporter_service_stopped

    - name: Check whether the Prometheus Node Exporter {{ prometheus_node_exporter_version }} package has been downloaded
      become: no
      local_action: stat path='{{ packages_root }}/{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}/node_exporter-{{ prometheus_node_exporter_version }}.linux-amd64.tar.gz'
      register: prometheus_node_exporter_package_stat_result

    - name: Download the Prometheus Node Exporter {{ prometheus_node_exporter_version }} package
      become: no
      local_action: get_url url='https://github.com/prometheus/node_exporter/releases/download/v{{ prometheus_node_exporter_version }}/node_exporter-{{ prometheus_node_exporter_version }}.linux-amd64.tar.gz' dest='{{ packages_root }}/{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}/node_exporter-{{ prometheus_node_exporter_version }}.linux-amd64.tar.gz' checksum={{ prometheus_node_exporter_package_checksum }}
      when: (prometheus_node_exporter_package_stat_result.stat.exists == False)

    - name: Remove the existing prometheus-node-exporter binary
      file:
        path: /usr/bin/prometheus-node-exporter
        state: absent

    - name: Extract the node_exporter binary from the Prometheus Node Exporter {{ prometheus_node_exporter_version }} package
      unarchive:
        src: '{{ packages_root }}/{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}/node_exporter-{{ prometheus_node_exporter_version }}.linux-amd64.tar.gz'
        dest: /usr/bin
        extra_opts:
        - --strip-components=1
        - node_exporter-{{ prometheus_node_exporter_version }}.linux-amd64/node_exporter
        creates: /usr/bin/node_exporter

    - name: Rename the node_exporter binary extracted from the Prometheus Node Exporter {{ prometheus_node_exporter_version }} package to prometheus-node-exporter
      command:
        cmd: mv /usr/bin/node_exporter /usr/bin/prometheus-node-exporter

    when: (prometheus_node_exporter_installed_version != prometheus_node_exporter_version)

- name: Generate the Prometheus Node Exporter environment
  template:
    src: prometheus-node-exporter-environment
    dest: /etc/default/prometheus-node-exporter

- name: Create the Prometheus Node Exporter systemd unit
  template:
    src: prometheus-node-exporter.service.j2
    dest: /lib/systemd/system/prometheus-node-exporter.service

- name: Restart the Prometheus Node Exporter service
  systemd:
    name: prometheus-node-exporter.service
    state: started
    enabled: yes
    daemon_reload: yes

