---
# file: roles/k8s_storage/tasks/main.yaml

- ansible.builtin.import_tasks: assert.yaml
  run_once: yes
  delegate_to: localhost


#   ___  ____       ____  ____  _____ ____ ___ _____ ___ ____
#  / _ \/ ___|     / ___||  _ \| ____/ ___|_ _|  ___|_ _/ ___|
# | | | \___ \ ____\___ \| |_) |  _|| |    | || |_   | | |
# | |_| |___) |_____|__) |  __/| |__| |___ | ||  _|  | | |___
#  \___/|____/     |____/|_|   |_____\____|___|_|   |___\____|
#
- include_tasks: ubuntu.yaml
  when: ansible_distribution == 'Ubuntu'
  tags:
  - unbound

- include_tasks: redhat.yaml
  when: ansible_os_family == 'RedHat'
  tags:
  - unbound


#  _____ ___  ____   ___  _ __     ____  __   _ __     ____  __ ____
# |_   _/ _ \|  _ \ / _ \| |\ \   / /  \/  | | |\ \   / /  \/  |  _ \
#   | || | | | |_) | | | | | \ \ / /| |\/| | | | \ \ / /| |\/| | | | |
#   | || |_| |  __/| |_| | |__\ V / | |  | | | |__\ V / | |  | | |_| |
#   |_| \___/|_|    \___/|_____\_/  |_|  |_| |_____\_/  |_|  |_|____/
#
- name: Install the TopoLVM lvmd {{ k8s_config.storage.topolvm.lvmd_version }} package if TopoLVM is enabled and this is a worker or there are no workers only masters
  block:
  - name: Create the /etc/topolvm directory
    ansible.builtin.file:
      path: /etc/topolvm
      owner: 'root'
      group: 'root'
      mode: '0755'
      state: directory

  - ansible.builtin.debug:
      msg: Check whether the TopoLVM lvmd {{ k8s_config.storage.topolvm.lvmd_version }} package has been installed

  - ansible.builtin.stat:
      path: /usr/bin/lvmd
    register: topolvm_lvmd_installed_stat_result

  - ansible.builtin.shell:
      cmd: /usr/bin/lvmd --version | awk  {'print $3'}
    register: topolvm_lvmd_installed_version_output
    when: (topolvm_lvmd_installed_stat_result.stat.exists == True)

  - ansible.builtin.set_fact:
      topolvm_lvmd_installed_version: '{{ topolvm_lvmd_installed_version_output.stdout }}'
    when: (topolvm_lvmd_installed_stat_result.stat.exists == True)

  - ansible.builtin.set_fact:
      topolvm_lvmd_installed_version: ''
    when: (topolvm_lvmd_installed_stat_result.stat.exists == False)

  - block:
    - ansible.builtin.debug:
        msg: Install the TopoLVM lvmd {{ k8s_config.storage.topolvm.lvmd_version }} package

    - name: Check whether the TopoLVM lvmd {{ k8s_config.storage.topolvm.lvmd_version }} package has been downloaded
      become: no
      local_action: ansible.builtin.stat path='{{ packages_root }}/{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}/lvmd-{{ k8s_config.storage.topolvm.lvmd_version }}.tar.gz'
      register: topolvm_lvmd_package_stat_result

    - name: Download the TopoLVM lvmd {{ k8s_config.storage.topolvm.lvmd_version }} package
      become: no
      local_action: ansible.builtin.get_url url='https://github.com/cybozu-go/topolvm/releases/download/v{{ k8s_config.storage.topolvm.lvmd_version }}/lvmd-{{ k8s_config.storage.topolvm.lvmd_version }}.tar.gz' dest='{{ packages_root }}/{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}/lvmd-{{ k8s_config.storage.topolvm.lvmd_version }}.tar.gz'
      when: (topolvm_lvmd_package_stat_result.stat.exists == False)

    - name: Remove the existing TopoLVM lvmd binary
      ansible.builtin.file:
        path: /usr/bin/lvmd
        state: absent

    - name: Extract the TopoLVM lvmd binary from the TopoLVM lvmd {{ k8s_config.storage.topolvm.lvmd_version }} package
      ansible.builtin.unarchive:
        src: '{{ packages_root }}/{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}/lvmd-{{ k8s_config.storage.topolvm.lvmd_version }}.tar.gz'
        dest: /usr/bin
        creates: /usr/bin/lvmd

    - ansible.builtin.template:
        src: topolvm/lvmd.yaml.j2
        dest: /etc/topolvm/lvmd.yaml
        owner: 'root'
        group: 'root'
        mode: '0755'

    - ansible.builtin.template:
        src: topolvm/lvmd.service.j2
        dest: /lib/systemd/system/lvmd.service
        owner: 'root'
        group: 'root'
        mode: '0755'

    - name: Restart the lvmd systemd service
      ansible.builtin.systemd:
        name: lvmd
        state: restarted
        enabled: yes
        daemon_reload: yes

    - name: Ensure that the lvmd service is started
      ansible.builtin.systemd:
        name: lvmd
        state: started
        enabled: yes

    when: (topolvm_lvmd_installed_version != k8s_config.storage.topolvm.lvmd_version)

  when: ((('k8s_worker' not in groups.keys()) or (inventory_hostname in groups['k8s_worker'])) and (k8s_config.storage.topolvm.enabled is defined) and (k8s_config.storage.topolvm.enabled != None) and (k8s_config.storage.topolvm.enabled == true))


#  _  _____ ____
# | |/ ( _ ) ___|
# | ' // _ \___ \
# | . \ (_) |__) |
# |_|\_\___/____/
#
# Apply the configuration for the Kubernetes storage components to the Kubernetes cluster only to the last master node if there are no workers or the last worker node
- include_tasks: k8s.yaml
  when: (('k8s_worker' not in groups.keys()) and (groups['k8s_master'][((groups['k8s_master']|length) - 1)] == inventory_hostname)) or (('k8s_worker' in groups.keys()) and (groups['k8s_worker'][((groups['k8s_worker']|length) - 1)] == inventory_hostname))


