---
# file: roles/k8s_storage/tasks/redhat.yaml

- ansible.builtin.debug:
    msg: Applying the RedHat-specific Kubernetes storage configuration

- name: Allow all hosts access to tcp port 3260 (iSCSI)
  ansible.posix.firewalld:
    port: 3260/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: Install the iSCSI client if this is a worker or there are no workers only masters
  block:
  - name: Install the open-iscsi package
    ansible.builtin.yum:
      name: iscsi-initiator-utils
      state: present

  - name: Start the iscsid service
    ansible.builtin.systemd:
      name: iscsid
      state: started
      enabled: yes

  when: (('k8s_worker' not in groups.keys()) or (inventory_hostname in groups['k8s_worker']))
