---
# file: roles/kafka_server/tasks/centos.yaml

- debug:
    msg: Applying the CentOS-specific Kafka Server configuration

- name: Allow all hosts access to tcp port {{ kafka_config.kafka_server.secure_broker_port }} (Kafka Secure Broker Port)
  firewalld:
    port: '{{ kafka_config.kafka_server.secure_broker_port }}/tcp'
    permanent: yes
    state: enabled
    immediate: yes

- name: Allow all hosts access to tcp port {{ kafka_config.kafka_server.prometheus_jmx_exporter.port }} (Prometheus JMX Exporter Port)
  firewalld:
    port: '{{ kafka_config.kafka_server.prometheus_jmx_exporter.port }}/tcp'
    permanent: yes
    state: enabled
    immediate: yes
  when: ((kafka_config.kafka_server.prometheus_jmx_exporter.enabled is defined) and (kafka_config.kafka_server.prometheus_jmx_exporter.enabled != None) and (kafka_config.kafka_server.prometheus_jmx_exporter.enabled == true))
