---
# file: roles/kafka_server/tasks/ubuntu.yaml

- debug:
    msg: Applying the Ubuntu-specific Kafka Server configuration

- name: Enable the firewall
  ufw:
    state: enabled
    policy: deny

- name: Allow all access to tcp port {{ kafka_secure_broker_port }} (Kafka Secure Broker Port)
  ufw:
    rule: allow
    port: '{{ kafka_secure_broker_port }}'
    proto: tcp

- name: Allow all access to tcp port {{ prometheus_kafka_server_jmx_exporter_port }} (Prometheus JMX Exporter Port)
  ufw:
    rule: allow
    port: '{{ prometheus_kafka_server_jmx_exporter_port }}'
    proto: tcp
  when: ((prometheus_jmx_exporter_enabled is defined) and (prometheus_jmx_exporter_enabled != None) and (prometheus_jmx_exporter_enabled == true))

