---
#file: roles/common/tasks/main.yaml

#   ___  ____       ____  ____  _____ ____ ___ _____ ___ ____
#  / _ \/ ___|     / ___||  _ \| ____/ ___|_ _|  ___|_ _/ ___|
# | | | \___ \ ____\___ \| |_) |  _|| |    | || |_   | | |
# | |_| |___) |_____|__) |  __/| |__| |___ | ||  _|  | | |___
#  \___/|____/     |____/|_|   |_____\____|___|_|   |___\____|
#
- include_tasks: ubuntu.yaml
  when: ansible_distribution == "Ubuntu"
  tags:
  - unbound

- include_tasks: centos.yaml
  when: ansible_distribution == "CentOS"
  tags:
  - unbound


#   ____ ___  __  __ __  __  ___  _   _
#  / ___/ _ \|  \/  |  \/  |/ _ \| \ | |
# | |  | | | | |\/| | |\/| | | | |  \| |
# | |__| |_| | |  | | |  | | |_| | |\  |
#  \____\___/|_|  |_|_|  |_|\___/|_| \_|
#
- name: Create the /var/tmp/ansible directory
  file:
    path: /var/tmp/ansible
    owner: root
    group: root
    mode: 0700
    state: directory
