---
# file: roles/common/tasks/ubuntu.yaml

- debug:
    msg: Applying the Ubuntu-specific common configuration
    
- name: Install the python3-pip package
  apt:
    state: present
    name:
     - python3-pip

- name: Install the pyOpenSSL package using pip
  pip: 
    name: pyOpenSSL

- name: If the data disk is present (sdb) then create the data volume group if it does not exist
  block:
  - name: Create the data volume group
    lvg:
      vg: data
      pvs: /dev/sdb

  - name: Collect only facts about hardware
    setup:
      gather_subset:
      - hardware

  when: (('sdb' in ansible_devices) and ('wwn' not in ansible_devices['sdb']) and ('data' not in ansible_lvm.vgs))

- name: Initialise the /data directory
  block:
  - name: Create the /data directory
    file:
      path: /data
      owner: 'root'
      group: 'root'
      mode: '0755'
      state: directory

  - name: Create and format the data logical volume in the data volume group and mount it under the /data directory
    block:
    - name: Create the data logical volume in the data volume group
      lvol:
        vg: data
        lv: data
        size: 100%FREE
      when: ('data' not in ansible_lvm.lvs)

    - name: Format the data logical volume in the data volume group using the xfs filesystem
      filesystem:
        fstype: ext4
        dev: /dev/data/data

    - name: Mount the data logical volume in the data volume group under the /data directory
      mount:
        path: /data
        src: /dev/mapper/data-data
        fstype: ext4
        state: mounted

    when: ('data' in ansible_lvm.vgs)

  when: (common_config.initialise_data_directory == True)