---
# file: roles/common/tasks/ubuntu.yaml

- debug:
    msg: Applying the Ubuntu-specific common configuration


#  ____   _    ____ _  __    _    ____ _____ ____
# |  _ \ / \  / ___| |/ /   / \  / ___| ____/ ___|
# | |_) / _ \| |   | ' /   / _ \| |  _|  _| \___ \
# |  __/ ___ \ |___| . \  / ___ \ |_| | |___ ___) |
# |_| /_/   \_\____|_|\_\/_/   \_\____|_____|____/
#
- name: Install the python3-pip package
  apt:
    state: present
    name:
     - python3-pip


#  ____ ___ ____    ____   _    ____ _  __    _    ____ _____ ____
# |  _ \_ _|  _ \  |  _ \ / \  / ___| |/ /   / \  / ___| ____/ ___|
# | |_) | || |_) | | |_) / _ \| |   | ' /   / _ \| |  _|  _| \___ \
# |  __/| ||  __/  |  __/ ___ \ |___| . \  / ___ \ |_| | |___ ___) |
# |_|  |___|_|     |_| /_/   \_\____|_|\_\/_/   \_\____|_____|____/
#
- name: Install the pyOpenSSL package using pip
  pip:
    name: pyOpenSSL


#  ____    _  _____  _     __     _____  _    _   _ __  __ _____
# |  _ \  / \|_   _|/ \    \ \   / / _ \| |  | | | |  \/  | ____|
# | | | |/ _ \ | | / _ \    \ \ / / | | | |  | | | | |\/| |  _|
# | |_| / ___ \| |/ ___ \    \ V /| |_| | |__| |_| | |  | | |___
# |____/_/   \_\_/_/   \_\    \_/  \___/|_____\___/|_|  |_|_____|
#
- name: If the data disk is present (sdb) then create the data volume group if it does not exist
  block:
  - name: Create the data volume group
    community.general.lvg:
      vg: data
      pvs: /dev/sdb

  - name: Collect only facts about hardware
    setup:
      gather_subset:
      - hardware

  when: (('sdb' in ansible_devices) and ('data' not in ansible_lvm.vgs))

- name: Initialise the /data directory
  block:
  - name: Create the /data directory
    file:
      path: /data
      owner: 'root'
      group: 'root'
      mode: '0755'
      state: directory

  - name: Create and format the data logical volume in the data volume group and mount it under the /data directory
    block:
    - name: Create the data logical volume in the data volume group
      community.general.lvol:
        vg: data
        lv: data
        size: 100%FREE
      when: ('data' not in ansible_lvm.lvs)

    - name: Format the data logical volume in the data volume group using the xfs filesystem
      community.general.filesystem:
        fstype: ext4
        dev: /dev/data/data

    - name: Mount the data logical volume in the data volume group under the /data directory
      ansible.posix.mount:
        path: /data
        src: /dev/mapper/data-data
        fstype: ext4
        state: mounted

    when: ('data' in ansible_lvm.vgs)

  when: (common_config.initialise_data_directory == True)


#  _____ ___ ____  _______        ___    _     _
# |  ___|_ _|  _ \| ____\ \      / / \  | |   | |
# | |_   | || |_) |  _|  \ \ /\ / / _ \ | |   | |
# |  _|  | ||  _ <| |___  \ V  V / ___ \| |___| |___
# |_|   |___|_| \_\_____|  \_/\_/_/   \_\_____|_____|
#
- name: Enable the firewall
  ufw:
    state: enabled
    policy: deny

- name: Allow all hosts access to tcp port 22 (SSH)
  ufw:
    rule: allow
    port: '22'
    proto: tcp


