---
# file: roles/confluent_zookeeper/handlers/main.yaml

- name: Reload systemctl daemon
  command:
    cmd: systemctl daemon-reload
  when: ansible_service_mgr == 'systemd'

- name: restart zookeeper
  systemd:
    name: zookeeper
    state: restarted
