---
# file: roles/confluent_zookeeper/handlers/main.yaml

- name: Reload systemctl daemon
  ansible.builtin.command: systemctl daemon-reload
  when: ansible_service_mgr == 'systemd'

- name: restart zookeeper
  ansible.builtin.systemd:
    name: zookeeper
    state: restarted
