---
#file: roles/confluent_kafka_mirrormaker/vars/main.yaml

kafka_secure_broker_port: 9093

kafka_mirrormaker_etc_directory: /etc/kafka
kafka_mirrormaker_log_directory: /var/log/kafka

kafka_mirrormaker_user: cp-kafka
kafka_mirrormaker_user_id: 311
kafka_mirrormaker_group: cp-kafka
kafka_mirrormaker_group_id: 311

kafka_mirrormaker_user_username: mirrormaker

prometheus_jmx_exporter_enabled: true
prometheus_jmx_exporter_version: 0.13.0
prometheus_kafka_mirrormaker_jmx_exporter_port: 9130

