---
# file: roles/etcd/tasks/assert.yaml

- name: Check the etcd variable is defined correctly
  ansible.builtin.assert:
    that:
    - etcd is defined
    quiet: yes

- name: Check the etcd.clusters variable is defined correctly
  ansible.builtin.assert:
    that:
    - etcd.clusters is defined
    - (etcd.clusters | length) >  0
    quiet: yes
