---
# file: roles/etcd/tasks/redhat.yaml

- debug:
    msg: Applying the RedHat-specific etcd configuration

- name: Allow all hosts access to tcp port 2379
  firewalld:
    port: 2379/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: Allow all hosts access to tcp port 2380
  firewalld:
    port: 2380/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: Collect the package facts
  package_facts:
    manager: auto
