---
# file: roles/etcd/tasks/ubuntu.yaml

- debug:
    msg: Applying the Ubuntu-specific etcd configuration

- name: Enable the firewall
  ufw:
    state: enabled
    policy: deny

- name: Allow all hosts access to tcp port 2379
  ufw:
    rule: allow
    port: '2379'
    proto: tcp

- name: Allow all hosts access to tcp port 2380
  ufw:
    rule: allow
    port: '2380'
    proto: tcp
