---
# file: roles/etcd/tasks/ubuntu.yaml

- ansible.builtin.debug:
    msg: Applying the Ubuntu-specific etcd configuration

- name: Allow all hosts access to tcp port 2379
  community.general.ufw:
    rule: allow
    port: '2379'
    proto: tcp

- name: Allow all hosts access to tcp port 2380
  community.general.ufw:
    rule: allow
    port: '2380'
    proto: tcp
