---
# file: roles/confluent_kafka_server/tasks/ubuntu.yaml

- debug:
    msg: Applying the Ubuntu-specific Kafka Server configuration

- name: Enable the firewall
  ufw:
    state: enabled
    policy: deny

- name: Allow all hosts access to tcp port {{ confluent_config.kafka_server.secure_broker_port }} (Kafka Secure Broker Port)
  ufw:
    rule: allow
    port: '{{ confluent_config.kafka_server.secure_broker_port }}'
    proto: tcp

- name: Allow all hosts access to tcp port {{ confluent_config.kafka_server.prometheus_jmx_exporter.port }} (Prometheus JMX Exporter Port)
  ufw:
    rule: allow
    port: '{{ confluent_config.kafka_server.prometheus_jmx_exporter.port }}'
    proto: tcp
  when: ((confluent_config.kafka_server.prometheus_jmx_exporter.enabled is defined) and (confluent_config.kafka_server.prometheus_jmx_exporter.enabled != None) and (confluent_config.kafka_server.prometheus_jmx_exporter.enabled == true))

- name: Allow access to the remote JMX tcp ports
  block:
  - ufw:
      rule: allow
      port: '9998'
      proto: tcp
  - ufw:
      rule: allow
      port: '9999'
      proto: tcp
  when: ((confluent_config.kafka_server.enable_remote_jmx is defined) and (confluent_config.kafka_server.enable_remote_jmx != None) and (confluent_config.kafka_server.enable_remote_jmx == true))
