---
# file: roles/k8s_operators/defaults/main.yaml

pki_root: ../../../pki

k8s_postgres_operator_enabled: false
k8s_postgres_operator_helm_chart_version: 1.5.0
k8s_postgres_operator_ui_enabled: true
k8s_postgres_operator_ui_helm_chart_version: 1.5.0

k8s_config: "{{ k8s_defaults | combine(k8s | default({}), recursive=True) }}"
