---
# file: roles/common/defaults/main.yaml

common_defaults:

  initialise_data_directory: false

common_config: "{{ common_defaults | combine(common | default({}), recursive=True) }}"

epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
epel_repo_gpg_key_url: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
epel_repofile_path: "/etc/yum.repos.d/epel.repo"

credentials_root: "{{ playbook_dir }}/credentials"
packages_root: "{{ playbook_dir }}/packages"
pki_root: "{{ playbook_dir }}/pki"
