# file: roles/grafana/tasks/centos.yaml

- debug:
    msg: Applying the CentOS-specific Grafana configuration
    
- name: Allow all access to tcp port 3000
  firewalld:
    port: 3000/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: Collect the package facts
  package_facts:
    manager: auto

- name: Retrieve the version of the installed grafana package
  debug:
    msg: Found grafana package version {{ ansible_facts.packages['grafana'][0].version  }}
  when: "'grafana' in ansible_facts.packages"

- name: Install the grafana package
  block:
  - name: Check whether the Grafana {{ grafana_centos_package_version }} package has been downloaded
    become: no
    local_action: stat path=packages/grafana_{{ grafana_centos_package_version }}_amd64.deb
    register: grafana_package_stat_result  

  - name: Download the Grafana {{ grafana_centos_package_version }} package
    become: no
    local_action: get_url url='https://dl.grafana.com/oss/release/grafana-{{ grafana_centos_package_version }}-1.x86_64.rpm' dest='packages/grafana-{{ grafana_centos_package_version }}-1.x86_64.rpm' checksum={{ grafana_centos_package_checksum }}
    when: (grafana_package_stat_result.stat.exists == False)
  
  - name: Copy the Grafana {{ grafana_centos_package_version }} package
    copy:
      src: packages/grafana-{{ grafana_centos_package_version }}-1.x86_64.rpm
      dest: /var/tmp/ansible/grafana-{{ grafana_centos_package_version }}-1.x86_64.rpm
  
  - name: Install the grafana package ({{ grafana_centos_package_version }})
    yum:
      name: /var/tmp/ansible/grafana-{{ grafana_centos_package_version }}-1.x86_64.rpm
      state: present

  when: (('grafana' not in ansible_facts.packages) or (ansible_facts.packages['grafana'][0].version != grafana_centos_package_version))
