---
# file: roles/grafana/tasks/centos.yaml

- debug:
    msg: Applying the CentOS-specific Grafana configuration

- name: Allow all access to tcp port 3000
  firewalld:
    port: 3000/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: Collect the package facts
  package_facts:
    manager: auto

- name: Retrieve the version of the installed grafana package
  debug:
    msg: Found the installed grafana package ({{ ansible_facts.packages['grafana'][0].version  }})
  when: ('grafana' in ansible_facts.packages)

- name: Install the grafana package
  block:
  - name: Check whether the {{ grafana_centos_package }} package has been downloaded
    become: no
    local_action: stat path=packages/{{ grafana_centos_package }}
    register: grafana_package_stat_result

  - name: Download the {{ grafana_centos_package }} package
    become: no
    local_action: get_url url='https://dl.grafana.com/oss/release/{{ grafana_centos_package }}' dest='packages/{{ grafana_centos_package }}' checksum={{ grafana_centos_package_checksum }}
    when: (grafana_package_stat_result.stat.exists == False)

  - name: Copy the {{ grafana_centos_package }} package
    copy:
      src: packages/{{ grafana_centos_package }}
      dest: /var/tmp/ansible/{{ grafana_centos_package }}

  - name: Install the {{ grafana_centos_package }} package
    yum:
      name: /var/tmp/ansible/{{ grafana_centos_package }}
      state: present

  when: (('grafana' not in ansible_facts.packages) or (ansible_facts.packages['grafana'][0].version != grafana_centos_package_version))
