---
# file: roles/grafana/tasks/redhat.yaml

- debug:
    msg: Applying the RedHat-specific Grafana configuration

- name: Allow all hosts access to tcp port 3000
  firewalld:
    port: 3000/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: Collect the package facts
  package_facts:
    manager: auto

- name: Retrieve the version of the installed grafana package
  debug:
    msg: Found the installed grafana package ({{ ansible_facts.packages['grafana'][0].version  }})
  when: ('grafana' in ansible_facts.packages)

- name: Install the grafana package
  block:
  - name: Check whether the {{ grafana_config.redhat_package }} package has been downloaded
    become: no
    local_action: stat path='{{ packages_root }}/{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}/{{ grafana_config.redhat_package }}'
    register: grafana_package_stat_result

  - name: Download the {{ grafana_config.redhat_package }} package
    become: no
    local_action: get_url url='https://dl.grafana.com/oss/release/{{ grafana_config.redhat_package }}' dest='{{ packages_root }}/{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}/{{ grafana_config.redhat_package }}' checksum={{ grafana_config.redhat_package_checksum }}
    when: (grafana_package_stat_result.stat.exists == False)

  - name: Copy the {{ grafana_config.redhat_package }} package
    copy:
      src: '{{ packages_root }}/{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}/{{ grafana_config.redhat_package }}'
      dest: /var/tmp/ansible/{{ grafana_config.redhat_package }}

  - name: Install the {{ grafana_config.redhat_package }} package
    yum:
      name: /var/tmp/ansible/{{ grafana_config.redhat_package }}
      state: present

  when: (('grafana' not in ansible_facts.packages) or (ansible_facts.packages['grafana'][0].version != grafana_config.redhat_package_version))
