---
# file: roles/grafana/tasks/ubuntu.yaml

- debug:
    msg: Applying the Ubuntu-specific Grafana configuration

- name: Allow all access to tcp port 3000
  ufw:
    rule: allow
    port: '3000'
    proto: tcp

- name: Add the Grafana GPG apt key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add the Grafana repository
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present

- name: Collect the package facts
  package_facts:
    manager: auto

- name: Retrieve the version of the installed grafana package
  debug:
    msg: Found grafana package version {{ ansible_facts.packages['grafana'][0].version  }}
  when: "'grafana' in ansible_facts.packages"

- name: Install the grafana package
  block:
  - name: Check whether the Grafana {{ grafana_package_version }} package has been downloaded
    become: no
    local_action: stat path=packages/grafana_{{ grafana_package_version }}_amd64.deb
    register: grafana_package_stat_result  

  - name: Download the Grafana {{ grafana_package_version }} package
    become: no
    local_action: get_url url='https://dl.grafana.com/oss/release/grafana_{{ grafana_package_version }}_amd64.deb' dest='packages/grafana_{{ grafana_package_version }}_amd64.deb' checksum={{ grafana_ubuntu_package_checksum }}
    when: (grafana_package_stat_result.stat.exists == False)
  
  - name: Copy the Grafana {{ grafana_package_version }} package
    copy:
      src: packages/grafana_{{ grafana_package_version }}_amd64.deb
      dest: /var/tmp/ansible/grafana_{{ grafana_package_version }}_amd64.deb
  
  - name: Unlock the version of the grafana package
    command:
      cmd: apt-mark unhold grafana  

  - name: Install the grafana package ({{ grafana_package_version }})
    apt:
      state: present
      policy_rc_d: 101
      deb: /var/tmp/ansible/grafana_{{ grafana_package_version }}_amd64.deb

  - name: Lock the version of the grafana package
    command:
      cmd: apt-mark hold grafana

  when: (('grafana' not in ansible_facts.packages) or (ansible_facts.packages['grafana'][0].version != grafana_ubuntu_package_version))




