---
# file: roles/grafana/tasks/ubuntu.yaml

- debug:
    msg: Applying the Ubuntu-specific Grafana configuration

- name: Allow all hosts access to tcp port 3000
  ufw:
    rule: allow
    port: '3000'
    proto: tcp

- name: Add the Grafana GPG apt key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Collect the package facts
  package_facts:
    manager: auto

- name: Retrieve the version of the installed grafana package
  debug:
    msg: Found the installed grafana package ({{ ansible_facts.packages['grafana'][0].version }})
  when: "'grafana' in ansible_facts.packages"

- name: Install the grafana package
  block:
  - name: Check whether the {{ grafana_config.ubuntu_package }} package has been downloaded
    become: no
    local_action: stat path='{{ packages_root }}/{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}/{{ grafana_config.ubuntu_package }}'
    register: grafana_package_stat_result  

  - name: Download the {{ grafana_config.ubuntu_package }} package
    become: no
    local_action: get_url url='https://dl.grafana.com/oss/release/{{ grafana_config.ubuntu_package }}' dest='{{ packages_root }}/{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}/{{ grafana_config.ubuntu_package }}' checksum={{ grafana_config.ubuntu_package_checksum }}
    when: (grafana_package_stat_result.stat.exists == False)
  
  - name: Copy the {{ grafana_config.ubuntu_package }} package
    copy:
      src: '{{ packages_root }}/{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}/{{ grafana_config.ubuntu_package }}'
      dest: /var/tmp/ansible/{{ grafana_config.ubuntu_package }}
  
  - name: Unlock the version of the grafana package
    command:
      cmd: apt-mark unhold grafana  

  - name: Install the {{ grafana_config.ubuntu_package }} package
    apt:
      state: present
      policy_rc_d: 101
      deb: /var/tmp/ansible/{{ grafana_config.ubuntu_package }}

  - name: Lock the version of the grafana package
    command:
      cmd: apt-mark hold grafana

  when: (('grafana' not in ansible_facts.packages) or (ansible_facts.packages['grafana'][0].version != grafana_config.ubuntu_package_version))




