---
# file: roles/k8s_storage/defaults/main.yaml

pki_root: ../../../pki

k8s_defaults:
  storage:
    longhorn:
      enabled: false
      helm_chart_version: 1.0.2
    topolvm:
      enabled: false
      lvmd_version: 0.6.0
      version: 0.6.0
      volume_group: system

k8s_config: "{{ k8s_defaults | combine(k8s | default({}), recursive=True) }}"
