---
# file: roles/k8s_storage/defaults/main.yaml

k8s_defaults:
  storage:
    longhorn:
      enabled: false
      helm_chart_version: '1.3.2'
    topolvm:
      enabled: true
      lvmd_version: '0.15.3'
      version: '0.15.3'
      volume_group: system

k8s_config: "{{ k8s_defaults | combine(k8s | default({}), recursive=True) }}"
