# file: roles/k8s_common/tasks/main.yaml

- name: Create the /var/cache/ansible directory
  file:
    path: /var/cache/ansible
    state: directory

- name: Add the k8s-admin group
  group:
    name: k8s-admin
    gid: 301
    state: present

- name: Allow k8s-admin group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%k8s-admin'
    line: '%k8s-admin ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- include_tasks: ubuntu.yaml
  when: ansible_distribution == "Ubuntu"
  tags:
  - unbound

- include_tasks: centos.yaml
  when: ansible_distribution == "CentOS"
  tags:
  - unbound
