---
# file: roles/k8s_common/tasks/redhat.yaml

- ansible.builtin.debug:
    msg: Applying the RedHat-specific Kubernetes common configuration

- name: Collect the system service facts
  service_facts:
  register: services_state

- name: Collect the package facts
  package_facts:
    manager: auto


#   ____ _____ ____ _____ ___ _____ ___ ____    _  _____ _____      _   _   _ _____ _   _  ___  ____  ___ _____ ___ _____ ____
#  / ___| ____|  _ \_   _|_ _|  ___|_ _/ ___|  / \|_   _| ____|    / \ | | | |_   _| | | |/ _ \|  _ \|_ _|_   _|_ _| ____/ ___|
# | |   |  _| | |_) || |  | || |_   | | |     / _ \ | | |  _|     / _ \| | | | | | | |_| | | | | |_) || |  | |  | ||  _| \___ \
# | |___| |___|  _ < | |  | ||  _|  | | |___ / ___ \| | | |___   / ___ \ |_| | | | |  _  | |_| |  _ < | |  | |  | || |___ ___) |
#  \____|_____|_| \_\|_| |___|_|   |___\____/_/   \_\_| |_____| /_/   \_\___/  |_| |_| |_|\___/|_| \_\___| |_| |___|_____|____/
#
- name: Install the root CA, Kubernetes intermediate CA and Kubernetes etcd intermediate CA certificates
  block:
  - name: Copy the root CA certificate for the Kubernetes cluster to the /etc/pki/ca-trust/source/anchors directory
    ansible.builtin.copy:
      src: '{{ pki_root }}/{{ role_name }}/{{ k8s_config.cluster_name }}/ca.crt'
      dest: '/etc/pki/ca-trust/source/anchors/ca.crt'

  - name: Copy the Kubernetes intermediate CA certificate for the Kubernetes cluster to the /etc/pki/ca-trust/source/anchors directory
    ansible.builtin.copy:
      src: "{{ pki_root }}/{{ role_name }}/{{ k8s_config.cluster_name }}/k8s-ca-{{ k8s_config.cluster_name.replace('_', '-') }}.crt"
      dest: "/etc/pki/ca-trust/source/anchors/k8s-ca-{{ k8s_config.cluster_name.replace('_', '-') }}.crt"

  - name: Update the certificate index to install the CA certificate for the Kubernetes cluster
    ansible.builtin.shell:
      cmd: /bin/update-ca-trust


#  ____ ___ ____    _    ____  _     _____   ______        ___    ____
# |  _ \_ _/ ___|  / \  | __ )| |   | ____| / ___\ \      / / \  |  _ \
# | | | | |\___ \ / _ \ |  _ \| |   |  _|   \___ \\ \ /\ / / _ \ | |_) |
# | |_| | | ___) / ___ \| |_) | |___| |___   ___) |\ V  V / ___ \|  __/
# |____/___|____/_/   \_\____/|_____|_____| |____/  \_/\_/_/   \_\_|
#
- name: Disable swap since Kubernetes cannot work with swap enabled (1/2)
  ansible.builtin.shell: |
    swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Disable swap in /etc/fstab since Kubernetes can't work with swap enabled (2/2)
  replace:
    path: /etc/fstab
    regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
    replace: '#\1\2\3swap\4'
  when: ansible_swaptotal_mb > 0


#  ____ ___ ____    _    ____  _     _____   ____  _____ _     ___ _   _ _   ___  __
# |  _ \_ _/ ___|  / \  | __ )| |   | ____| / ___|| ____| |   |_ _| \ | | | | \ \/ /
# | | | | |\___ \ / _ \ |  _ \| |   |  _|   \___ \|  _| | |    | ||  \| | | | |\  /
# | |_| | | ___) / ___ \| |_) | |___| |___   ___) | |___| |___ | || |\  | |_| |/  \
# |____/___|____/_/   \_\____/|_____|_____| |____/|_____|_____|___|_| \_|\___//_/\_\
#
- name: Disable SELinux
  selinux:
    state: disabled


#  ____  _   _ ____  ____   ___  ____ _____ ___ _   _  ____   ____   _    ____ _  __    _    ____ _____ ____
# / ___|| | | |  _ \|  _ \ / _ \|  _ \_   _|_ _| \ | |/ ___| |  _ \ / \  / ___| |/ /   / \  / ___| ____/ ___|
# \___ \| | | | |_) | |_) | | | | |_) || |  | ||  \| | |  _  | |_) / _ \| |   | ' /   / _ \| |  _|  _| \___ \
#  ___) | |_| |  __/|  __/| |_| |  _ < | |  | || |\  | |_| | |  __/ ___ \ |___| . \  / ___ \ |_| | |___ ___) |
# |____/ \___/|_|   |_|    \___/|_| \_\|_| |___|_| \_|\____| |_| /_/   \_\____|_|\_\/_/   \_\____|_____|____/
#
- name: Install the arptables package
  ansible.builtin.yum:
    name: arptables
    state: present

- name: Install the ebtables package
  ansible.builtin.yum:
    name: ebtables
    state: present

- name: Install the jq package
  ansible.builtin.yum:
    name: jq
    state: present


#  _  _______ ____  _   _ _____ _       __  __  ___  ____  _   _ _     _____ ____
# | |/ / ____|  _ \| \ | | ____| |     |  \/  |/ _ \|  _ \| | | | |   | ____/ ___|
# | ' /|  _| | |_) |  \| |  _| | |     | |\/| | | | | | | | | | | |   |  _| \___ \
# | . \| |___|  _ <| |\  | |___| |___  | |  | | |_| | |_| | |_| | |___| |___ ___) |
# |_|\_\_____|_| \_\_| \_|_____|_____| |_|  |_|\___/|____/ \___/|_____|_____|____/
#
- name: Add the overlay module
  community.general.modprobe:
    name: overlay
    state: present

- name: Add the br_netfilter module
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Ensure the overlay module is persistent
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/modules.conf
    line: overlay
    create: yes
    owner: root
    group: root
    mode: '0644'

- name: Ensure the br_netfilter module is persistent
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/modules.conf
    line: br_netfilter
    create: yes
    owner: root
    group: root
    mode: '0644'


#   ____ ___  _   _ _____  _    ___ _   _ _____ ____  ____
#  / ___/ _ \| \ | |_   _|/ \  |_ _| \ | | ____|  _ \|  _ \
# | |  | | | |  \| | | | / _ \  | ||  \| |  _| | |_) | | | |
# | |__| |_| | |\  | | |/ ___ \ | || |\  | |___|  _ <| |_| |
#  \____\___/|_| \_| |_/_/   \_\___|_| \_|_____|_| \_\____/
#
- name: Add the Docker CE YUM repo
  yum_repository:
    name: 'docker-ce-stable'
    description: "Docker CE Stable - $basearch"
    file: docker-ce
    baseurl: https://download.docker.com/linux/centos/{{ ansible_distribution_major_version }}/$basearch/stable/
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: Check whether the /etc/containerd/config.toml file exists
  stat:
    path: /etc/containerd/config.toml
  register: containerd_config_stat_result

- name: Install the containerd package
  ansible.builtin.yum:
    name:
    - containerd
    state: latest
  register: install_containerd_package_result

- name: Create the containerd configuration
  block:
  - name: Create the /etc/containerd directory if it does not exist
    ansible.builtin.file:
      path: /etc/containerd
      state: directory
      mode: '0755'
      owner: root
      group: root

  - name: Create the default containerd configuration
    ansible.builtin.shell:
      cmd: containerd config default > /etc/containerd/config.toml

  - name: Configure the systemd cgroup driver for containerd
    ansible.builtin.lineinfile:
      path: /etc/containerd/config.toml
      insertafter: '^          \[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options\]'
      line: '            SystemdCgroup = true'

  when: (containerd_config_stat_result.stat.exists == False)

- name: Restart the containerd service if required
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    enabled: yes
  when: (install_containerd_package_result.changed == True)

- name: Ensure that the containerd service is started
  ansible.builtin.systemd:
    name: containerd
    state: started
    enabled: yes


#  _  ___   _ ____  _____ ____  _   _ _____ _____ _____ ____    ____   _    ____ _  __    _    ____ _____ ____
# | |/ / | | | __ )| ____|  _ \| \ | | ____|_   _| ____/ ___|  |  _ \ / \  / ___| |/ /   / \  / ___| ____/ ___|
# | ' /| | | |  _ \|  _| | |_) |  \| |  _|   | | |  _| \___ \  | |_) / _ \| |   | ' /   / _ \| |  _|  _| \___ \
# | . \| |_| | |_) | |___|  _ <| |\  | |___  | | | |___ ___) | |  __/ ___ \ |___| . \  / ___ \ |_| | |___ ___) |
# |_|\_\\___/|____/|_____|_| \_\_| \_|_____| |_| |_____|____/  |_| /_/   \_\____|_|\_\/_/   \_\____|_____|____/
#
- name: Add the Kubernetes YUM repo
  yum_repository:
    name: Kubernetes
    description: Kubernetes YUM repo
    file: Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Retrieve the version of the installed kubectl package
  ansible.builtin.debug:
    msg: Found the installed kubectl package ({{ ansible_facts.packages['kubectl'][0].version }})
  when: ('kubectl' in ansible_facts.packages)

- name: Install the kubectl package
  block:
  - name: Install the kubectl package ({{ k8s_config.k8s_redhat_package_version }})
    ansible.builtin.yum:
      name: kubectl-{{k8s_config.k8s_redhat_package_version}}*
      state: present

  when: (('kubectl' not in ansible_facts.packages) or (ansible_facts.packages['kubectl'][0].version != k8s_config.k8s_redhat_package_version))

- name: Retrieve the version of the installed kubelet package
  ansible.builtin.debug:
    msg: Found the installed kubelet package ({{ ansible_facts.packages['kubelet'][0].version }})
  when: ('kubelet' in ansible_facts.packages)

- name: Install the kubelet package
  block:
  - name: Install the kubelet package ({{ k8s_config.k8s_redhat_package_version }})
    ansible.builtin.yum:
      name: kubelet-{{k8s_config.k8s_redhat_package_version}}*
      state: present

  when: (('kubelet' not in ansible_facts.packages) or (ansible_facts.packages['kubelet'][0].version != k8s_config.k8s_redhat_package_version))

- name: Retrieve the version of the installed kubeadm package
  ansible.builtin.debug:
    msg: Found the installed kubeadm package ({{ ansible_facts.packages['kubeadm'][0].version }})
  when: ('kubeadm' in ansible_facts.packages)

- name: Install the kubeadm package
  block:
  - name: Install the kubeadm package ({{ k8s_config.k8s_redhat_package_version }})
    ansible.builtin.yum:
      name: kubeadm-{{k8s_config.k8s_redhat_package_version}}*
      state: present

  when: (('kubeadm' not in ansible_facts.packages) or (ansible_facts.packages['kubeadm'][0].version != k8s_config.k8s_redhat_package_version))


#  _  ___   _ ____  _____ ____  _   _ _____ _____ _____ ____    ______   ______   ____ _____ _       ____  _____ _____ _____ ___ _   _  ____ ____
# | |/ / | | | __ )| ____|  _ \| \ | | ____|_   _| ____/ ___|  / ___\ \ / / ___| / ___|_   _| |     / ___|| ____|_   _|_   _|_ _| \ | |/ ___/ ___|
# | ' /| | | |  _ \|  _| | |_) |  \| |  _|   | | |  _| \___ \  \___ \\ V /\___ \| |     | | | |     \___ \|  _|   | |   | |  | ||  \| | |  _\___ \
# | . \| |_| | |_) | |___|  _ <| |\  | |___  | | | |___ ___) |  ___) || |  ___) | |___  | | | |___   ___) | |___  | |   | |  | || |\  | |_| |___) |
# |_|\_\\___/|____/|_____|_| \_\_| \_|_____| |_| |_____|____/  |____/ |_| |____/ \____| |_| |_____| |____/|_____| |_|   |_| |___|_| \_|\____|____/
#
- name: Check whether the /etc/sysctl.d/kubernetes.conf file exists
  stat:
    path: /etc/sysctl.d/kubernetes.conf
  register: kubernetes_sysctl_stat_result

- name: Apply the Kubernetes sysctl configuration
  block:
  - name: Create the /etc/sysctl.d/kubernetes.conf file
    ansible.builtin.template:
      src: kubernetes.conf.j2
      dest: /etc/sysctl.d/kubernetes.conf

  - name: Reload the kernel parameter configuration files
    ansible.builtin.command:
      cmd: /sbin/sysctl --system

  when: (kubernetes_sysctl_stat_result.stat.exists == False)



