---
# file: roles/k8s_common/tasks/redhat.yaml

- debug:
    msg: Applying the RedHat-specific Kubernetes common configuration

- name: Collect the system service facts
  service_facts:
  register: services_state

- name: Collect the package facts
  package_facts:
    manager: auto


#   ____ _____ ____ _____ ___ _____ ___ ____    _  _____ _____      _   _   _ _____ _   _  ___  ____  ___ _____ ___ _____ ____
#  / ___| ____|  _ \_   _|_ _|  ___|_ _/ ___|  / \|_   _| ____|    / \ | | | |_   _| | | |/ _ \|  _ \|_ _|_   _|_ _| ____/ ___|
# | |   |  _| | |_) || |  | || |_   | | |     / _ \ | | |  _|     / _ \| | | | | | | |_| | | | | |_) || |  | |  | ||  _| \___ \
# | |___| |___|  _ < | |  | ||  _|  | | |___ / ___ \| | | |___   / ___ \ |_| | | | |  _  | |_| |  _ < | |  | |  | || |___ ___) |
#  \____|_____|_| \_\|_| |___|_|   |___\____/_/   \_\_| |_____| /_/   \_\___/  |_| |_| |_|\___/|_| \_\___| |_| |___|_____|____/
#
- name: Install the root CA, Kubernetes intermediate CA and Kubernetes etcd intermediate CA certificates
  block:
  - name: Copy the root CA certificate for the Kubernetes cluster to the /etc/pki/ca-trust/source/anchors directory
    copy:
      src: '{{ pki_root }}/{{ role_name }}/{{ k8s_config.cluster_name }}/ca.crt'
      dest: '/etc/pki/ca-trust/source/anchors/ca.crt'

  - name: Copy the Kubernetes intermediate CA certificate for the Kubernetes cluster to the /etc/pki/ca-trust/source/anchors directory
    copy:
      src: "{{ pki_root }}/{{ role_name }}/{{ k8s_config.cluster_name }}/k8s-ca-{{ k8s_config.cluster_name.replace('_', '-') }}.crt"
      dest: "/etc/pki/ca-trust/source/anchors/k8s-ca-{{ k8s_config.cluster_name.replace('_', '-') }}.crt"

  - name: Update the certificate index to install the CA certificate for the Kubernetes cluster
    shell:
      cmd: /bin/update-ca-trust


#  ____ ___ ____    _    ____  _     _____   ______        ___    ____
# |  _ \_ _/ ___|  / \  | __ )| |   | ____| / ___\ \      / / \  |  _ \
# | | | | |\___ \ / _ \ |  _ \| |   |  _|   \___ \\ \ /\ / / _ \ | |_) |
# | |_| | | ___) / ___ \| |_) | |___| |___   ___) |\ V  V / ___ \|  __/
# |____/___|____/_/   \_\____/|_____|_____| |____/  \_/\_/_/   \_\_|
#
- name: Disable swap since Kubernetes cannot work with swap enabled (1/2)
  shell: |
    swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Disable swap in /etc/fstab since Kubernetes can't work with swap enabled (2/2)
  replace:
    path: /etc/fstab
    regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
    replace: '#\1\2\3swap\4'
  when: ansible_swaptotal_mb > 0


#  ____ ___ ____    _    ____  _     _____   ____  _____ _     ___ _   _ _   ___  __
# |  _ \_ _/ ___|  / \  | __ )| |   | ____| / ___|| ____| |   |_ _| \ | | | | \ \/ /
# | | | | |\___ \ / _ \ |  _ \| |   |  _|   \___ \|  _| | |    | ||  \| | | | |\  /
# | |_| | | ___) / ___ \| |_) | |___| |___   ___) | |___| |___ | || |\  | |_| |/  \
# |____/___|____/_/   \_\____/|_____|_____| |____/|_____|_____|___|_| \_|\___//_/\_\
#
- name: Disable SELinux
  selinux:
    state: disabled


#  _____ ___ ____  _______        ___    _     _       ____   ___  ____ _____ ____
# |  ___|_ _|  _ \| ____\ \      / / \  | |   | |     |  _ \ / _ \|  _ \_   _/ ___|
# | |_   | || |_) |  _|  \ \ /\ / / _ \ | |   | |     | |_) | | | | |_) || | \___ \
# |  _|  | ||  _ <| |___  \ V  V / ___ \| |___| |___  |  __/| |_| |  _ < | |  ___) |
# |_|   |___|_| \_\_____|  \_/\_/_/   \_\_____|_____| |_|    \___/|_| \_\|_| |____/
#
- name: Allow all hosts access to tcp port 22 (SSH)
  firewalld:
    port: 22/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: Allow all hosts access to tcp port 2379
  firewalld:
    port: 2379/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: Allow all hosts access to tcp port 2380
  firewalld:
    port: 2380/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: Allow all hosts access to tcp port 4149
  firewalld:
    port: 4149/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: Allow all hosts access to tcp port 6443 (Kubernetes API)
  firewalld:
    port: 6443/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: Allow all hosts access to tcp port 4149 (Default cAdvisor port used to query container metrics)
  firewalld:
    port: 4149/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: Allow all hosts access to tcp port 9099 (Health check server for Calico)
  firewalld:
    port: 9099/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: Allow all hosts access to tcp port 9100 (Prometheus Node Exporter)
  firewalld:
    port: 9100/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: Allow all hosts access to tcp port 10256 (Health check server for Kube Proxy)
  firewalld:
    port: 10256/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: Allow all hosts access to tcp port 10257 (Kube Controller Manager Port)
  firewalld:
    port: 10257/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: Allow all hosts access to tcp port 10250 (API which allows full node access)
  firewalld:
    port: 10250/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: Allow all hosts access to tcp port 10255 (Unauthenticated read-only port, allowing access to node state)
  firewalld:
    port: 10255/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: Allow all hosts access to tcp ports 30000-32767 (Nodeport)
  firewalld:
    port: 30000-32767/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: Open TCP and UDP pprts for the Weave CNI provider
  block:
  - name: Allow all hosts access to tcp port 6783 for the Weave CNI provider
    firewalld:
      port: 6783/tcp
      permanent: yes
      state: enabled
      immediate: yes

  - name: Allow all access to udp port 6783 for the Weave CNI provider
    firewalld:
      port: 6783/udp
      permanent: yes
      state: enabled
      immediate: yes

  - name: Allow all access to udp port 6784 for the Weave CNI provider
    firewalld:
      port: 6784/udp
      permanent: yes
      state: enabled
      immediate: yes

  when: (k8s_config.cni_provider == 'weave')


#  ____  _   _ ____  ____   ___  ____ _____ ___ _   _  ____   ____   _    ____ _  __    _    ____ _____ ____
# / ___|| | | |  _ \|  _ \ / _ \|  _ \_   _|_ _| \ | |/ ___| |  _ \ / \  / ___| |/ /   / \  / ___| ____/ ___|
# \___ \| | | | |_) | |_) | | | | |_) || |  | ||  \| | |  _  | |_) / _ \| |   | ' /   / _ \| |  _|  _| \___ \
#  ___) | |_| |  __/|  __/| |_| |  _ < | |  | || |\  | |_| | |  __/ ___ \ |___| . \  / ___ \ |_| | |___ ___) |
# |____/ \___/|_|   |_|    \___/|_| \_\|_| |___|_| \_|\____| |_| /_/   \_\____|_|\_\/_/   \_\____|_____|____/
#
- name: Install the arptables package
  yum:
    name: arptables
    state: present

- name: Install the ebtables package
  yum:
    name: ebtables
    state: present

- name: Install the jq package
  yum:
    name: jq
    state: present


#  _  ___   _ ____  _____ ____  _   _ _____ _____ _____ ____    ____   _    ____ _  __    _    ____ _____ ____
# | |/ / | | | __ )| ____|  _ \| \ | | ____|_   _| ____/ ___|  |  _ \ / \  / ___| |/ /   / \  / ___| ____/ ___|
# | ' /| | | |  _ \|  _| | |_) |  \| |  _|   | | |  _| \___ \  | |_) / _ \| |   | ' /   / _ \| |  _|  _| \___ \
# | . \| |_| | |_) | |___|  _ <| |\  | |___  | | | |___ ___) | |  __/ ___ \ |___| . \  / ___ \ |_| | |___ ___) |
# |_|\_\\___/|____/|_____|_| \_\_| \_|_____| |_| |_____|____/  |_| /_/   \_\____|_|\_\/_/   \_\____|_____|____/
#
- name: Add the Kubernetes YUM repo
  yum_repository:
    name: Kubernetes
    description: Kubernetes YUM repo
    file: Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Retrieve the version of the installed kubectl package
  debug:
    msg: Found the installed kubectl package ({{ ansible_facts.packages['kubectl'][0].version }})
  when: ('kubectl' in ansible_facts.packages)

- name: Install the kubectl package
  block:
  - name: Install the kubectl package ({{ k8s_config.centos_package_version }})
    yum:
      name: kubectl-{{k8s_config.centos_package_version}}*
      state: present

  when: (('kubectl' not in ansible_facts.packages) or (ansible_facts.packages['kubectl'][0].version != k8s_config.centos_package_version))

- name: Retrieve the version of the installed kubelet package
  debug:
    msg: Found the installed kubelet package ({{ ansible_facts.packages['kubelet'][0].version }})
  when: ('kubelet' in ansible_facts.packages)

- name: Install the kubelet package
  block:
  - name: Install the kubelet package ({{ k8s_config.centos_package_version }})
    yum:
      name: kubelet-{{k8s_config.centos_package_version}}*
      state: present

  when: (('kubelet' not in ansible_facts.packages) or (ansible_facts.packages['kubelet'][0].version != k8s_config.centos_package_version))

- name: Retrieve the version of the installed kubeadm package
  debug:
    msg: Found the installed kubeadm package ({{ ansible_facts.packages['kubeadm'][0].version }})
  when: ('kubeadm' in ansible_facts.packages)

- name: Install the kubeadm package
  block:
  - name: Install the kubeadm package ({{ k8s_config.centos_package_version }})
    yum:
      name: kubeadm-{{k8s_config.centos_package_version}}*
      state: present

  when: (('kubeadm' not in ansible_facts.packages) or (ansible_facts.packages['kubeadm'][0].version != k8s_config.centos_package_version))


#  _  ___   _ ____  _____ ____  _   _ _____ _____ _____ ____    ______   ______   ____ _____ _       ____  _____ _____ _____ ___ _   _  ____ ____
# | |/ / | | | __ )| ____|  _ \| \ | | ____|_   _| ____/ ___|  / ___\ \ / / ___| / ___|_   _| |     / ___|| ____|_   _|_   _|_ _| \ | |/ ___/ ___|
# | ' /| | | |  _ \|  _| | |_) |  \| |  _|   | | |  _| \___ \  \___ \\ V /\___ \| |     | | | |     \___ \|  _|   | |   | |  | ||  \| | |  _\___ \
# | . \| |_| | |_) | |___|  _ <| |\  | |___  | | | |___ ___) |  ___) || |  ___) | |___  | | | |___   ___) | |___  | |   | |  | || |\  | |_| |___) |
# |_|\_\\___/|____/|_____|_| \_\_| \_|_____| |_| |_____|____/  |____/ |_| |____/ \____| |_| |_____| |____/|_____| |_|   |_| |___|_| \_|\____|____/
#
- name: Check whether the /etc/sysctl.d/kubernetes.conf file exists
  stat:
    path: /etc/sysctl.d/kubernetes.conf
  register: kubernetes_sysctl_stat_result

- name: Apply the Kubernetes sysctl configuration
  block:
  - name: Create the /etc/sysctl.d/kubernetes.conf file
    template:
      src: kubernetes.conf.j2
      dest: /etc/sysctl.d/kubernetes.conf

  - name: Reload the kernel parameter configuration files
    command:
      cmd: /sbin/sysctl --system

  when: (kubernetes_sysctl_stat_result.stat.exists == False)






