---
#file: roles/kafka_server/vars/main.yaml

kafka_server_etc_directory: /etc/kafka-server
kafka_server_log_directory: /var/log/kafka-server
kafka_server_data_directory: /data/kafka-server

kafka_server_user_id: 350
kafka_server_group_id: 350




#
#
#
#
#zookeeper_client_port: 2181
#zookeeper_cluster_ports: "2888:3888"
#
#zookeeper_hosts: "{{groups['kafka_zookeeper']}}"
#
#zookeeper_enable_admin_server: 'false'
#zookeeper_admin_server_port: 8080
#
#zookeeper_max_client_connections: 60
#
### Rolling file appender setttings
#zookeeper_rolling_log_file_max_size: 10MB
#zookeeper_max_rolling_log_file_count: 10
#
#zookeeper_tick_time: 2000
#
#zookeeper_init_limit: 5
#
#zookeeper_sync_limit: 2
#
#
#zookeeper_autopurge_purge_interval: 1
#zookeeper_autopurge_snap_retain_count: 10
#
#



