---
#file: roles/kafka_server/vars/main.yaml

kafka_secure_broker_port: 9093

kafka_etc_directory: /etc/kafka
kafka_log_directory: /var/log/kafka
kafka_data_directory: /data/kafka

kafka_user_id: 330
kafka_group_id: 330

kafka_server_user_username: kafka

kafka_server_zookeeper_secure_client_port: 2182
kafka_server_zookeeper_user_username: kafka

kafka_admin_user_username: admin
