---
#file: roles/kafka_server/defaults/main.yaml

kafka_defaults:
  kafka_server:
    secure_broker_port: 9093
    etc_directory: /etc/kafka
    log_directory: /var/log/kafka
    data_directory: /data/kafka

    user: kafka
    user_id: 330
    group: kafka
    group_id: 330

    zookeeper:
      secure_client_port: 2182
      username: kafka

    users:
      broker:
        username: kafka
      admin:
        username: admin
      mirrormaker:
        username: mirrormaker

    prometheus_jmx_exporter:
      enabled: true
      port: 9131

kafka_config: "{{ kafka_defaults | combine(kafka | default({})) }}"
