---
#file: roles/kafka_server/vars/main.yaml

kafka_secure_broker_port: 9093

kafka_server_etc_directory: /etc/kafka
kafka_server_log_directory: /var/log/kafka
kafka_server_data_directory: /data/kafka

kafka_server_user: kafka
kafka_server_user_id: 330
kafka_server_group: kafka
kafka_server_group_id: 330

kafka_server_zookeeper_secure_client_port: 2182
kafka_server_zookeeper_user_username: kafka

kafka_server_user_username: kafka
kafka_admin_user_username: admin
kafka_mirrormaker_user_username: mirrormaker

prometheus_jmx_exporter_enabled: true
prometheus_jmx_exporter_version: 0.13.0
prometheus_kafka_server_jmx_exporter_port: 9131



