---
# file: roles/k8s_load_balancer/tasks/centos.yaml

- debug:
    msg: Applying the CentOS-specific Kubernetes load balancer configuration

- name: Install the haproxy package
  yum: name=haproxy state=latest

- name: Configure the haproxy
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg

- name: Restart the haproxy service
  systemd:
    name: haproxy.service
    state: restarted
    enabled: yes
