---
# file: roles/k8s_load_balancer/tasks/redhat.yaml

- ansible.builtin.debug:
    msg: Applying the RedHat-specific Kubernetes load balancer configuration

- name: Create the /run/haproxy directory
  ansible.builtin.file:
    path: /run/haproxy
    owner: 'root'
    group: 'root'
    mode: 0755
    state: directory

- name: Install the haproxy package
  ansible.builtin.yum:
    name: haproxy
    state: latest

- name: Configure the haproxy
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: Set haproxy_connect_any selinux flag on and keep it persistent across reboots
  ansible.posix.seboolean:
    name: haproxy_connect_any
    state: yes
    persistent: yes

- name: Restart the haproxy service
  ansible.builtin.systemd:
    name: haproxy
    state: restarted
    enabled: yes

- name: Ensure that the haproxy service is started
  ansible.builtin.systemd:
    name: haproxy
    state: started
    enabled: yes
