---
# file: roles/k8s_load_balancer/tasks/ubuntu.yaml

- debug:
    msg: Applying the Ubuntu-specific Kubernetes load balancer configuration

- name: Update the Apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install the haproxy package
  apt: name=haproxy state=latest

- name: Configure the haproxy
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg

- name: Restart the haproxy service
  systemd:
    name: haproxy.service
    state: restarted
    enabled: yes

- name: Ensure that the haproxy service is started
  systemd:
    name: haproxy.service
    state: started
    enabled: yes
