---
#file: roles/confluent_kafka_server/defaults/main.yaml

confluent_defaults:
  kafka_server:
    secure_broker_port: 9093
    etc_directory: /etc/kafka
    log_directory: /var/log/kafka
    data_directory: /data/kafka

    user: cp-kafka
    user_id: 311
    group: cp-kafka
    group_id: 311

    zookeeper:
      secure_client_port: 2182
      username: kafka

    users:
      broker:
        username: kafka
      admin:
        username: admin
      mirrormaker:
        username: mirrormaker
      schema_registry:
        username: schema-registry

    prometheus_jmx_exporter:
      enabled: true
      port: 9131

confluent_config: "{{ confluent_defaults | combine(confluent | default({})) }}"
