---
# file: roles/confluent_schema_registry/tasks/main.yaml

- name: Create the /var/tmp/ansible/confluent/{{ role_name }} directory
  file:
    path: '/var/tmp/ansible/confluent/{{ role_name }}'
    owner: 'root'
    group: 'root'
    mode: '0700'
    state: directory

- fail:
    msg: 'No confluent.clusters configuration specified'
  when: ((confluent is not defined) or (confluent == None) or (confluent.clusters is not defined) or (confluent.clusters == None))

- set_fact:
    confluent_cluster_name: ''

- set_fact:
    confluent_cluster_name: '{{ item }}'
  when: (('schema_registry_hosts' in confluent_config.clusters[item]) and (inventory_hostname in confluent_config.clusters[item].schema_registry_hosts))
  loop: '{{ confluent_config.clusters | flatten(1) }}'

- fail:
    msg: "The Schema Registry host {{ inventory_hostname }} is not associated with a Confluent cluster"
  when: ((confluent_cluster_name is not defined) or (confluent_cluster_name == None) or (confluent_cluster_name == ''))

- debug:
    msg: 'Cluster Name: {{ confluent_cluster_name }}'

- set_fact:
    schema_registry_hosts: "{{ confluent_config.clusters[confluent_cluster_name].schema_registry_hosts | intersect(groups['confluent_schema_registry']|default([])) }}"

- debug:
    msg: 'Schema Registry hosts: {{ schema_registry_hosts }}'

- set_fact:
    kafka_server_hosts: "{{ confluent_config.clusters[confluent_cluster_name].kafka_server_hosts | intersect(groups['confluent_kafka_server']|default([])) }}"

- debug:
    msg: 'Kafka Server hosts: {{ kafka_server_hosts }}'


#   ___  ____       ____  ____  _____ ____ ___ _____ ___ ____
#  / _ \/ ___|     / ___||  _ \| ____/ ___|_ _|  ___|_ _/ ___|
# | | | \___ \ ____\___ \| |_) |  _|| |    | || |_   | | |
# | |_| |___) |_____|__) |  __/| |__| |___ | ||  _|  | | |___
#  \___/|____/     |____/|_|   |_____\____|___|_|   |___\____|
#
- include_tasks: ubuntu.yaml
  when: ansible_distribution == 'Ubuntu'
  tags:
  - unbound

- include_tasks: redhat.yaml
  when: ansible_os_family == 'RedHat'
  tags:
  - unbound


#   ____ ___  _   _ _____ _    _   _ _____ _   _ _____   ____   ____ _   _ _____ __  __    _      ____  _____ ____ ___ ____ _____ ______   __
#  / ___/ _ \| \ | |  ___| |  | | | | ____| \ | |_   _| / ___| / ___| | | | ____|  \/  |  / \    |  _ \| ____/ ___|_ _/ ___|_   _|  _ \ \ / /
# | |  | | | |  \| | |_  | |  | | | |  _| |  \| | | |   \___ \| |   | |_| |  _| | |\/| | / _ \   | |_) |  _|| |  _ | |\___ \ | | | |_) \ V /
# | |__| |_| | |\  |  _| | |__| |_| | |___| |\  | | |    ___) | |___|  _  | |___| |  | |/ ___ \  |  _ <| |__| |_| || | ___) || | |  _ < | |
#  \____\___/|_| \_|_|   |_____\___/|_____|_| \_| |_|   |____/ \____|_| |_|_____|_|  |_/_/   \_\ |_| \_\_____\____|___|____/ |_| |_| \_\|_|
#
- name: Create the credentials directory
  local_action: file path="{{ credentials_root }}/confluent/{{ confluent_cluster_name }}" state="directory"
  become: false

- name: Add the {{ confluent_config.schema_registry.group }} group
  group:
    name: '{{ confluent_config.schema_registry.group }}'
    gid: '{{ confluent_config.schema_registry.group_id }}'
    state: present

- name: Add the {{ confluent_config.schema_registry.user }} user
  user:
    name: '{{ confluent_config.schema_registry.user }}'
    uid: '{{ confluent_config.schema_registry.user_id }}'
    group: '{{ confluent_config.schema_registry.group }}'
    create_home: yes
    state: present

- name: Create the {{ confluent_config.schema_registry.etc_directory }} directory
  file:
    path: '{{ confluent_config.schema_registry.etc_directory }}'
    owner: '{{ confluent_config.schema_registry.user }}'
    group: '{{ confluent_config.schema_registry.group }}'
    mode: '0550'
    state: directory

- name: Create the {{ confluent_config.schema_registry.etc_directory }}/conf directory
  file:
    path: '{{ confluent_config.schema_registry.etc_directory }}/conf'
    owner: '{{ confluent_config.schema_registry.user }}'
    group: '{{ confluent_config.schema_registry.group }}'
    mode: '0550'
    state: directory

- name: Setup the Schema Registry keystore and CA truststore
  block:
  - name: Create the {{ confluent_config.schema_registry.etc_directory }}/pki directory
    file:
      path: '{{ confluent_config.schema_registry.etc_directory }}/pki'
      owner: '{{ confluent_config.schema_registry.user }}'
      group: '{{ confluent_config.schema_registry.group }}'
      mode: '0550'
      state: directory

  - name: Copy the Schema Registry CA certificate
    copy:
      src: '{{ pki_root }}/{{ role_name }}/{{ confluent_cluster_name }}/ca.crt'
      dest: '/var/tmp/ansible/confluent/{{ role_name }}/ca.crt'
    register: ca_certificate_copy_result

  - name: Copy the Schema Registry private key ({{ inventory_hostname_short }}.key)
    copy:
      src: '{{ pki_root }}/{{ role_name }}/{{ confluent_cluster_name }}/{{ inventory_hostname_short }}.key'
      dest: '/var/tmp/ansible/confluent/{{ role_name }}/{{ inventory_hostname_short }}.key'
    register: schema_registry_private_key_copy_result

  - name: Copy the Schema Registry certificate ({{ inventory_hostname_short }}.crt)
    copy:
      src: '{{ pki_root }}/{{ role_name }}/{{ confluent_cluster_name }}/{{ inventory_hostname_short }}.crt'
      dest: '/var/tmp/ansible/confluent/{{ role_name }}/{{ inventory_hostname_short }}.crt'
    register: schema_registry_certificate_copy_result

  - name: Generate or retrieve the password for the Schema Registry keystore
    set_fact:
      schema_registry_keystore_password: "{{ lookup('password', '{{ credentials_root }}/confluent/{{ confluent_cluster_name }}/{{ inventory_hostname_short }}-keystore-password chars=ascii_letters,digits length=16') }}"

  - name: Generate or retrieve the password for the CA truststore
    set_fact:
      ca_truststore_password: "{{ lookup('password', '{{ credentials_root }}/confluent/{{ confluent_cluster_name }}/ca-truststore-password chars=ascii_letters,digits length=16') }}"

  - name: Generate the Schema Registry keystore and CA truststore
    block:
    - name: Generate the Schema Registry PKCS12 keystore
      openssl_pkcs12:
        action: export
        path: '{{ confluent_config.schema_registry.etc_directory }}/pki/{{ inventory_hostname_short }}.p12'
        friendly_name: "{{ inventory_hostname_short }}"
        privatekey_path: '/var/tmp/ansible/confluent/{{ role_name }}/{{ inventory_hostname_short }}.key'
        certificate_path: '/var/tmp/ansible/confluent/{{ role_name }}/{{ inventory_hostname_short }}.crt'
        passphrase: '{{ schema_registry_keystore_password }}'
        owner: '{{ confluent_config.schema_registry.user }}'
        group: '{{ confluent_config.schema_registry.group }}'
        mode: '0440'
        state: present

    - name: Remove the Scheme Registry CA PKCS12 truststore if it already exists
      file:
        path: '{{ confluent_config.schema_registry.etc_directory }}/pki/ca.p12'
        state: absent

    - name: Generate the Schema Registry CA PKCS12 truststore
      shell:
        cmd: keytool -importcert -noprompt -trustcacerts -alias "ca" -file /var/tmp/ansible/confluent/{{ role_name }}/ca.crt -keystore '{{ confluent_config.schema_registry.etc_directory }}/pki/ca.p12' -storetype PKCS12 -storepass '{{ ca_truststore_password }}'

    - name: Set the permissions for the Schema Registry CA PKCS12 truststore
      file:
        path: '{{ confluent_config.schema_registry.etc_directory }}/pki/ca.p12'
        owner: '{{ confluent_config.schema_registry.user }}'
        group: '{{ confluent_config.schema_registry.group }}'
        mode: '0440'

    when: ((ca_certificate_copy_result.changed == True) or (schema_registry_private_key_copy_result.changed == True) or (schema_registry_certificate_copy_result.changed == True))

- name: Create the {{ confluent_config.schema_registry.log_directory }} directory
  file:
    path: '{{ confluent_config.schema_registry.log_directory }}'
    owner: '{{ confluent_config.schema_registry.user }}'
    group: '{{ confluent_config.schema_registry.group }}'
    mode: '0750'
    state: directory

# NOTE: This is the password Schema Registry uses to connect to the Kafka cluster
- name: Generate or retrieve the password for the Schema Registry user
  set_fact:
    kafka_server_schema_registry_user_password: "{{ lookup('password', '{{ credentials_root }}/confluent/{{ confluent_cluster_name }}/kafka-server-schema-registry-user-password chars=ascii_letters,digits length=16') }}"

- name: Create the Schema Registry configuration file
  template:
    src: schema-registry.properties.j2
    dest: '{{ confluent_config.schema_registry.etc_directory }}/conf/schema-registry.properties'
    owner: '{{ confluent_config.schema_registry.user }}'
    group: '{{ confluent_config.schema_registry.group }}'
    mode: '0440'
  register: schema_registry_configuration_template_result

- name: Configure the schema-registry service
  template:
    src: schema-registry.service.j2
    dest: /lib/systemd/system/schema-registry.service
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: schema_registry_service_file_template_result

- name: Restart the schema-registry service if required
  systemd:
    name: schema-registry.service
    state: restarted
    enabled: yes
    daemon_reload: yes
  when: ((ca_certificate_copy_result.changed == True) or (schema_registry_private_key_copy_result.changed == True) or (schema_registry_certificate_copy_result.changed == True) or (schema_registry_configuration_template_result.changed == True) or (schema_registry_service_file_template_result.changed == True))

- name: Ensure that the schema-registry service is started
  systemd:
    name: schema-registry.service
    state: started
    enabled: yes
