---
# file: roles/k8s_monitoring/tasks/main.yaml

k8s_defaults:
  monitoring:
    enabled: false

    # For latest version of Helm chart see: https://helm.elastic.co
    elasticsearch:
      cluster_type: standalone
      enabled: true
      helm_chart_version: '7.17.3'
      persistent_volume_size: 10Gi
      persistent_volume_storage_class_name: default-local-storage

    # For latest version of Helm chart see: https://github.com/grafana/helm-charts/blob/main/charts/grafana/Chart.yaml
    grafana:
      enabled: false
      helm_chart_version: '6.43.5'

    # For latest version of Helm chart see: https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/Chart.yaml
    jaeger:
      enabled: false
      helm_chart_version: '0.64.1'

    # For latest version of Helm chart see: https://helm.elastic.co
    kibana:
      enabled: false
      helm_chart_version: '7.17.3'

    # For latest version of Helm chart see: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/Chart.yaml
    prometheus:
      enabled: false
      helm_chart_version: '15.18.0'

      alert_manager:
        persistent_volume_storage_class_name: default-local-storage
        persistent_volume_size: 2Gi

      server:
        persistent_volume_storage_class_name: default-local-storage
        persistent_volume_size: 10Gi

k8s_config: "{{ k8s_defaults | combine(k8s | default({}), recursive=True) }}"

