---
# file: roles/k8s_monitoring/tasks/main.yaml

pki_root: ../../../pki

k8s_defaults:
  monitoring:
    enabled: false

    elasticsearch:
      cluster_type: standalone
      enabled: true
      helm_chart_version: 7.9.2
      persistent_volume_size: 10Gi
      persistent_volume_storage_class_name: default-local-storage

    grafana:
      enabled: true
      helm_chart_version: 5.7.9

    jaeger:
      enabled: true
      helm_chart_version: 0.39.0

    kibana:
      enabled: true
      helm_chart_version: 7.9.2

    prometheus:
      enabled: true
      helm_chart_version: 11.16.2

      alert_manager:
        persistent_volume_storage_class_name: default-local-storage
        persistent_volume_size: 2Gi

      server:
        persistent_volume_storage_class_name: default-local-storage
        persistent_volume_size: 10Gi

k8s_config: "{{ k8s_defaults | combine(k8s | default({}), recursive=True) }}"
