---
# file: roles/k8s_monitoring/tasks/main.yaml

k8s_defaults:
  monitoring:
    enabled: false

    elasticsearch:
      cluster_type: standalone
      enabled: true
      helm_chart_version: 7.8.0
      persistent_volume_size: 10Gi
      persistent_volume_storage_class_name: default-local-storage

    grafana:
      enabled: true
      helm_chart_version: 5.4.1

    jaeger:
      enabled: true
      helm_chart_version: 0.33.0

    kibana:
      enabled: true
      helm_chart_version: 7.8.0

    prometheus:
      enabled: true
      helm_chart_version: 11.7.0

      alert_manager:
        persistent_volume_storage_class_name: default-local-storage
        persistent_volume_size: 2Gi

      server:
        persistent_volume_storage_class_name: default-local-storage
        persistent_volume_size: 10Gi

k8s_config: "{{ k8s_defaults | combine(k8s | default({}), recursive=True) }}"
