{
 "title": "Kubernetes Deployments Dashboard",
 "description": "Kubernetes dashboard for following up deployments: CPU, Memory, Network, Desired Replicas, Available Replicas, Observer Generation, Metadata Generation, Replicas",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "deployment",
    "label": "Deployments",
    "query": "label_values(kube_deployment_metadata_generation{namespace=~\"$namespace\"}, deployment)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\", created_by_name=~\"$deployment-\\\\w{5,10}\"}, pod)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(kube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}, container)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_usage_bytes{pod=~\"$pod\", container=~\"$container\", container!=\"POD\", container!=\"\"})",
     "legendFormat": "Current"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests_memory_bytes{pod=~\"$pod\", container=~\"$container\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "sum (kube_pod_container_resource_limits_memory_bytes{pod=~\"$pod\", container=~\"$container\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{image!=\"\",container!=\"POD\",pod=~\"$pod\", container=~\"$container\"}[5m]))",
     "legendFormat": "Current"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{pod=~\"$pod\", container=~\"$container\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{pod=~\"$pod\", container=~\"$container\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_network_receive_bytes_total{pod=~\"$pod\"}[5m]))",
     "legendFormat": "Network I/O"
    }
   ]
  }
 ]
}