---
# file: roles/k8s_istio/meta/main.yaml

galaxy_info:
  author: Marcus Portmann
  description: Ansible Kubernetes Istio Role
  company: http://mmp.guru
  license: Apache 2
  min_ansible_version: 2.9
  platforms:
  - name: EL
    versions:
     - 7
  - name: Ubuntu
    versions:
      - breezy
      - focal
  categories:
  - platform

dependencies:
  - role: common
