---
# file: roles/kafka_common/defaults/main.yaml

# NOTE: The Kafka version is specified here and in the hierarchical configuration 
#       below because the hierarchical configuration is not inherited by the other
#       Kafka roles. The two values MUST be kept in sync.
kafka_version: '3.3.1'

kafka_defaults:
  package_version: '3.3.1'
  package_checksum: sha512:D14D9CC97D1702649B33378F38060C4A6220850A3D7182D1AF20E905CB98728E51F2AEEC63121F5773A389D6B66891B7508E5D23584DD1A4E424825E3D54E3E0

prometheus_jmx_exporter:
  enabled: true
  package_version: '0.17.2'

kafka_config: "{{ kafka_defaults | combine(kafka | default({}), recursive=True) }}"



