---
# file: roles/kafka_common/defaults/main.yaml

kafka_defaults:
  package_version: '2.8.0'
  package_checksum: sha512:3C49DCA1147A0A249DD88E089F40AF31A67B8207ED2D9E2294FA9A6D41F5ED0B006943CD60D8E30D7E69D760D398F299CAFCD68B6ED7BEDF9F93D1B7A9E8C487

prometheus_jmx_exporter:
  enabled: true
  package_version: '0.16.1'

kafka_config: "{{ kafka_defaults | combine(kafka | default({}), recursive=True) }}"



