---
#file: roles/kafka_common/defaults/main.yaml

kafka_defaults:
  package_version: 2.5.0
  package_checksum: sha512:A06F87C40CE9C58EF796D84F1014692E217B87DCA6047CB763E9570B9A74F104C78D1F337D2899A243980020690F1FA5BD5AD5CAC40F7A1C452F012ABA1D0709

prometheus_jmx_exporter:
  enabled: true
  package_version: 0.13.0

kafka_config: "{{ kafka_defaults | combine(kafka | default({})) }}"
