spring:
  kafka:
    bootstrap-servers: kafka-local-dev-01.local:9093
    ssl:
      protocol: TLS
      key-store-type: PKCS12
      key-store-location: file:pki/demo-producer.p12
      key-store-password: bdm1QKInU586etBN
      trust-store-type: PKCS12
      trust-store-location: file:pki/ca.p12
      trust-store-password: ulLdVI9hUP46gaQj
    security:
      protocol: SASL_SSL
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username='demo-producer' password='jsi9zxp28syOTQf2';
        mechanism: SCRAM-SHA-256
      linger:
        ms: 100

---
spring:
  profiles: kafka-dc1
  kafka:
    bootstrap-servers: kafka-local-dev-01.local:9093

---
spring:
  profiles: kafka-dc2
  kafka:
    bootstrap-servers: kafka-local-dev-02.local:9093

---
spring:
  profiles: confluent-dc1
  kafka:
    bootstrap-servers: confluent-local-dev-01.local:9093

---
spring:
  profiles: confluent-dc2
  kafka:
    bootstrap-servers: confluent-local-dev-02.local:9093


