spring:
  kafka:
    ssl:
      protocol: TLS
      key-store-type: PKCS12
      key-store-location: file:pki/demo-producer.p12
      key-store-password: bdm1QKInU586etBN
      trust-store-type: PKCS12
      trust-store-location: file:pki/ca.p12
      trust-store-password: ulLdVI9hUP46gaQj
    security:
      protocol: SASL_SSL
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username='demo-producer' password='jsi9zxp28syOTQf2';
        mechanism: SCRAM-SHA-256
      linger:
        ms: 100

---
spring:
  profiles: kafka-digital
  kafka:
    bootstrap-servers: kafka-zkks-digital-dev-01.local:9093

---
spring:
  profiles: kafka-analytics
  kafka:
    bootstrap-servers: kafka-zkks-analytics-dev-01.local:9093

---
spring:
  profiles: confluent-digital
  kafka:
    bootstrap-servers: confluent-zkks-digital-dev-01.local:9093

---
spring:
  profiles: confluent-analytics
  kafka:
    bootstrap-servers: confluent-zkks-analytics-dev-01.local:9093

---
spring:
  profiles: confluent-local
  kafka:
    bootstrap-servers: confluent-ks-local-01.local:9093


