---
# file: roles/confluent_common/defaults/main.yaml

confluent_defaults:
  major_version: '6.2'
  package_version: '6.2.0'

prometheus_jmx_exporter:
  enabled: true
  package_version: '0.16.1'
  package_checksum: sha1:d3952d71a19007372240657b07f5b1b42994880e

confluent_config: "{{ confluent_defaults | combine(confluent | default({}), recursive=True) }}"
