---
# file: roles/confluent_common/defaults/main.yaml

confluent_defaults:
  major_version: 6.0
  package_version: 6.0.0

prometheus_jmx_exporter:
  enabled: true
  package_version: 0.14.0
  package_checksum: sha1:7541a57484f3bc765d8c14e881ec8d445067b81c

confluent_config: "{{ confluent_defaults | combine(confluent | default({}), recursive=True) }}"
