---
# file: roles/confluent_common/defaults/main.yaml

# NOTE: The Confluent version is specified here and in the hierarchical configuration 
#       below because the hierarchical configuration is not inherited by the other
#       Confluent roles. The two values MUST be kept in sync.
confluent_version: '7.0.1'

confluent_defaults:
  major_version: '7.0'
  package_version: '7.0.1'

prometheus_jmx_exporter:
  enabled: true
  package_version: '0.16.1'
  package_checksum: sha1:d3952d71a19007372240657b07f5b1b42994880e

confluent_config: "{{ confluent_defaults | combine(confluent | default({}), recursive=True) }}"
