---
# file: roles/confluent_common/defaults/main.yaml

confluent_defaults:
  major_version: 6.1
  package_version: 6.1.1

prometheus_jmx_exporter:
  enabled: true
  package_version: 0.15.0
  package_checksum: sha1:a1061f29088ac2709da076a97736de575a872538

confluent_config: "{{ confluent_defaults | combine(confluent | default({}), recursive=True) }}"
