---
# file: roles/k8s_worker/tasks/main.yml

- name: Create the /var/cache/ansible directory
  file:
    path: /var/cache/ansible
    state: directory

- name: Add the k8s-admin group
  group:
    name: k8s-admin
    gid: 310
    state: present

- name: Add the k8s-admin user with a specific uid and a primary group of 'k8s-admin'
  user:
    name: k8s-admin
    comment: Kubernetes Administrator
    uid: 310
    group: k8s-admin
    groups: docker
    shell: /bin/bash
    state: present

- include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags:
    - unbound

- include_tasks: centos.yml
  when: ansible_distribution == "CentOS"
  tags:
    - unbound

- name: Check whether the kubelet service has been configured
  stat:
    path: /var/lib/kubelet/config.yaml
  register: kubelet_config_stat_result

- name: Initializing the additional worker node in the Kubernetes cluster
  block:

    - command:
        cmd: /usr/bin/kubeadm token create --print-join-command
      register: kubeadm_join_command_result
      delegate_to: "{{ groups['k8s_master'][0] }}"

    - set_fact:
        kubeadm_join_command: "{{ kubeadm_join_command_result.stdout_lines[0] }}"

    - command:
        cmd: "{{ kubeadm_join_command }}"

  when: kubelet_config_stat_result.stat.exists == False

- name: Deploy the kube-state-metrics service if this is the first worker node
  block:

    - template:
        src: kube-state-metrics.yml.j2
        dest: /tmp/kube-state-metrics.yml

    - shell:
        cmd: /usr/bin/kubectl apply -f /tmp/kube-state-metrics.yml
  when: groups['k8s_worker'][0] == inventory_hostname
