# file: roles/k8s_worker/tasks/main.yaml

- name: Create the /var/tmp/ansible directory
  file:
    path: /var/tmp/ansible
    owner: root
    group: root
    mode: 0700    
    state: directory

- include_tasks: ubuntu.yaml
  when: ansible_distribution == "Ubuntu"
  tags:
    - unbound

- include_tasks: centos.yaml
  when: ansible_distribution == "CentOS"
  tags:
    - unbound

- name: Check whether the kubelet service has been configured
  stat:
    path: /var/lib/kubelet/config.yaml
  register: kubelet_config_stat_result

- name: Check whether a CNI provider has been configured
  stat:
    path: /etc/cni
  register: etc_cni_stat_result

- name: Initializing the additional worker node in the Kubernetes cluster
  block:
  - command:
      cmd: /usr/bin/kubeadm token create --print-join-command
    register: kubeadm_join_command_result
    delegate_to: "{{ groups['k8s_master'][0] }}"

  - set_fact:
      kubeadm_join_command: "{{ kubeadm_join_command_result.stdout_lines[0] }}"

  - command:
      cmd: "{{ kubeadm_join_command }}"

  when: kubelet_config_stat_result.stat.exists == False

