---
# file: roles/k8s_master/defaults/main.yaml

k8s_defaults:
  # For latest version of Helm chart see: https://github.com/bitnami-labs/sealed-secrets/blob/main/helm/sealed-secrets/Chart.yaml
  bitnami_labs_sealed_secrets_enabled: true
  bitnami_labs_sealed_secrets_helm_chart_version: '2.7.0'
  bitnami_labs_sealed_secrets_kubeseal_version: '0.19.1'

  cni_provider: flannel

  etcd_topology: stacked

  # NOTE: The pod subnet MUST be 10.244.0.0/16 since this is hardcoded in the default flannel yaml configuration
  pod_subnet: 10.244.0.0/16
  service_subnet: 10.245.0.0/16

k8s_config: "{{ k8s_defaults | combine(k8s | default({}), recursive=True) }}"
