---
# file: roles/docker/tasks/centos.yaml

- debug:
    msg: Applying the CentOS-specific Docker configuration

- name: Collect the package facts
  package_facts:
    manager: auto

- name: Retrieve the version of the installed containerd package
  debug:
    msg: Found the installed containerd package ({{ ansible_facts.packages['containerd.io'][0].version }})
  when: "'containerd.io' in ansible_facts.packages"

- name: Install the containerd package
  block:
  - name: Check whether the {{ containerd_centos_package }} package has been downloaded
    become: no
    local_action: stat path=packages/{{ containerd_centos_package }}
    register: containerd_package_stat_result

  - name: Download the {{ containerd_centos_package }} package
    become: no
    local_action: get_url url='https://download.docker.com/linux/centos/7/x86_64/stable/Packages/{{ containerd_centos_package }}' dest='packages/{{ containerd_centos_package }}'
    when: (containerd_package_stat_result.stat.exists == False)

  - name: Copy the {{ containerd_centos_package }} package
    copy:
      src: packages/{{ containerd_centos_package }}
      dest: /var/tmp/ansible/{{ containerd_centos_package }}

  - name: Install the {{ containerd_centos_package }} package
    yum:
      name: /var/tmp/ansible/{{ containerd_centos_package }}
      state: present

  when: (('containerd.io' not in ansible_facts.packages) or (ansible_facts.packages['containerd.io'][0].version != containerd_centos_package_version))


- name: Retrieve the version of the installed docker-ce-cli package
  debug:
    msg: Found the installed docker-ce-cli package ({{ ansible_facts.packages['docker-ce-cli'][0].version }})
  when: "'docker-ce-cli' in ansible_facts.packages"

- name: Install the docker-ce-cli package
  block:
  - name: Check whether the {{ docker_ce_cli_centos_package }} package has been downloaded
    become: no
    local_action: stat path=packages/{{ docker_ce_cli_centos_package }}
    register: docker_ce_cli_package_stat_result

  - name: Download the {{ docker_ce_cli_centos_package }} package
    become: no
    local_action: get_url url='https://download.docker.com/linux/centos/7/x86_64/stable/Packages/{{ docker_ce_cli_centos_package }}' dest='packages/{{ docker_ce_cli_centos_package }}'
    when: (docker_ce_cli_package_stat_result.stat.exists == False)

  - name: Copy the {{ docker_ce_cli_centos_package }} package
    copy:
      src: packages/{{ docker_ce_cli_centos_package }}
      dest: /var/tmp/ansible/{{ docker_ce_cli_centos_package }}

  - name: Install the {{ docker_ce_cli_centos_package }} package
    yum:
      name: /var/tmp/ansible/{{ docker_ce_cli_centos_package }}
      state: present

  when: (('docker-ce-cli' not in ansible_facts.packages) or (ansible_facts.packages['docker-ce-cli'][0].version != docker_ce_cli_centos_package_version))


- name: Retrieve the version of the installed docker-ce package
  debug:
    msg: Found the installed docker-ce package ({{ ansible_facts.packages['docker-ce'][0].version }})
  when: "'docker-ce' in ansible_facts.packages"

- name: Install the docker-ce package
  block:
  - name: Check whether the {{ docker_ce_centos_package }} package has been downloaded
    become: no
    local_action: stat path=packages/{{ docker_ce_centos_package }}
    register: docker_ce_package_stat_result

  - name: Download the {{ docker_ce_centos_package }} package
    become: no
    local_action: get_url url='https://download.docker.com/linux/centos/7/x86_64/stable/Packages/{{ docker_ce_centos_package }}' dest='packages/{{ docker_ce_centos_package }}'
    when: (docker_ce_package_stat_result.stat.exists == False)

  - name: Copy the {{ docker_ce_centos_package }} package
    copy:
      src: packages/{{ docker_ce_centos_package }}
      dest: /var/tmp/ansible/{{ docker_ce_centos_package }}

  - name: Install the {{ docker_ce_centos_package }} package
    yum:
      name: /var/tmp/ansible/{{ docker_ce_centos_package }}
      state: present

  - name: Create the /etc/docker directory
    file:
      path: /etc/docker
      state: directory

  - name: Create the Docker daemon configuration file
    template:
      src: daemon.json.j2
      dest: /etc/docker/daemon.json

  - name: Restart the docker service
    systemd:
      name: docker.service
      state: restarted
      enabled: yes
      daemon_reload: yes

  when: (('docker-ce' not in ansible_facts.packages) or (ansible_facts.packages['docker-ce'][0].version != docker_ce_centos_package_version))

