---
# file: roles/docker/tasks/ubuntu.yaml

- debug:
    msg: Applying the Ubuntu-specific Docker configuration

- name: Add the Docker GPG apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add the Docker CE repository
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable'
    filename: 'docker-ce'
    state: present
  register: add_docker_ce_repository_result

- name: Update the Apt cache
  apt: update_cache=yes cache_valid_time=3600
  when: (add_docker_ce_repository_result.changed == True)

- name: Collect the package facts
  package_facts:
    manager: auto

- name: Retrieve the version of the installed docker-ce package
  debug:
    msg: Found the installed docker-ce package ({{ ansible_facts.packages['docker-ce'][0].version }})
  when: "'docker-ce' in ansible_facts.packages"

- name: Retrieve the version of the installed docker-ce-cli package
  debug:
    msg: Found the installed docker-ce-cli package ({{ ansible_facts.packages['docker-ce-cli'][0].version }})
  when: "'docker-ce-cli' in ansible_facts.packages"

- name: Install the docker-ce and docker-ce-cli packages
  block:
  - name: Update the Apt cache
    apt: update_cache=yes cache_valid_time=3600

  - name: Unlock the version of the docker-ce package
    command:
      cmd: apt-mark unhold docker-ce
    when: "'docker-ce' in ansible_facts.packages"

  - name: Unlock the version of the docker-ce-cli packages
    command:
      cmd: apt-mark unhold docker-ce-cli
    when: "'docker-ce-cli' in ansible_facts.packages"

  - name: Install the docker-ce and docker-ce-cli packages ({{ docker_config.ubuntu.docker_ce.package_version }})
    apt:
      state: present
      policy_rc_d: 101
      name:
       - docker-ce={{ docker_config.ubuntu.docker_ce.package_version }}
       - docker-ce-cli={{ docker_config.ubuntu.docker_ce.package_version }}

  - name: Lock the version of the docker-ce and docker-ce-cli packages
    command:
      cmd: apt-mark hold docker-ce docker-ce-cli

  - name: Create the /etc/docker directory
    file:
      path: /etc/docker
      state: directory

  - name: Create the Docker daemon configuration file
    template:
      src: daemon.json.j2
      dest: /etc/docker/daemon.json

  - name: Restart the docker service
    systemd:
      name: docker.service
      state: restarted
      enabled: yes
      daemon_reload: yes

  when: (('docker-ce' not in ansible_facts.packages) or (ansible_facts.packages['docker-ce'][0].version != docker_config.ubuntu.docker_ce.package_version))


