# This playbook configures a Confluent cluster.

- name: Gather facts from all Confluent Kafka MirrorMaker hosts
  hosts: confluent_kafka_mirrorkeeper
  become: yes
  become_user: root
  pre_tasks:
  - setup:
    delegate_to: "{{ item }}"
    delegate_facts: True
    when: hostvars[item]['ansible_default_ipv4'] is not defined
    with_items: "{{ groups['confluent_kafka_mirrorkeeper'] }}"
  tasks: []

- name: Gather facts from all Confluent Kafka Server hosts
  hosts: confluent_kafka_server
  become: yes
  become_user: root
  pre_tasks:
  - setup:
    delegate_to: "{{ item }}"
    delegate_facts: True
    when: hostvars[item]['ansible_default_ipv4'] is not defined
    with_items: "{{ groups['confluent_kafka_server'] }}"
  tasks: []

- name: Gather facts from all Confluent ZooKeeper hosts
  hosts: confluent_zookeeper
  become: yes
  become_user: root
  pre_tasks:
  - setup:
    delegate_to: "{{ item }}"
    delegate_facts: True
    when: hostvars[item]['ansible_default_ipv4'] is not defined
    with_items: "{{ groups['confluent_zookeeper'] }}"
  tasks: []

- name: Configure the Confluent ZooKeeper hosts
  hosts: confluent_zookeeper
  become: yes
  become_user: root
  roles:
  - confluent_zookeeper

- name: Configure the Confluent Kafka Server hosts
  hosts: confluent_kafka_server
  become: yes
  become_user: root
  roles:
  - confluent_kafka_server

- name: Configure the Confluent Kafak MirrorMaker hosts
  hosts: confluent_kafka_mirrormaker
  become: yes
  become_user: root
  roles:
  - confluent_kafka_mirrormaker

- name: Configure the Confluent Schema Registry hosts
  hosts: confluent_schema_registry
  become: yes
  become_user: root
  roles:
  - confluent_schema_registry

