
- name: Gather facts from all postgresql hosts
  hosts: postgresql
  become: yes
  become_user: root
  pre_tasks:
  - setup:
    delegate_to: "{{ item }}"
    delegate_facts: True
    when: hostvars[item]['ansible_default_ipv4'] is not defined
    with_items: "{{ (groups['postgresql'] | default([])) }}"
  tasks: []

- name: Configure the postgresql hosts
  hosts: postgresql
  become: yes
  become_user: root
  roles:
  - postgresql
