# This playbook configures an Etcd cluster.

- name: Gather facts from all etcd hosts
  hosts: etcd
  become: yes
  become_user: root
  pre_tasks:
  - setup:
    delegate_to: "{{ item }}"
    delegate_facts: True
    when: hostvars[item]['ansible_default_ipv4'] is not defined
    with_items: "{{ (groups['etcd'] | default([])) }}"
  tasks: []

- name: Configure the etcd hosts
  hosts: etcd
  vars:
    etcd_ubuntu_package_version: 3.2.17+dfsg-1
  become: yes
  become_user: root

  roles:
    - etcd
