# This playbook configures a Kubernetes cluster.

- name: Configure the Kubernetes API load balancer hosts
  hosts: k8s_load_balancer
  become: yes
  become_user: root
  roles:
  - k8s_load_balancer

- name: Apply the common configuration to both Kubernetes master and worker hosts
  hosts: k8s_master:k8s_worker
  vars:
    docker_ubuntu_package_version: 5:19.03.6~3-0~ubuntu-bionic
    k8s_vmware_tanzu_kubernetes_grid_version: 1.17.3+vmware.1
    k8s_vmware_tanzu_kubernetes_cni_version: 0.7.5+vmware.6-1
    k8s_ubuntu_package_version: 1.17.3-00
    topolvm_lvmd_version: 0.3.0    
  become: yes
  become_user: root
  roles:
  - docker
  - k8s_common

#- name: Configure the Kubernetes master hosts
#  hosts: k8s_master
#  vars:
#    helm_version: 3.1.0
#    helm_package_hash: sha256:f0fd9fe2b0e09dc9ed190239fce892a468cbb0a2a8fffb9fe846f893c8fd09de
#    istio_version: 1.4.4
#    istio_package_hash: sha256:105365208e6c5e2c24fbd74c34e6a63e0301d265b8b674387b6a8163c7579c27
#    istioctl_version: 1.4.4
#    istioctl_package_hash: sha256:01f5775dea867dde54e16da305378370bb0e7ee5acbfbedd35e1b40aefd2ce14
#    k8s_ubuntu_package_version: 1.17.3-00
#    kube_state_metrics_version: 1.9.4
#    topolvm_version: 0.3.0
#  become: yes
#  become_user: root
#  roles:
#  - k8s_master
#
#- name: Configure the Kubernetes worker hosts
#  hosts: k8s_worker
#  become: yes
#  become_user: root
#  roles:
#  - k8s_worker
