# This playbook configures a Kubernetes cluster.

- name: Configure the Kubernetes API load balancer hosts
  hosts: k8s_load_balancer
  become: yes
  become_user: root
  roles:
  - k8s_load_balancer

- name: Apply the common configuration to both Kubernetes master and worker hosts
  hosts: k8s_master:k8s_worker
  vars:
    docker_ubuntu_package_version: 5:19.03.6~3-0~ubuntu-bionic
    k8s_version: 1.17
    k8s_vmware_tanzu_kubernetes_grid_version: 1.17.3+vmware.1
    k8s_vmware_tanzu_kubernetes_grid_checksum: sha256:34b680c64e7ccf8e7502519a4282c4e8e7c596acdf76945b15fa8e18a5525897
    k8s_vmware_tanzu_kubernetes_cni_version: 0.7.5+vmware.6-1
    k8s_vmware_tanzu_kubernetes_cri_tools_version: 1.16.1+vmware.3-1
    k8s_vmware_tanzu_kubernetes_kubeadm_version: 1.17.3+vmware.1-1
    k8s_vmware_tanzu_kubernetes_kubectl_version: 1.17.3+vmware.1-1
    k8s_vmware_tanzu_kubernetes_kubelet_version: 1.17.3+vmware.1-1    
    topolvm_lvmd_version: 0.4.1   
  become: yes
  become_user: root
  roles:
  - docker
  - k8s_common

- name: Configure the Kubernetes master hosts
  hosts: k8s_master
  vars:
    bitnami_labs_sealed_secrets_version: 0.11.0
    helm_version: 3.1.2
    helm_package_checksum: sha256:e6be589df85076108c33e12e60cfb85dcd82c5d756a6f6ebc8de0ee505c9fd4c
    istio_version: 1.5.0
    istio_package_checksum: sha256:fba603390074b1b9da9b3bd1492a278740fe725ac8ff07b8ec54fb7d66e03c33
    istioctl_package_checksum: sha256:e841c8858f7598351caaf6d7e6a67c4a43218f343629c67cf76db5d000c9df72
    kube_state_metrics_version: 1.9.5
    topolvm_version: 0.4.1
  become: yes
  become_user: root
  roles:
  - k8s_master

- name: Configure the Kubernetes worker hosts
  hosts: k8s_worker
  become: yes
  become_user: root
  roles:
  - k8s_worker
