# This playbook configures a Kubernetes cluster.

- name: Configure the Kubernetes load balancer hosts
  hosts: k8s_load_balancer
  become: yes
  become_user: root
  roles:
  - k8s_load_balancer

- name: Configure the Kubernetes master hosts
  hosts: k8s_master
  become: yes
  become_user: root
  roles:
  - k8s_master

- name: Configure the Kubernetes worker hosts
  hosts: k8s_worker
  become: yes
  become_user: root
  roles:
  - k8s_worker

- name: Apply the configuration for the Kubernetes storage components to the Kubernetes cluster
  hosts: k8s_master:k8s_worker
  become: yes
  become_user: root
  roles:
  - k8s_storage


#
#- name: Apply the configuration for the Kubernetes operator components to the Kubernetes cluster
#  hosts: k8s_master:k8s_worker
#  become: yes
#  become_user: root
#  roles:
#  - k8s_operators

- name: Apply the configuration for the Kubernetes monitoring components to the Kubernetes cluster
  hosts: k8s_master:k8s_worker
  become: yes
  become_user: root
  roles:
  - k8s_monitoring

#- name: Apply the configuration for the Istio components to the Kubernetes cluster
#  hosts: k8s_master:k8s_worker
#  become: yes
#  become_user: root
#  roles:
#  - k8s_istio
#
#
#


