# This playbook configures a Kubernetes cluster.

- name: Gather facts from the Kubernetes load balancer hosts
  hosts: k8s_load_balancer
  become: yes
  become_user: root
  pre_tasks:
  - setup:
    delegate_to: "{{ item }}"
    delegate_facts: True
    when: hostvars[item]['ansible_default_ipv4'] is not defined
    with_items: "{{ (groups['k8s_master'] | default([])) }}"    
  - setup:
    delegate_to: "{{ item }}"
    delegate_facts: True
    when: hostvars[item]['ansible_default_ipv4'] is not defined
    with_items: "{{ (groups['k8s_worker'] | default([])) }}"
  - setup:
    delegate_to: "{{ item }}"
    delegate_facts: True
    when: hostvars[item]['ansible_default_ipv4'] is not defined
    with_items: "{{ (groups['k8s_load_balancer'] | default([])) }}"    
  tasks: []

- name: Gather facts from the Kubernetes master hosts
  hosts: k8s_master
  become: yes
  become_user: root
  pre_tasks:
  - setup:
    delegate_to: "{{ item }}"
    delegate_facts: True
    when: hostvars[item]['ansible_default_ipv4'] is not defined
    with_items: "{{ (groups['k8s_master'] | default([])) }}"
  tasks: []

- name: Gather facts from the Kubernetes worker hosts
  hosts: k8s_worker
  become: yes
  become_user: root
  pre_tasks:
  - setup:
    delegate_to: "{{ item }}"
    delegate_facts: True
    when: hostvars[item]['ansible_default_ipv4'] is not defined
    with_items: "{{ (groups['k8s_master'] | default([])) }}"
  - setup:
    delegate_to: "{{ item }}"
    delegate_facts: True
    when: hostvars[item]['ansible_default_ipv4'] is not defined
    with_items: "{{ (groups['k8s_worker'] | default([])) }}"
  tasks: []

- name: Configure the Kubernetes load balancer hosts
  hosts: k8s_load_balancer
  become: yes
  become_user: root
  roles:
  - k8s_load_balancer

- name: Configure the Kubernetes master hosts
  hosts: k8s_master
  become: yes
  become_user: root
  roles:
  - k8s_master

- name: Configure the Kubernetes worker hosts
  hosts: k8s_worker
  become: yes
  become_user: root
  roles:
  - k8s_worker

- name: Apply the configuration for the Kubernetes storage components to the Kubernetes cluster
  hosts: k8s_master:k8s_worker
  become: yes
  become_user: root
  roles:
  - k8s_storage

#- name: Apply the configuration for the Kubernetes operator components to the Kubernetes cluster
#  hosts: k8s_master:k8s_worker
#  become: yes
#  become_user: root
#  roles:
#  - k8s_operators

- name: Apply the configuration for the Kubernetes monitoring components to the Kubernetes cluster
  hosts: k8s_master:k8s_worker
  become: yes
  become_user: root
  roles:
  - k8s_monitoring

- name: Apply the configuration for the Istio components to the Kubernetes cluster
  hosts: k8s_master:k8s_worker
  become: yes
  become_user: root
  roles:
  - k8s_istio


