# This playbook configures a Kafka cluster.

- name: Gather facts from all Kafka MirrorMaker related hosts
  hosts: kafka_mirrorkeeper
  become: yes
  become_user: root
  pre_tasks:
  - setup:
    delegate_to: "{{ item }}"
    delegate_facts: True
    when: hostvars[item]['ansible_default_ipv4'] is not defined
    with_items: "{{ (groups['kafka_mirrorkeeper'] | default([])) }}"
  - setup:
    delegate_to: "{{ item }}"
    delegate_facts: True
    when: hostvars[item]['ansible_default_ipv4'] is not defined
    with_items: "{{ (groups['prometheus-server'] | default([])) }}"
  tasks: []

- name: Gather facts from all Kafka Server related hosts
  hosts: kafka_server
  become: yes
  become_user: root
  pre_tasks:
  - setup:
    delegate_to: "{{ item }}"
    delegate_facts: True
    when: hostvars[item]['ansible_default_ipv4'] is not defined
    with_items: "{{ (groups['burrow'] | default([])) }}"
  - setup:
    delegate_to: "{{ item }}"
    delegate_facts: True
    when: hostvars[item]['ansible_default_ipv4'] is not defined
    with_items: "{{ (groups['kafka_server'] | default([])) }}"
  - setup:
    delegate_to: "{{ item }}"
    delegate_facts: True
    when: hostvars[item]['ansible_default_ipv4'] is not defined
    with_items: "{{ (groups['prometheus-server'] | default([])) }}"
  tasks: []

- name: Gather facts from all Kafka ZooKeeper related hosts
  hosts: kafka_zookeeper
  become: yes
  become_user: root
  pre_tasks:
  - setup:
    delegate_to: "{{ item }}"
    delegate_facts: True
    when: hostvars[item]['ansible_default_ipv4'] is not defined
    with_items: "{{ (groups['burrow'] | default([])) }}"
  - setup:
    delegate_to: "{{ item }}"
    delegate_facts: True
    when: hostvars[item]['ansible_default_ipv4'] is not defined
    with_items: "{{ (groups['kafka_server'] | default([])) }}"
  - setup:
    delegate_to: "{{ item }}"
    delegate_facts: True
    when: hostvars[item]['ansible_default_ipv4'] is not defined
    with_items: "{{ (groups['kafka_zookeeper'] | default([])) }}"
  - setup:
    delegate_to: "{{ item }}"
    delegate_facts: True
    when: hostvars[item]['ansible_default_ipv4'] is not defined
    with_items: "{{ (groups['prometheus-server'] | default([])) }}"
  tasks: []

- name: Configure the Kafka ZooKeeper hosts
  hosts: kafka_zookeeper
  become: yes
  become_user: root
  roles:
  - kafka_zookeeper

- name: Configure the Kafka Broker hosts
  hosts: kafka_server
  become: yes
  become_user: root
  roles:
  - kafka_server

- name: Configure the Kafka MirrorMaker hosts
  hosts: kafka_mirrormaker
  become: yes
  become_user: root
  roles:
  - kafka_mirrormaker
