# This playbook configures a monitoring server.

- name: Configure a monitored host
  hosts: monitored
  become: yes
  become_user: root
  roles:
  - monitored

- name: Configure a Prometheus Server host
  hosts: prometheus_server
  become: yes
  become_user: root
  roles:
  - prometheus_server

- name: Configure a Grafana host
  hosts: grafana
  become: yes
  become_user: root
  roles:
  - grafana

