# This playbook configures a monitoring server.

- name: Configure a monitored host
  hosts: monitored
  become: yes
  become_user: root
  roles:
  - monitored

- name: Configure a Prometheus host
  hosts: prometheus
  become: yes
  become_user: root
  roles:
  - prometheus

- name: Configure a Grafana host
  hosts: grafana
  become: yes
  become_user: root
  roles:
  - grafana

