# This playbook configures the monitoring components.

- name: Gather facts from all hosts monitored by Prometheus
  hosts: prometheus_server
  become: yes
  become_user: root
  pre_tasks:
  - setup:
    delegate_to: "{{ item }}"
    delegate_facts: True
    when: hostvars[item]['ansible_default_ipv4'] is not defined
    with_items: "{{ (groups['burrow'] | default([])) }}"
  - setup:
    delegate_to: "{{ item }}"
    delegate_facts: True
    when: hostvars[item]['ansible_default_ipv4'] is not defined
    with_items: "{{ (groups['confluent_kafka_server'] | default([])) }}"
  - setup:
    delegate_to: "{{ item }}"
    delegate_facts: True
    when: hostvars[item]['ansible_default_ipv4'] is not defined
    with_items: "{{ (groups['confluent_kafka_zookeeper'] | default([])) }}"
  - setup:
    delegate_to: "{{ item }}"
    delegate_facts: True
    when: hostvars[item]['ansible_default_ipv4'] is not defined
    with_items: "{{ (groups['etcd'] | default([])) }}"
  - setup:
    delegate_to: "{{ item }}"
    delegate_facts: True
    when: hostvars[item]['ansible_default_ipv4'] is not defined
    with_items: "{{ (groups['k8s_master'] | default([])) }}"
  - setup:
    delegate_to: "{{ item }}"
    delegate_facts: True
    when: hostvars[item]['ansible_default_ipv4'] is not defined
    with_items: "{{ (groups['kafka_server'] | default([])) }}"
  - setup:
    delegate_to: "{{ item }}"
    delegate_facts: True
    when: hostvars[item]['ansible_default_ipv4'] is not defined
    with_items: "{{ (groups['kafka_zookeeper'] | default([])) }}"
  - setup:
    delegate_to: "{{ item }}"
    delegate_facts: True
    when: hostvars[item]['ansible_default_ipv4'] is not defined
    with_items: "{{ (groups['monitored'] | default([])) }}"
  - setup:
    delegate_to: "{{ item }}"
    delegate_facts: True
    when: hostvars[item]['ansible_default_ipv4'] is not defined
    with_items: "{{ (groups['prometheus_alert_manager'] | default([])) }}"
  tasks: []

- name: Configure a Burrow host
  hosts: burrow
  become: yes
  become_user: root
  roles:
  - burrow

- name: Configure a monitored host
  hosts: monitored
  become: yes
  become_user: root
  roles:
  - monitored

- name: Configure a Prometheus Server host
  hosts: prometheus_server
  become: yes
  become_user: root
  roles:
  - prometheus_server
  
- name: Configure a Prometheus Alert Manager host
  hosts: prometheus_alert_manager
  become: yes
  become_user: root
  roles:
  - prometheus_alert_manager  

- name: Configure a Grafana host
  hosts: grafana
  become: yes
  become_user: root
  roles:
  - grafana
