---
# This playbook configures a monitoring server.


- name: Configure a monitored host
  hosts: monitored
  vars:
    prometheus_node_exporter_version: 0.18.1
    prometheus_node_exporter_package_hash: sha256:b2503fd932f85f4e5baf161268854bf5d22001869b84f00fd2d1f57b51b72424
  become: yes
  become_user: root

  roles:
    - monitored

- name: Configure a Prometheus host
  hosts: prometheus
  vars:
    prometheus_version: 2.15.2
    prometheus_package_hash: sha256:579f800ec3ec2dc9a36d2d513e7800552cf6b0898f87a8abafd54e73b53f8ad0
  become: yes
  become_user: root

  roles:
    - prometheus

- name: Configure a Grafana host
  hosts: grafana
  vars:
    grafana_ubuntu_package_version: 6.6.0
  become: yes
  become_user: root

  roles:
    - grafana

