---
# file: roles/k8s_common/vars/main.yaml

k8s_centos_package_version: 1.18.0
k8s_helm_version: 3.2.2
k8s_helm_package_checksum: sha256:305cc92bc21c902a5337a9e1a63316ef67f6e06000d878cf22eb504c6750745c
k8s_ubuntu_package_version: 1.18.2-00

k8s_k8s_admin_user_id: 500
k8s_k8s_admin_group_id: 500







