---
# file: roles/k8s_common/defaults/main.yaml

k8s_defaults:
  cri_o_version: '1.20'
  cri_o_redhat_package_version: '1.20'
  cri_o_ubuntu_package_version: '1.20.2~0'

  crictl_version: '1.20.0'
  crictl_package_checksum: sha256:44d5f550ef3f41f9b53155906e0229ffdbee4b19452b4df540265e29572b899c

  bitnami_labs_sealed_secrets_enabled: true


  k8s_redhat_package_version: '1.20.6'
  k8s_ubuntu_package_version: '1.20.6-00'

  kustomize_version: '4.1.2'

  admin_user: k8s-admin
  admin_user_id: 500
  admin_group: k8s-admin
  admin_group_id: 500

  cni_provider: weave

  helm_package_checksum: sha256:f3a4be96b8a3b61b14eec1a35072e1d6e695352e7a08751775abf77861a0bf54
  helm_version: '3.6.2'

k8s_config: "{{ k8s_defaults | combine(k8s | default({}), recursive=True) }}"


