---
# file: roles/k8s_common/defaults/main.yaml

k8s_defaults:
  crictl_version: '1.24.2'
  crictl_package_checksum: sha256:53432dd365f7bf045c1e65ee2e44c74df6a0a8f0a798f640a945c8e07ad8682e

  bitnami_labs_sealed_secrets_enabled: true

  k8s_redhat_package_version: '1.24.7'
  k8s_ubuntu_package_version: '1.24.7-00'

  kustomize_version: '4.5.7'

  admin_user: k8s-admin
  admin_user_id: 500
  admin_group: k8s-admin
  admin_group_id: 500

  cni_provider: weave

  helm_package_checksum: sha256:2315941a13291c277dac9f65e75ead56386440d3907e0540bf157ae70f188347
  helm_version: '3.10.2'

k8s_config: "{{ k8s_defaults | combine(k8s | default({}), recursive=True) }}"


