---
# file: roles/k8s_common/defaults/main.yaml

pki_root: ../../../pki

k8s_defaults:
  centos_package_version: 1.19.3
  ubuntu_package_version: 1.19.3-00
  
  kustomize_version: 3.8.5

  admin_user: k8s-admin
  admin_user_id: 500
  admin_group: k8s-admin
  admin_group_id: 500

  cni_provider: weave

  helm_package_checksum: sha256:b664632683c36446deeb85c406871590d879491e3de18978b426769e43a1e82c
  helm_version: 3.3.4

k8s_config: "{{ k8s_defaults | combine(k8s | default({}), recursive=True) }}"




