---
# file: roles/k8s_common/vars/main.yaml

k8s_centos_package_version: 1.18.0
k8s_helm_version: 3.1.2
k8s_helm_package_checksum: sha256:e6be589df85076108c33e12e60cfb85dcd82c5d756a6f6ebc8de0ee505c9fd4c
k8s_ubuntu_package_version: 1.18.2-00

k8s_k8s_admin_user_id: 400
k8s_k8s_admin_group_id: 400






