---
# file: roles/k8s_common/defaults/main.yaml

k8s_defaults:
  bitnami_labs_sealed_secrets_enabled: true

  redhat_package_version: 1.20.6
  ubuntu_package_version: 1.20.6-00

  kustomize_version: 4.1.2

  admin_user: k8s-admin
  admin_user_id: 500
  admin_group: k8s-admin
  admin_group_id: 500

  cni_provider: weave

  helm_package_checksum: sha256:a8ddb4e30435b5fd45308ecce5eaad676d64a5de9c89660b56face3fe990b318
  helm_version: 3.5.4

k8s_config: "{{ k8s_defaults | combine(k8s | default({}), recursive=True) }}"




