---
# file: roles/kafka_common/tasks/main.yaml

#   ___  ____       ____  ____  _____ ____ ___ _____ ___ ____
#  / _ \/ ___|     / ___||  _ \| ____/ ___|_ _|  ___|_ _/ ___|
# | | | \___ \ ____\___ \| |_) |  _|| |    | || |_   | | |
# | |_| |___) |_____|__) |  __/| |__| |___ | ||  _|  | | |___
#  \___/|____/     |____/|_|   |_____\____|___|_|   |___\____|
#
- include_tasks: ubuntu.yaml
  when: ansible_distribution == 'Ubuntu'
  tags:
  - unbound

- include_tasks: centos.yaml
  when: ansible_distribution == 'CentOS'
  tags:
  - unbound


#  _  __    _    _____ _  __    _       ____ ___  __  __ __  __  ___  _   _
# | |/ /   / \  |  ___| |/ /   / \     / ___/ _ \|  \/  |  \/  |/ _ \| \ | |
# | ' /   / _ \ | |_  | ' /   / _ \   | |  | | | | |\/| | |\/| | | | |  \| |
# | . \  / ___ \|  _| | . \  / ___ \  | |__| |_| | |  | | |  | | |_| | |\  |
# |_|\_\/_/   \_\_|   |_|\_\/_/   \_\  \____\___/|_|  |_|_|  |_|\___/|_| \_|
#
- name: Install Kafka
  block:
  - debug:
      msg: Check whether the Kafka {{ kafka_version }} package has been installed

  - stat:
      path: /opt/kafka
    register: kafka_installed_stat_result

  - block:
    - debug:
        msg: Install the Kafka {{ kafka_version }} package

    - name: Check whether the Kafka {{ kafka_version }} package has been downloaded
      become: no
      local_action: stat path=packages/kafka_2.13-{{ kafka_version }}.tgz
      register: kafka_package_stat_result

    - name: Download the Kafka {{ kafka_version }} package
      become: no
      local_action: get_url url='http://apache.is.co.za/kafka/{{ kafka_version }}/kafka_2.13-{{ kafka_version }}.tgz' dest='packages/kafka_2.13-{{ kafka_version }}.tgz' checksum={{ kafka_package_checksum }}
      when: (kafka_package_stat_result.stat.exists == False)

    - name: Extract the Kafka {{ kafka_version }} package
      unarchive:
        src: packages/kafka_2.13-{{ kafka_version }}.tgz
        dest: /opt

    - name: Create the symbolic link to the Kafka {{ kafka_version }} package
      file:
        src: /opt/kafka_2.13-{{ kafka_version }}
        dest: /opt/kafka
        owner: root
        group: root
        state: link

    - name: Copy the custom-replication-policy.jar file to the /opt/kafka/libs directory
      copy:
        src: custom-replication-policy.jar
        dest: /opt/kafka/libs/custom-replication-policy.jar
        owner: root
        group: root

    when: ((kafka_installed_stat_result.stat.exists == False) or (kafka_installed_stat_result.stat.lnk_target != ('/opt/kafka_2.13-' + kafka_version)))


#  ____  ____   ___  __  __ _____ _____ _   _ _____ _   _ ____        _ __  ____  __  _______  ______   ___  ____ _____ _____ ____
# |  _ \|  _ \ / _ \|  \/  | ____|_   _| | | | ____| | | / ___|      | |  \/  \ \/ / | ____\ \/ /  _ \ / _ \|  _ \_   _| ____|  _ \
# | |_) | |_) | | | | |\/| |  _|   | | | |_| |  _| | | | \___ \   _  | | |\/| |\  /  |  _|  \  /| |_) | | | | |_) || | |  _| | |_) |
# |  __/|  _ <| |_| | |  | | |___  | | |  _  | |___| |_| |___) | | |_| | |  | |/  \  | |___ /  \|  __/| |_| |  _ < | | | |___|  _ <
# |_|   |_| \_\\___/|_|  |_|_____| |_| |_| |_|_____|\___/|____/   \___/|_|  |_/_/\_\ |_____/_/\_\_|    \___/|_| \_\|_| |_____|_| \_\
#
- name: Install the Prometheus JMX Exporter library
  block:
  - name: Create the /opt/prometheus/lib directory
    file:
      path: /opt/prometheus/lib
      owner: root
      group: root
      mode: '0750'
      state: directory

  - debug:
      msg: Check whether the Prometheus JMX Exporter {{ prometheus_jmx_exporter_version }} library has been installed

  - stat:
      path: /opt/prometheus/lib/jmx_prometheus_javaagent-{{ prometheus_jmx_exporter_version }}.jar
    register: prometheus_jmx_exporter_installed_stat_result

  - block:
    - debug:
        msg: Install the Prometheus JMX Exporter {{ prometheus_jmx_exporter_version }} library

    - name: Check whether the Prometheus JMX Exporter {{ prometheus_jmx_exporter_version }} has been downloaded
      become: no
      local_action: stat path=packages/jmx_prometheus_javaagent-{{ prometheus_jmx_exporter_version }}.jar
      register: prometheus_jmx_exporter_package_stat_result

    - name: Download the Prometheus JMX Exporter {{ prometheus_jmx_exporter_version }} library
      become: no
      local_action: get_url url='https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/{{ prometheus_jmx_exporter_version }}/jmx_prometheus_javaagent-{{ prometheus_jmx_exporter_version }}.jar' dest='packages/jmx_prometheus_javaagent-{{ prometheus_jmx_exporter_version }}.jar'
      when: (prometheus_jmx_exporter_package_stat_result.stat.exists == False)

    - name: Copy the Prometheus JMX Exporter {{ prometheus_jmx_exporter_version }} library
      copy:
        src: packages/jmx_prometheus_javaagent-{{ prometheus_jmx_exporter_version }}.jar
        dest: /opt/prometheus/lib/jmx_prometheus_javaagent-{{ prometheus_jmx_exporter_version }}.jar

    when: (prometheus_jmx_exporter_installed_stat_result.stat.exists == False)

  when: ((prometheus_jmx_exporter_enabled is defined) and (prometheus_jmx_exporter_enabled != None) and (prometheus_jmx_exporter_enabled == true))

