# file: roles/kafka_common/tasks/main.yaml

#   ___  ____       ____  ____  _____ ____ ___ _____ ___ ____
#  / _ \/ ___|     / ___||  _ \| ____/ ___|_ _|  ___|_ _/ ___|
# | | | \___ \ ____\___ \| |_) |  _|| |    | || |_   | | |
# | |_| |___) |_____|__) |  __/| |__| |___ | ||  _|  | | |___
#  \___/|____/     |____/|_|   |_____\____|___|_|   |___\____|
#
- include_tasks: ubuntu.yaml
  when: ansible_distribution == "Ubuntu"
  tags:
  - unbound

- include_tasks: centos.yaml
  when: ansible_distribution == "CentOS"
  tags:
  - unbound


#  _  __    _    _____ _  __    _       ____ ___  __  __ __  __  ___  _   _
# | |/ /   / \  |  ___| |/ /   / \     / ___/ _ \|  \/  |  \/  |/ _ \| \ | |
# | ' /   / _ \ | |_  | ' /   / _ \   | |  | | | | |\/| | |\/| | | | |  \| |
# | . \  / ___ \|  _| | . \  / ___ \  | |__| |_| | |  | | |  | | |_| | |\  |
# |_|\_\/_/   \_\_|   |_|\_\/_/   \_\  \____\___/|_|  |_|_|  |_|\___/|_| \_|
#
- name: Add the kafka group
  group:
    name: kafka
    gid: 320
    state: present

- name: Add the kafka user
  user:
    name: kafka
    uid: 320
    group: kafka
    create_home: no
    shell: /usr/sbin/nologin
    state: present

- name: Install kafka
  block:
  - debug:
      msg: Check whether the kafka {{ kafka_version }} package has been installed

  - stat:
      path: /opt/kafka
    register: kafka_installed_stat_result

  - block:
    - debug:
        msg: Install the kafka {{ kafka_version }} package

    - name: Check whether the kafka {{ kafka_version }} package has been downloaded
      become: no
      local_action: stat path=packages/kafka_2.13-{{ kafka_version }}.tgz
      register: kafka_package_stat_result

    - name: Download the kafka {{ kafka_version }} package
      become: no
      local_action: get_url url='http://apache.is.co.za/kafka/{{ kafka_version }}/kafka_2.13-{{ kafka_version }}.tgz' dest='packages/kafka_2.13-{{ kafka_version }}.tgz' checksum={{ kafka_package_checksum }}
      when: (kafka_package_stat_result.stat.exists == False)

    - name: Extract the kafka {{ kafka_version }} package
      unarchive:
        src: packages/kafka_2.13-{{ kafka_version }}.tgz
        dest: /opt

    - name: Create the symbolic link to the kafka {{ kafka_version }} package
      file:
        src: /opt/kafka_2.13-{{ kafka_version }}
        dest: /opt/kafka
        owner: root
        group: root
        state: link

    when: ((kafka_installed_stat_result.stat.exists == False) or (kafka_installed_stat_result.stat.lnk_target != ("/opt/kafka_2.13-" + kafka_version)))

