---
# file: roles/kafka_common/tasks/ubuntu.yaml

- debug:
    msg: Applying the Ubuntu-specific Kafka common configuration

- name: Update the Apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install the openjdk-11-jdk package
  apt:
    name: openjdk-11-jdk
    state: latest
