---
# file: roles/artifactory_oss/tasks/assert.yaml

- name: Check the artifactory_oss.database_host variable is defined correctly
  ansible.builtin.assert:
    that:
    - artifactory_oss.database_host is defined
    - artifactory_oss.database_host is string
    - artifactory_oss.database_host != ''
    quiet: yes

- name: Check the artifactory_oss.database_name variable is defined correctly
  ansible.builtin.assert:
    that:
    - artifactory_oss.database_name is defined
    - artifactory_oss.database_name is string
    - artifactory_oss.database_name != ''
    quiet: yes

- name: Check the artifactory_oss.database_username variable is defined correctly
  ansible.builtin.assert:
    that:
    - artifactory_oss.database_username is defined
    - artifactory_oss.database_username is string
    - artifactory_oss.database_username != ''
    quiet: yes

- name: Check the artifactory_oss.database_password variable is defined correctly
  ansible.builtin.assert:
    that:
    - artifactory_oss.database_password is defined
    - artifactory_oss.database_password is string
    - artifactory_oss.database_password != ''
    quiet: yes
