---
# file: roles/artifactory_oss/tasks/main.yaml

- ansible.builtin.import_tasks: assert.yaml
  run_once: yes
  delegate_to: localhost


#   ___  ____       ____  ____  _____ ____ ___ _____ ___ ____
#  / _ \/ ___|     / ___||  _ \| ____/ ___|_ _|  ___|_ _/ ___|
# | | | \___ \ ____\___ \| |_) |  _|| |    | || |_   | | |
# | |_| |___) |_____|__) |  __/| |__| |___ | ||  _|  | | |___
#  \___/|____/     |____/|_|   |_____\____|___|_|   |___\____|
#
- include_tasks: ubuntu.yaml
  when: ansible_distribution == 'Ubuntu'
  tags:
  - unbound

- include_tasks: redhat.yaml
  when: ansible_os_family == 'RedHat'
  tags:
  - unbound


#     _    ____ _____ ___ _____ _    ____ _____ ___  ______   __   ___  ____ ____
#    / \  |  _ \_   _|_ _|  ___/ \  / ___|_   _/ _ \|  _ \ \ / /  / _ \/ ___/ ___|
#   / _ \ | |_) || |  | || |_ / _ \| |     | || | | | |_) \ V /  | | | \___ \___ \
#  / ___ \|  _ < | |  | ||  _/ ___ \ |___  | || |_| |  _ < | |   | |_| |___) |__) |
# /_/   \_\_| \_\|_| |___|_|/_/   \_\____| |_| \___/|_| \_\|_|    \___/|____/____/
#
- name: Create the /var/tmp/ansible/artifactory_oss directory
  ansible.builtin.file:
    path: /var/tmp/ansible/artifactory_oss
    owner: 'root'
    group: 'root'
    mode: '0700'
    state: directory

- name: Install Artifactory OSS
  block:
  - ansible.builtin.debug:
      msg: Check whether the Artifactory OSS {{ artifactory_oss_config.package_version }} package has been installed

  - ansible.builtin.stat:
      path: /opt/artifactory-oss
    register: artifactory_oss_installed_stat_result

  - block:
    - ansible.builtin.debug:
        msg: Install the Artifactory OSS {{ artifactory_oss_config.package_version }} package

    - name: Check whether the Artifactory OSS {{ artifactory_oss_config.package_version }} package has been downloaded
      become: no
      local_action: ansible.builtin.stat path='{{ packages_root }}/{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}/jfrog-artifactory-oss-{{ artifactory_oss_config.package_version }}-linux.tar.gz'
      register: artifactory_oss_package_stat_result

    - name: Download the Artifactory OSS {{ artifactory_oss_config.package_version }} package
      become: no
      local_action: ansible.builtin.get_url url='https://releases.jfrog.io/artifactory/bintray-artifactory/org/artifactory/oss/jfrog-artifactory-oss/{{ artifactory_oss_config.package_version }}/jfrog-artifactory-oss-{{ artifactory_oss_config.package_version }}-linux.tar.gz' dest='{{ packages_root }}/{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}/jfrog-artifactory-oss-{{ artifactory_oss_config.package_version }}-linux.tar.gz'
      when: (artifactory_oss_package_stat_result.stat.exists == False)

    - name: Extract the Artifactory OSS {{ artifactory_oss_config.package_version }} package
      ansible.builtin.unarchive:
        src: '{{ packages_root }}/{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}/jfrog-artifactory-oss-{{ artifactory_oss_config.package_version }}-linux.tar.gz'
        dest: /opt
        owner: 'root'
        group: 'root'

    - name: Create the symbolic link to the Artifactory OSS {{ artifactory_oss_config.package_version }} package
      ansible.builtin.file:
        src: /opt/artifactory-oss-{{ artifactory_oss_config.package_version }}
        dest: /opt/artifactory-oss
        owner: 'root'
        group: 'root'
        mode: '0755'
        state: link

    when: ((artifactory_oss_installed_stat_result.stat.exists == False) or (artifactory_oss_installed_stat_result.stat.lnk_target != ('/opt/artifactory-oss-' + artifactory_oss_config.package_version)))

#- name: Create the {{ artifactory_oss_config.data_directory }} directory
#  ansible.builtin.file:
#    path: '{{ artifactory_oss_config.data_directory }}'
#    owner: 'root'
#    group: 'root'
#    mode: '0755'
#    state: directory
#  when: ((artifactory_oss_config.data_directory is defined) and (artifactory_oss_config.data_directory != None))
#
