---
# file: roles/gitea/defaults/main.yaml

gitea_defaults:

  package_checksum: sha256:50c25c094ae109f49e276cd00ddc48a0a240b7670e487ae1286cc116d4cdbcf2
  package_version: '1.14.3'

  user: git
  user_id: 305
  group: git
  group_id: 305

  config_directory: /etc/gitea

  data_directory: /var/lib/gitea

  app_name: 'Gitea: Git with a cup of tea'

  run_mode: prod

  users_no_log: true

  admin_username: gitea
  admin_password: gitea
  admin_email: gitea@example.org

  port: 7073

gitea_config: "{{ gitea_defaults | combine(gitea | default({}), recursive=True) }}"
