---
# file: roles/postgresql/tasks/main.yaml

- name: Create the /var/tmp/ansible/{{ role_name }} directory
  file:
    path: '/var/tmp/ansible/{{ role_name }}'
    owner: 'root'
    group: 'root'
    mode: '0700'
    state: directory


#   ___  ____       ____  ____  _____ ____ ___ _____ ___ ____
#  / _ \/ ___|     / ___||  _ \| ____/ ___|_ _|  ___|_ _/ ___|
# | | | \___ \ ____\___ \| |_) |  _|| |    | || |_   | | |
# | |_| |___) |_____|__) |  __/| |__| |___ | ||  _|  | | |___
#  \___/|____/     |____/|_|   |_____\____|___|_|   |___\____|
#
- include_tasks: ubuntu.yaml
  when: ansible_distribution == 'Ubuntu'
  tags:
  - unbound

- include_tasks: redhat.yaml
  when: ansible_os_family == 'RedHat'
  tags:
  - unbound


#  ____   ___  ____ _____ ____ ____  _____ ____   ___  _
# |  _ \ / _ \/ ___|_   _/ ___|  _ \| ____/ ___| / _ \| |
# | |_) | | | \___ \ | || |  _| |_) |  _| \___ \| | | | |
# |  __/| |_| |___) || || |_| |  _ <| |___ ___) | |_| | |___
# |_|    \___/|____/ |_| \____|_| \_\_____|____/ \__\_\_____|
#
- name: Configure global settings
  lineinfile:
    dest: "{{ postgresql_config_directory }}/postgresql.conf"
    regexp: "^#?{{ item.option }}.+$"
    line: "{{ item.option }} = '{{ item.value }}'"
    state: "{{ item.state | default('present') }}"
    mode: 0644
  with_items: "{{ postgresql_config.global_config_options }}"
  notify: restart postgresql

- name: Configure host based authentication (if entries are configured)
  template:
    src: "pg_hba.conf.j2"
    dest: "{{ postgresql_config_directory }}/pg_hba.conf"
    owner: '{{ postgresql_config.user }}'
    group: '{{ postgresql_config.group }}'
    mode: 0600
  when: postgresql_config.hba_entries | length > 0
  notify: restart postgresql


