---
# file: roles/kafka_mirrormaker/tasks/redhat.yaml

- ansible.builtin.debug:
    msg: Applying the RedHat-specific Kafka MirrorMaker configuration

- name: Allow all hosts access to tcp port {{ kafka_config.kafka_mirrormaker.prometheus_jmx_exporter.port }} (Prometheus JMX Exporter Port)
  ansible.posix.firewalld:
    port: '{{ kafka_config.kafka_mirrormaker.prometheus_jmx_exporter.port }}/tcp'
    permanent: yes
    state: enabled
    immediate: yes
  when: ((kafka_config.kafka_mirrormaker.prometheus_jmx_exporter.enabled is defined) and (kafka_config.kafka_mirrormaker.prometheus_jmx_exporter.enabled != None) and (kafka_config.kafka_mirrormaker.prometheus_jmx_exporter.enabled == true))
