---
# file: roles/kafka_mirrormaker/tasks/ubuntu.yaml

- debug:
    msg: Applying the Ubuntu-specific Kafka MirrorMaker configuration

- name: Enable the firewall
  ufw:
    state: enabled
    policy: deny

- name: Allow all hosts access to tcp port {{ kafka_config.kafka_mirrormaker.prometheus_jmx_exporter.port }} (Prometheus JMX Exporter Port)
  ufw:
    rule: allow
    port: '{{ kafka_config.kafka_mirrormaker.prometheus_jmx_exporter.port }}'
    proto: tcp
  when: ((kafka_config.kafka_mirrormaker.prometheus_jmx_exporter.enabled is defined) and (kafka_config.kafka_mirrormaker.prometheus_jmx_exporter.enabled != None) and (kafka_config.kafka_mirrormaker.prometheus_jmx_exporter.enabled == true))



