# file: roles/k8s_master/tasks/ubuntu.yaml

- debug:
    msg: Applying the Ubuntu-specific Kubernetes master configuration

- name: Retrieve the version of the installed kubeadm package
  debug:
    msg: Found kubeadm package version {{ ansible_facts.packages['kubeadm'][0].version  }}
  when: "'kubeadm' in ansible_facts.packages"



