---
# file: roles/prometheus_alert_manager/defaults/main.yaml

prometheus_alert_manager_defaults:
  etc_directory: /etc/alertmanager
  data_directory: /var/lib/alertmanager

  package_checksum: sha256:6fa982232ae7be5524f5b3cd4e90b7c6a75086368200c917644eaa3e806555dc
  package_version: '0.24.0'

  user: alertmanager
  user_id: 456
  group: alertmanager
  group_id: 456

  prometheus_msteams_etc_directory: /etc/prometheus-msteams
  prometheus_msteams_package_checksum: sha256:9a589b4417fc116c153c40d1220dca1f46e6bb8e24b4db0d52ee0c0151de2222
  prometheus_msteams_package_version: 'v1.5.1'
  prometheus_msteams_user: prometheus-msteams
  prometheus_msteams_user_id: 457
  prometheus_msteams_group: prometheus-msteams
  prometheus_msteams_group_id: 457


prometheus_alert_manager_config: "{{ prometheus_alert_manager_defaults | combine(prometheus_alert_manager | default({}), recursive=True) }}"
